delete from message where code IN('pgr.lbl.srn','pgr.msg.sla.infomessage');


insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.srn','SRN(Service Request No.)','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.srn','SRN (सेवा विनंती क्रमांक)','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.sla.infomessage','To ensure timely resolution of your complaint, we have defined "Service Level Agreement - SLA" for each complaint type. The estimation for this category is up to %d days','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.title.mseva.appname','mSeva','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.login','लॉग-इन ','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.register','नोंदणी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.forgot.password','पासवर्ड विसरला','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.password','पासवर्ड','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.new.password','नवीन पासवर्ड','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.confirm.password','संकेतशब्द कन्फर्म करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.city','शहर','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.code','कोड','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.username.blank','वापरकर्तानाव रिक्त असू शकत नाही ','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.city.blank','सिटी रिक्त असू शकत नाही','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.otp.blank','OTP रिक्त असू शकत नाही','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.fullname.blank','आपले पूर्ण नाव प्रविष्ट करा!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.password.confirmpassword.same','पासवर्ड आणि संकेतशब्द कन्फर्म करा समान असावी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.signup','साइन अप करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.user.creation','वापरकर्ता तयार केला गेला करू शकत नाही','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.username.update','वापरकर्ता {$ वापरकर्ता नाव} अद्यतनित करू शकत नाही.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.signup.failed','साइन इन करा अयशस्वी झाले','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.login.failed','लॉग इन अयशस्वी झाले','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.invalid.credentials','अवैध श्रेय','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.opt.generation','व्युत्पन्न किंवा OTP पाठवू शकले नाहीत.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.otp','OTP','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.post.servicerequest','पोस्ट सेवा विनंती','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.generate.otp','OTP निर्माण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.send','पाठवा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.servicename','सेवेचे नाव','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.description','वर्णन','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.servicerequest.notfound','सेवा कोड किंवा तिथल्या प्रचलित आयडी प्रदान किंवा जनरल सेवा त्रुटी नाही.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.bad.servicerequest','सेवा कोड किंवा प्रदान कार्यकक्षा आयडी आढळले नाहीत.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.alert.goto.settings.enable.permissions','सेटिंग्ज वर जा आणि परवानग्या सक्षम','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.alert.externalstorageaccesspermission.harddisk','बाह्य संचय परवानगी SD कार्ड प्रतिमा प्रवेश करण्यासाठी या अनुप्रयोग करीता आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.select.source','स्त्रोत निवडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.photo','फोटो','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.alert.search.here','येथे शोधा ..','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.sla.limit','SLA पर्यंत 4 दिवस','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.sla.infomessage','प्रत्येक तक्रार प्रकार - "SLA  सेवा स्तर करारनामा" आपल्या तक्रारीचे वेळेवर ठराव सुनिश्चित करण्यासाठी, आम्ही निश्चित केले आहेत.  वर्ग अंदाज  %d  दिवस आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.location.change.infomessage','डिफॉल्ट आपले वर्तमान स्थान दर्शवेल. आपण नेहमी स्थान पिन क्लिक करून स्थान बदलू शकता','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.select.location','स्थान निवडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.file.complaint','तक्रार दाखल','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.my.complaints','माझ्या तक्रारी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.uri.list','URI यादी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.deleted.uri.list','हटविले URI निर्देशांक यादी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.uri.selection','URI निवड','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.complete.signup','तो फक्त साइन-अप पूर्ण 2 मिनिटे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaintno','तक्रार नाही','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.department','विभाग','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.date.format','dd-MM-yyyy hh:mm:ss','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.date.format.mobileui','dd MMMM yyyy','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complainthistory.date.format','dd MMM yyyy','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.selected.servicerequest.key','selected_service_request','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.notifications','सूचना','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaint.sentto','तक्रार पाठविले','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaint.field','तक्रार दाखल','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaint.update','तक्रार अद्यतन','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.title.listen','आम्ही ऐकतो','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.title.connect','आम्ही कनेक्ट','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.title.track','आम्ही मागोवा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.title.solve','आम्ही सोडवा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.complaint.tellus','तक्रार आम्हाला सांगा आहे.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.complaint.connectto.official','आम्ही जबाबदार अधिकृत कनेक्ट','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.official.resolve.complaint','आमच्या अधिकृत तक्रार निर्धारण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.page.footer','eGovernments Foundation द्वारा समर्थित','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.receivingmode','प्राप्त मोड','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.receivingcenter','केंद्र प्राप्त','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.required','आवश्यक','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.title.egoverp','eGov ERP','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.signout','साइन आउट','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.worklist','Worklist','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.drafts','मसुदे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.history','इतिहास','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.cancel','रद्द करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.resetclear','साफ करा / रीसेट करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.date','तारीख','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.sender','प्रेषक','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.natureofwork','कामाचे स्वरूप','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.status','स्थिती','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.comments','टिप्पण्या','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.title.citizenportal','नागरिक पोर्टल','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.inbox','इनबॉक्स','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.myaccount','माझे खाते','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.newrequest','नवीन विनंती','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.sortby','क्रमवारी लावा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.recentmessages','अलीकडील संदेश','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.usermessages','वापरकर्ता संदेश','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.system.notifications','प्रणाली सूचना','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.redressal','तक्रार निवारण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.register.grievance','नोंदणी तक्रार','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.view.grievance','तक्रार पहा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error','त्रुटी!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.title.create.account','खाते तयार करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.enter.mobilenumber','आपल्या वैध 10 अंकी मोबाईल नंबर प्रविष्ट करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.alert.agree.signup','साइन अप केल्याने, आपण समजून आणि वापर गोपनीयता आणि सुरक्षा धोरण आमच्या अटी मान्य करता','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.password','किमान 8 characters.Should वापरा असू वरच्या व खालच्या केस वर्णमाला, संख्या आणि [<> & #% " ''/ \ आणि मोकळी जागा] वगळता विशेष वर्ण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.account.created.successfully','आपले खाते यशस्वीरित्या तयार','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.otp.validation.failed','OTP प्रमाणीकरण अयशस्वी!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.date','तक्रार दिनांक','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.department','तक्रार विभाग','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.nextescalation.date','पुढील वृद्धी दिनांक','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.filedvia','द्वारे दाखल','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.updatedby','अद्यतनित','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.currentowner','चालू मालक / अधिकारी जबाबदार','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.history','तक्रार इतिहास','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.actions','क्रिया','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.change.status','स्थिती बदला','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.change.grievancetype','बदल तक्रार प्रकार','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.change.jurisdiction','कार्यक्षेत्र बदला','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.forwardto','पुढे तक्रार करण्यासाठी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.include.message','संदेश समाविष्ट करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.submit','सादर','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.search.grievance','तक्रार शोध','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.more','अधिक ..','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.less','कमी..','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaintnumber','तक्रार क्रमांक','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.registered.date','नोंदणीची तारीख','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.clickfor.demo','डेमो क्लिक करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.valid.email','आपला वैध ई-मेल आयडी प्रविष्ट करा!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.residential.address','तुमच्या सध्याच्या पत्ता प्रविष्ट करा!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.select.grievance.categoryandtype','येथून आपली तक्रार निवडा नाहीतर तक्रार श्रेणी आणि तक्रार प्रकार खाली पासून निवड!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.select.grievance.category','श्रेणी निवडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.select.grievance.type','प्रकार निवडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.describe.grievance.details','थोडक्यात आपली तक्रार तपशील वर्णन!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.upload.photovideo','तक्रार relevated फोटो / व्हिडिओ अपलोड (कमाल: 3 फाइल)!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.landmark.optional','आपल्या शेताची हद्द दाखवणारी खूण प्रविष्ट करा (जर असेल तर)!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.finalgrievance.submit','शेवटी, आपली तक्रार सबमिट करण्यासाठी येथे क्लिक करा!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.signin','साइन इन करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.locale','लोकॅल निवडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.follow','आम्हाला वर अनुसरण करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.msg.number.required','तक्रार संख्या अनिवार्य आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.addmobilenumber/login','मोबाइल नंबर / लॉगिन आयडी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.forgot','विसरलात?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.incorrect.usename/password','वापरकर्तानाव किंवा संकेतशब्द चुकीचा आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.signup.agree','साइन अप केल्याने, आपण समजून आणि सहमत आमच्या','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.terms','वापरण्याच्या अटी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.policies','गोपनीयता आणि सुरक्षा धोरणे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.privacy.policy','गोपनीयता धोरण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.security.policy','सुरक्षा धोरण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.email.compulsory','ई - मेल आयडी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.category','तक्रार वर्ग','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.type','तक्रार प्रकार','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.location.icon','तुमची तक्रार स्थान टायपिंग प्रारंभ किंवा स्थान चिन्ह पसंत','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.types','शीर्ष तक्रार प्रकार','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.grievance.photo/video','फोटो / व्हिडिओ','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.update','तक्रार अद्यतन','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.citizen','माझे तक्रार','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.home.page','कॉपीराइट','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.home','घर','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.city.kurnool','कुर्नुल','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.new.mseva','mSeva वर नवीन आहात?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.resend.otp','OTP परत पाठवा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.enter.otp','प्रविष्ट 5 अंकी OTP क्रमांक आपला मोबाइल नंबर पाठविले','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.account.create','आपले खाते तयार करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.question.good','जे चांगल आहे ते ?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.question.bad','काय वाईट आहे?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.mark.resolved','निराकरण झाले म्हणून चिन्हांकित','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.resolved','सोडवलेले','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.service','सेवा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.resolve.time','वेळ निराकरण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.work','काम','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.other','इतर','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaint.details','तक्रार तपशील','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.complaint.filedby','दाखल','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.rate.experience','आपले अनुभव रेट','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.complaint.closed','तक्रार यशस्वीरित्या बंद.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.complaint.details.characters','वर्णन किमान 10 वर्ण लांब असणे आवश्यक आहे.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.select.photo','फोटो निवडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.upload.image','प्रतिमा अपलोड करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.location','स्थान','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.select.map','नकाशा निवडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.pending','प्रलंबित','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.completed','पूर्ण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.kurnool.feedback','आम्हाला चांगले कुर्नुल करण्यास मदत करा. आम्ही आपल्यासाठी निराकरण करू शकता तक्रार आहे तर आम्हाला कळवा.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaints.resolved','तकर्ार िनवारण निराकरण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.platform','आमच्या प्लॅटफॉर्म. तुझा आवाज','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.how.work','हे कसे कार्य करते?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.registercomplaint.easy','आम्ही पूर्वीपेक्षा सोपे आम्हाला सह कनेक्ट केले आहे. आपण तक्रार वाढवण्याची एकदा, आम्ही जबाबदार अधिकारी ते नेमतील. आपली तक्रार निराकरण होईपर्यंत "माझी तक्रारी" अंतर्गत आमच्या वेबसाइटवर आपल्या तक्रारीची स्थिती ट्रॅक करू शकता.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaint.raise','तक्रार वाढवण्याची','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.connect.concerned','संबंधित अधिका-कनेक्ट','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.track.complaintstatus','ट्रॅक स्थिती','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.available.playstore','PlayStore वर उपलब्ध आहे.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.download.app','अनुप्रयोग डाउनलोड करा.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0001','अक्षांश / रेखांश किंवा क्रॉस उतरंड आयडी  आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0002','अक्षांश / रेखांश किंवा क्रॉस उतरंड आयडी  आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0003','अक्षांश / रेखांश किंवा क्रॉस उतरंड आयडी  आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0004','स्थान आयडी आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0005','प्रथम नाव आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0006','फोन आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0008','वापरकर्ता आयडी आवश्यक आ','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0009','प्राप्त मोड आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0010','प्राप्त केंद्र आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0011','भाडेकरू आयडी आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0012','सेवा कोड आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0013','वर्णन आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.0014','सेवा विनंती आयडी आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.success.grievanceupdated','तक्रार यशस्वीरित्या अद्यतनित!','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.date.fromdate','या तारखेपासून','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.date.todate','तारीख करण्यासाठी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.reset','रीसेट करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.add.name','नाव','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','USER.USER_NAME_ALREADY_EXISTS','वापरकर्तानाव आधीच अस्तित्वात आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core-user.006','OTP वैधता प्रलंबित आहे.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','USER.USER_NOT_FOUND','वापरकर्ता सापडला नाही','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core-user.001','लिंग आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core-user.002','प्रकार आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core-user.004','मोबाइल नंबर आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','OTP.IDENTITY_MANDATORY','ओळख क्षेत्रात आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','OTP.TENANT_ID_MANDATORY','भाडेकरू क्षेत्रात आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','OTP.UUID_MANDATORY','UUID क्षेत्रात आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','OTP.OTP_MANDATORY','OTP क्षेत्रात आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.criteria.required','किमान एक शोध निकष आवश्यक आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.fileformat.notallowed','फाइल स्वरूप परवानगी नाही','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.notvalid.srn','एक वैध SRN','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.file.exceed','फाइल आकार 5MB मर्यादा ओलांडली आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.add.comment','टिप्पणी करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.address.mandatory','पत्ता आवश्यक','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.complaint.resolved','तक्रार निराकरण','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.contact.us','संपर्क','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.dept','विभाग','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.work.done','पूर्ण झाले','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.eGov','eGovernments Foundation','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.enter.OTP','OTP प्रविष्ट करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.work.finish','फिनिश','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.fullname.cantblank','पूर्ण नाव रिक्त असू शकत नाहीत','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.letsgetstarted','सुरु करूया','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.know.more','अधिक वाचा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.login/signup','लॉगिन करा किंवा साइन अप','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.logout','बाहेर पडणे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.closenavigation','नेव्हिगेशन ड्रॉवर बंद करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.opennavigation','नेव्हिगेशन ड्रॉवर उघडा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.servicejuridiction.notfound','service_code किंवा प्रदान jurisdiction_id आढळले नाहीत.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.generalservice','service_code किंवा jurisdiction_id प्रदान किंवा सामान्य सेवा त्रुटी नाही.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.nxt','पुढे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.user.notupdatable','वापरकर्ता अद्यतनित करू शकत नाही.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.otp.sent.entertocreateaccount','आम्ही आपल्या नोंदणीकृत मोबाईल नंबर 4 अंकी OTP पाठविले आहेत. आपले खाते तयार करण्यासाठी OTP प्रविष्ट करा.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.notblank.password','पासवर्ड रिक्त असू शकत नाहीत','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.notblank.phone','फोन नंबर रिक्त असू शकत नाहीत','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.error.internet.tryagain','इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.plse.wait','कृपया थांबा. . .','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.poweredby','द्वारा समर्थित','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.profile','प्रोफाइल','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.enter.mobileno','मोबाइल नंबर एंटर करा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.Resend','पुन्हा पाठवा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.all.complaints','तक्रारी','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.skip','टाळा','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.status.update','स्थिती अद्यतनित','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.welcome','आपले स्वागत आहे','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.list.complaint.history','तक्रार इतिहास','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.details','तपशील','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.otp.notreceived','ओटीपी प्राप्त झाले नाही?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.SLA.days.of','% d दिवस SLA','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.SLA.days.upto','SLA% d दिवस पर्यंत','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.month.day.year','MM-dd-yyyy hh:mm:ss a','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.more','+%d\r\nMore','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.signin','Sign In','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.locale','Select locale','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.follow','Follow us on','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.forgot','forgot?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.msg.number.required','Grievance number is mandatory','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.addmobilenumber/login','Mobile number / Login ID','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.incorrect.usename/password','Username or Password is incorrect','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.terms','Terms of use','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.policies','Privacy & Security Policies','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.privacy.policy','Privacy Policy','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.security.policy','Security Policy','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.email.compulsory','Email ID','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.category','Grievance Category','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.type','Grievance Type','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.location.icon','Start typing your Grievance location or select it from location icon','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.types','Top Grievance Types','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.grievance.photo/video','Photos/Video','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.update','Update Grievance','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.citizen','My Grievances','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.home.page','Copyright','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.home','Home','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.city.kurnool','Kurnool','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.new.mseva','New to mSeva ?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.resend.otp','Resend OTP','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.enter.otp','Enter the 5 digit OTP number sent to your mobile number','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.account.create','Create Your Account','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.question.good','What is good ?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.question.bad','What is bad ?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.mark.resolved','Mark resolved','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.resolved','Resolved','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.service','Service','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.resolve.time','Resolve Time','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.work','Work','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.other','Other','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaint.details','Complaint Details','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.complaint.filedby','Filed By','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.rate.experience','Rate Your Experience','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.complaint.closed','Complaint closed successfully.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.complaint.details.characters','Description must be at least 10 characters long.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.select.photo','Select Photo','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.upload.image','Upload Image','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.location','Location','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.select.map','Select from the map','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.pending','Pending','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.completed','Completed','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.kurnool.feedback','Help us make Kurnool better. Let us know if there is a complaint we can solve for you.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaints.resolved','COMPLAINTS RESOLVED','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.platform','Our Platform. Your Voice','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.how.work','How it works?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.registercomplaint.easy',' We have made connecting with us easier than ever before. Once you raise the complaint , we will assign it to the responsible officer. You can track the status of your complaint on our website under “My Complaints” till your complaint is resolved.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaint.raise','Raise a complaint','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.connect.concerned','Connect to concerned officer','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.track.complaintstatus','Track Status','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.available.playstore','is currently available on playstore.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.download.app','Download the app.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0001','latitude/longitude or cross hierarchy id is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0002','latitude/longitude or cross hierarchy id is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0003','latitude/longitude or cross hierarchy id is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0004','Location id is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0005','First name is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0006','Phone is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0008','User id is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0009','Receiving mode is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0010','Receiving center is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0011','Tenant id is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0012','Service code is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0013','Description is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.0014','Service request id is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.success.grievanceupdated','Grievance updated succesfully','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.date.fromdate','From Date','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.date.todate','To Date','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.reset','Reset','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.add.name','Name','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','USER.USER_NAME_ALREADY_EXISTS','User name already exists','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core-user.006','Otp validation is pending.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','USER.USER_NOT_FOUND','User not found','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core-user.001','Gender is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core-user.002','Type is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core-user.004','Mobile number is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','OTP.IDENTITY_MANDATORY','Identity field is mandatory','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','OTP.TENANT_ID_MANDATORY','Tenant field is mandatory','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','OTP.UUID_MANDATORY','UUID field is mandatory','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','OTP.OTP_MANDATORY','Otp field is mandatory','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.criteria.required','Atleast one search criteria is required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.fileformat.notallowed','file format is not allowed','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.notvalid.srn','Not a valid SRN','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.signup.agree','By doing sign up, you understood and agree to our','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.add.comment','Add Comment','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.address.mandatory','Address required','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.complaint.resolved','Complaint resolved','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.contact.us','Contact','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.dept','Dept','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.work.done','Done','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.eGov','eGovernments Foundation','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.enter.OTP','Enter OTP','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.work.finish','FINISH','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.fullname.cantblank','Full Name can''t be blank','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.letsgetstarted','GET STARTED','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.know.more','Know More','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.login/signup','LogIn or SignUp','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.logout','Logout','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.closenavigation','Close navigation drawer','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.opennavigation','Open navigation drawer','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.servicejuridiction.notfound','service_code or jurisdiction_id provided were not found.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.generalservice','service_code or jurisdiction_id was not provided or General service error.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.nxt','NEXT','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.user.notupdatable','Not able to update user.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.otp.sent.entertocreateaccount','We have sent 4 digit otp number to your registered mobile number. Enter the OTP to create your account.','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.notblank.password','Password can''t be blank','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.notblank.phone','Phone number can''t be blank','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.internet.tryagain','Please check internet connection and try again','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.plse.wait','Please Wait. . .','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.poweredby','Powered by','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.profile','Profile','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.enter.mobileno','Enter Mobile Number','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.Resend','RESEND','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.all.complaints','Complaints','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.skip','SKIP','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.status.update','updated the status','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.welcome','WELCOME','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.list.complaint.history','Complaint History','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.details','Details','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.otp.notreceived','Didn''t receive OTP?','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.SLA.days.of','SLA of %d Days','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.SLA.days.upto','SLA upto %d days','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.month.day.year','MM-dd-yyyy hh:mm:ss a','ap.public');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.more','+%d\r\nMore','ap.public');





