insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.title.mseva.appname','mSeva','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.login','Login','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.register','Register','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.forgot.password','Forgot Password?','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.password','Password','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.new.password','New Password','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.confirm.password','Confirm Password','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.fullname','Full Name','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.city','City','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.code','Code','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.mobilenumber','Mobile Number','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.email','Email Address (Optional)','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.username.blank','Username can''t be blank','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.city.blank','City can''t be blank','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.otp.blank','OTP can''t be blank','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.fullname.blank','Enter your full name!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.password.confirmpassword.same','Password and Confirm Password should be same','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.alert.pleasewait','Processing your request. Please wait..','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.signup','Sign Up','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.user.creation','User couldn''t have been created.','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.username.update','Not able to update user {$userName}.','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.signup.failed','Sign-up failed','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.login.failed','Login failed','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.invalid.credentials','Invalid Credentials','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.opt.generation','Could not generate or send OTP.','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.otp','OTP','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.post.servicerequest','Post Service Request','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.generate.otp','Generate OTP','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.send','Send','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.servicename','Service Name','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.address','Address','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.description','Description','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.landmark','Landmark','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.servicerequest.notfound','service code or jurisdiction id was not provided or General service error.','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.bad.servicerequest','service code or jurisdiction id provided were not found.','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.alert.goto.settings.enable.permissions','Go to settings and enable permissions','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.alert.externalstorageaccesspermission.harddisk','External storage Permission is required for this app to access images from SD card','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.select.source','Select Source','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.photo','Photo','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.alert.search.here','Search here..','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaint.category','Complaint Category','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.upload.photoimage','Upload Photograph/Video','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.sla.limit','SLA upto 4 days','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.sla.infomessage','To ensure timely resolution of your complaint, we have defined \"Service Level Agreement - SLA\" for each complaint type. The estimation for this category is up to 4 days','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.location.change.infomessage','By default it will show your current location. You can always change the location by clicking on the location pin','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.select.location','Select Location','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.file.complaint','File a complaint','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.my.complaints','My complaints','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.uri.list','uri list','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.deleted.uri.list','deleted uri index list','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.uri.selection','uri selection','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.complete.signup','It just takes 2 minute to complete sign-up','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaintno','Complaint No','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complainttype','Complaint Type','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.department','Department','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.date.format','dd-MM-yyyy hh:mm:ss','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.date.format.mobileui','dd MMMM yyyy','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complainthistory.date.format','dd MMM yyyy','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.selected.servicerequest.key','selected_service_request','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.notifications','Notifications','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaint.sentto','Complaint Sent to ','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaint.field','Complaint Filed','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaint.update','Complaint Update','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.title.listen','We Listen','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.title.connect','We Connect','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.title.track','We Track','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.title.solve','We Solve','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.complaint.tellus','Have a complaint tell us.','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.complaint.connectto.official','We connect you to the responsible official','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.complaintstatus.anytime','Know the status of your complaint anytime!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.official.resolve.complaint','Our official resolves the complaint','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.title.create.grievence','Create Grievance','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.page.footer','Powered by eGovernments Foundation','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.servicerequest.underprocess','Service Request is received and is under process','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.srn','Your SRN(Service Request No.)','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.future.reference','Please use this for all your future references','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.contact.information','Contact Information','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.receivingmode','Receiving Mode','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.receivingcenter','Receiving Center','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.required','Required','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievence.information','Grievance Information','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.top.griencetypes','Select from Top Grievance types','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.or','OR','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.moredetails','More Details','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievancedetails','Grievance Details','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.minmax.characters','Minimum 10 and maximum 500 characters','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.close','Close','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.location','Grievance Location','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.ok','Ok','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.acknowledgement','Acknowledgement','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.title.egoverp','eGov ERP','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.signout','Sign Out','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.worklist','Worklist','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.drafts','Drafts','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.history','History','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.cancel','Cancel','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.resetclear','Reset / Clear','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.date','Date','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.sender','Sender','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.natureofwork','Nature of Work','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.status','Status','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.comments','Comments','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.title.citizenportal','Citizen Portal','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.inbox','Inbox','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.myaccount','My Account','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.newrequest','New Request','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.sortby','Sort by','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.recentmessages','Recent Messages','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.usermessages','User Messages','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.system.notifications','System Notifications','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.redressal','Grievance Redressal','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.register.grievance','Register Grievance','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.view.grievance','View Grievance','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error','Error!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.title.create.account','Create an account','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.enter.mobilenumber','Please enter your valid 10 digit mobile number','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.alert.agree.signup','By doing sign up, you understood and agree to our Terms of use Privacy and security policies','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.password','Use atleast 8 characters.Should contain upper and lower case alphabet, number and special character except [&amp; < > # % &quot; '' / \\ and space]','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.account.created.successfully','Your account created successfully','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.otp.validation.failed','OTP validation failed!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.date','Grievance Date','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.department','Grievance Department','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.nextescalation.date','Next Escalation Date','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.filedvia','Filed via','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.updatedby','Updated By','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.currentowner','Current Owner/Officer Responsible','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.grievance.history','Grievance History','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.actions','Actions','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.change.status','Change Status','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.change.grievancetype','Change Grievance Type','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.change.jurisdiction','Change Jurisdiction','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.forwardto','Forward Grievance To','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.include.message','Include Message','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.submit','Submit','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.search.grievance','Search Grievance','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.more','More..','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.less','Less..','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.search','Search','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.complaintnumber','Complaint Number','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.lbl.registered.date','Registered Date','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.msg.clickfor.demo','Click for Demo','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.valid.email','Enter your valid email id!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.error.residential.address','Enter your present residential address!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.select.grievance.categoryandtype','Select your grievance from here or else choose it from below grievance category and grievance type!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.select.grievance.category','Select your grievance category!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.select.grievance.type','Select your grievance type!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.describe.grievance.details','Describe your grievance details briefly!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.upload.photovideo','Upload grievance relevated photo / video (Max : 3 files)!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.select.grievancelocation','Enter your grievance location or click on the location icon to select your desired location from the map!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.error.landmark.optional','Enter your landmark (if any)!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.finalgrievance.submit','Finally, Click here to submit your grievance!','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.save','Save','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','core.lbl.setlanguage','Set Language','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.complaint.moredetails','Give more details about the complaint to help us solve your issue','default');
insert into message values (nextval('SEQ_MESSAGE'),'en_IN','pgr.msg.creategrievance.avail.onlineservices','Create an Grievance to avail our online services','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.contact.information','संपर्क माहिती','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.fullname','नाव','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.mobilenumber','मोबाइल क्रमांक','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.email','ई-मेल','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.address','पत्ता','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievence.information','तक्रार माहिती','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.top.griencetypes','शीर्ष तक्रार प्रकारच्या निवडा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complaint.category','तक्रार वर्ग','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.complainttype','तक्रार प्रकार','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.moredetails','अधिक माहितीसाठी','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievancedetails','तक्रार तपशील','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.upload.photoimage','फोटो / व्हिडिओ अपलोड करा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.grievance.location','तक्रार स्थान','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.landmark','महत्त्वाची खूण (असल्यास)','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.title.create.grievence','तक्रार तयार करा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.close','बंद','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.or','किंवा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.ok','ठीक आहे','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.save','जतन करा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.setlanguage','भाषा सेट करा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.alert.pleasewait','आपल्या विनंतीवर प्रक्रिया करीत आहे. कृपया थांबा..','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.minmax.characters','कमीत कमी 10 आणि जास्तीत जास्त 500 वर्ण.','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.msg.acknowledgement','पोच','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.creategrievance.avail.onlineservices','आमच्या ऑनलाइन सेवा मिळवण्यासाठी एक तक्रार तयार करा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.complaintstatus.anytime','आपली तक्रार स्थिती तपासा','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','core.lbl.search','शोध','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.complaint.moredetails','आम्हाला आपल्या समस्येचे निराकरण करण्यात मदत करण्यासाठी याबाबत अधिक तपशील द्या','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.error.select.grievancelocation','तुमची तक्रार स्थान टायपिंग प्रारंभ किंवा नकाशा चिन्ह उजव्या बाजूला वर दर्शविलेल्या पसंत','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.servicerequest.underprocess','सेवा विनंती प्राप्त झाली आहे आणि प्रक्रिया आहे.','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.lbl.srn','आपल्या SRN (सेवा विनंती क्रमांक)','default');
insert into message values (nextval('SEQ_MESSAGE'),'mr_IN','pgr.msg.future.reference','कृपया आपल्या भविष्यातील सर्व संदर्भ हे वापरू','default');
