INSERT INTO egwtr_gapcode (id, code, name, outSideUlb,noOfLastMonths,logic,active,description,createdDate,lastModifiedDate,createdBy,lastModifiedBy,tenantid) VALUES (1,nextval('seq_egwtr_gapcode'),'Last 3 months Average','False','Last 3 months','Average',True,NULL,(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),1, 1, 'default');
INSERT INTO egwtr_gapcode (id, code, name, outSideUlb,noOfLastMonths,logic,active,description,createdDate,lastModifiedDate,createdBy,lastModifiedBy,tenantid) VALUES (2,nextval('seq_egwtr_gapcode'),'Last 3 Months Highest','False','Last 3 months','Highest',True,NULL,(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),1, 1, 'default');
INSERT INTO egwtr_gapcode (id, code, name, outSideUlb,noOfLastMonths,logic,active,description,createdDate,lastModifiedDate,createdBy,lastModifiedBy,tenantid) VALUES (3,nextval('seq_egwtr_gapcode'),'Last 3 months Lowest','False','Last 3 months','Lowest',True,NULL,(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),1, 1, 'default');
INSERT INTO egwtr_gapcode (id, code, name, outSideUlb,noOfLastMonths,logic,active,description,createdDate,lastModifiedDate,createdBy,lastModifiedBy,tenantid) VALUES (4,nextval('seq_egwtr_gapcode'),'Last 6 months Average','False','Last 6 months','Average',True,NULL,(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),1, 1, 'default');
INSERT INTO egwtr_gapcode (id, code, name, outSideUlb,noOfLastMonths,logic,active,description,createdDate,lastModifiedDate,createdBy,lastModifiedBy,tenantid) VALUES (5,nextval('seq_egwtr_gapcode'),'Last 6 Months Highest','False','Last 6 months','Highest',True,NULL,(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),1, 1, 'default');
INSERT INTO egwtr_gapcode (id, code, name, outSideUlb,noOfLastMonths,logic,active,description,createdDate,lastModifiedDate,createdBy,lastModifiedBy,tenantid) VALUES (6,nextval('seq_egwtr_gapcode'),'Last 6 months Lowest','False','Last 6 months','Lowest',True,NULL,(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),1, 1, 'default');
INSERT INTO egwtr_gapcode (id, code, name, outSideUlb,noOfLastMonths,logic,active,description,createdDate,lastModifiedDate,createdBy,lastModifiedBy,tenantid) VALUES (7,nextval('seq_egwtr_gapcode'),'Last month reading','False','Last month','',True,NULL,(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),(SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2017-08-27')),1, 1, 'default');





