INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'NEW AGREEMENT', 'Assistant Approved', 'Payament Pending', 'Revenue Officer', 'Assistant Approved', 'Forward', NULL, NULL, '2017-01-01', '2099-04-01', 'ap.public');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'NEW AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'ap.public');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Agreement', 'Advance Paid', NULL, NULL, 'Commissioner', 'NEW AGREEMENT', 'Commissioner approved', 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'Commissioner approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'ap.public');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'NEW AGREEMENT', 'END', 'END', NULL, NULL, NULL, NULL, NULL, '2017-01-01', '2099-04-01', 'ap.public');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'NEW AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'ap.public');
