node {
        stage "Prepare environment"
            checkout scm
            docker.image('node').inside {
                stage "Build"
                    sh "mvn clean package"
            }
        stage('Publish to docker hub') {
            when { currentBuild.result == 'SUCCESS' }
            steps {
                echo "Publish ${env.BUILD_ID} to docker hub"
            }
        }
}