ALTER TABLE egtl_license
ALTER COLUMN mobileNumber DROP NOT NULL,
ALTER COLUMN fatherSpouseName DROP NOT NULL,
ALTER COLUMN emailId DROP NOT NULL,
ALTER COLUMN ownerAddress DROP NOT NULL,
ALTER COLUMN ownerShipType DROP NOT NULL,
ALTER COLUMN category DROP NOT NULL,
ALTER COLUMN subCategory DROP NOT NULL,
ALTER COLUMN uom DROP NOT NULL,
ALTER COLUMN tradeCommencementDate DROP NOT NULL,
ALTER COLUMN adminWard DROP NOT NULL,
ALTER COLUMN licenseValidFromDate DROP NOT NULL,
ALTER COLUMN expiryDate DROP NOT NULL;