Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'New-HierarchyType','/hierarchytype/new',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'New-HierarchyType',true,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='New-HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Create-HierarchyType','/hierarchytype/create',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'Create-HierarchyType',false,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Create-HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Update-HierarchyType','/hierarchytype/update',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'Update-HierarchyType',false,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Update-HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'View-HierarchyType','/hierarchytype/view',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'View-HierarchyType',false,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='View-HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Edit-HierarchyType','/hierarchytype/edit',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'Edit-HierarchyType',false,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Edit-HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Result-HierarchyType','/hierarchytype/result',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'Result-HierarchyType',false,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Result-HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'View HierarchyType','/hierarchytype/search/view',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),2,'View HierarchyType',true,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='View HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Edit HierarchyType','/hierarchytype/search/edit',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),3,'Edit HierarchyType',true,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Edit HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View Result-HierarchyType','/hierarchytype/ajaxsearch/view',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'Search and View Result-HierarchyType',false,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View Result-HierarchyType'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit Result-HierarchyType','/hierarchytype/ajaxsearch/edit',(select id from eg_module where name='Masters' and parentmodule=(select id from eg_module where name='Location Management' and parentmodule is null)),1,'Search and Edit Result-HierarchyType',false,'/egb',(select id from eg_module where name='Location Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit Result-HierarchyType'));

