--service
insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'BILLING_SERVICE', 'Billing Service', false, 'Billing Service', 1, NULL, 'default');

insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'BS_MASTERS', 'Billing Masters', true, 'Masters', 1, (select id from service where name ='Billing Service' and code='BILLING_SERVICE' and tenantId='default'), 'default');

insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'BS_TAXHEADS', 'BS Tax Heads', true, 'Tax Heads', 3, (select id from service where name ='Billing Masters' and code='BS_MASTERS' and tenantId='default'), 'default');

insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'BS_BUSINESS_SERVICE', 'BS Business Service', true, 'Business Service', 3, (select id from service where name ='Billing Masters' and code='BS_MASTERS' and tenantId='default'), 'default');

insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'BS_GLCODE_MASTER', 'BS GLCode Master', true, 'GLCode Master', 3, (select id from service where name ='Billing Masters' and code='BS_MASTERS' and tenantId='default'), 'default');

insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'BS_TAX_PERIODS', 'BS Tax Periods', true, 'Tax Periods', 3, (select id from service where name ='Billing Masters' and code='BS_MASTERS' and tenantId='default'), 'default');

insert into eg_roleaction(roleCode, actionid, tenantId) select 'SUPERUSER', id, 'default' from eg_action where servicecode in ('BILLING_SERVICE', 'BS_MASTERS', 'BS_TAXHEADS', 'BS_BUSINESS_SERVICE', 'BS_GLCODE_MASTER', 'BS_TAX_PERIODS');

--Actions
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'UpdateCollection', '/billing-service/demand/collection/_update', 'BILLING_SERVICE', null, 1, 'Update Collection', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'BS_SearchDemandDetail', '/billing-service/demand/demanddetail/_search', 'BILLING_SERVICE', null, 2, 'Search Demand Detail', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'UpdateDemand', '/billing-service/demand/_update', 'BILLING_SERVICE', null, 3, 'Update Demand', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'CreateDemand', '/billing-service/demand/_create', 'BILLING_SERVICE', null, 4, 'Create Demand', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'SearchDemand', '/billing-service/demand/_search', 'BILLING_SERVICE', null, 5, 'Search Demand', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'UpdateTaxHead', '/billing-service/taxheads/_update', 'BS_TAXHEADS', null, 6, 'Update Tax Head', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'CreateTaxHead', '/billing-service/taxheads/_create', 'BS_TAXHEADS', null, 7, 'Create Tax Head', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'SearchTaxHead', '/billing-service/taxheads/_search', 'BS_TAXHEADS', null, 8, 'Search Tax Head', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'GenerateBill', '/billing-service/bill/_generate', 'BILLING_SERVICE', null, 9, 'Generate Bill', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Apportion', '/billing-service/bill/_apportion', 'BILLING_SERVICE', null, 10, 'Apportion', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'CreateBill', '/billing-service/bill/_create', 'BILLING_SERVICE', null, 11, 'Create Bill', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'SearchBill', '/billing-service/bill/_search', 'BILLING_SERVICE', null, 12, 'Search Bill', false, 1, now(), 1, now());
	insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'UpdateBusinessService', '/billing-service/businessservices/_update', 'BS_BUSINESS_SERVICE', null, 13, 'Update Business Service', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'CreateBusinessService', '/billing-service/businessservices/_create', 'BS_BUSINESS_SERVICE', null, 14, 'Create Business Service', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'SearchBusinessService', '/billing-service/businessservices/_search', 'BS_BUSINESS_SERVICE', null, 15, 'Search Business Service', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'UpdateGlcodeMaster', '/billing-service/glcodemasters/_update', 'BS_GLCODE_MASTER', null, 16, 'Update Glcode Master', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'CreateGlcodeMaster', '/billing-service/glcodemasters/_create', 'BS_GLCODE_MASTER', null, 17, 'Create Glcode Master', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'SearchGlcodeMaster', '/billing-service/glcodemasters/_search', 'BS_GLCODE_MASTER', null, 18, 'Search Glcode Master', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'BS_UpdateTaxPeriod', '/billing-service/taxperiods/_update', 'BS_TAX_PERIODS', null, 19, 'Update Tax Period', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'BS_CreateTaxPeriod', '/billing-service/taxperiods/_create', 'BS_TAX_PERIODS', null, 20, 'Create Tax Period', false, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'BS_SearchTaxPeriod', '/billing-service/taxperiods/_search', 'BS_TAX_PERIODS', null, 21, 'Search Tax Period', false, 1, now(), 1, now());


--role actions
insert into eg_roleaction(roleCode, actionid, tenantId) select 'SUPERUSER', id, 'default' from eg_action where servicecode in ('BILLING_SERVICE', 'BS_MASTERS', 'BS_TAXHEADS', 'BS_BUSINESS_SERVICE', 'BS_GLCODE_MASTER', 'BS_TAX_PERIODS');
