insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'Contractors', 'Contractors', true, 'Contractors', 1, (select id from service where code = 'WORKS_MASTERS' and tenantId='default'), 'default');

insert into eg_action(id, name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Create Contractor', '/works-masters/contractors/_create', 'Contractors', null, 0, 'Create Contractor', true, 1, now(), 1, now());
insert into eg_action(id, name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Update Contractor', '/works-masters/contractors/_update', 'Contractors', null, 1, 'Update Contractor', false, 1, now(), 1, now());
insert into eg_action(id, name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Search Contractor', '/works-masters/contractors/_search', 'Contractors', null, 2, 'Search Contractor', true, 1, now(), 1, now());

insert into eg_roleaction(roleCode, actionid, tenantid) values ('SUPERUSER', (select id from eg_action where name = 'Create Contractor' and url='/works-masters/contractors/_create'), 'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Update Contractor' and url='/works-masters/contractors/_update' ), 'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Search Contractor' and url='/works-masters/contractors/_search' ), 'default');
