insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'WMS', 'Works Management', false, 'Works Management', 0, null, 'default');
insert into service (id, code, name, enabled, displayname, ordernumber, parentmodule, tenantId) values (nextval('SEQ_SERVICE'), 'AbstractEstimate', 'Abstract Estimate', false, 'Abstract Estimate', 0, (select id from service where code = 'WMS' and tenantId='default'), 'default');

insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Estimate Create','/works-estimate/abstractestimates/_create','Estimate Create',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Estimate Create',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Estimate Update','/works-estimate/abstractestimates/_update','Estimate Update',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Estimate Update',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Estimate Search','/works-estimate/abstractestimates/_search','Estimate Search',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Estimate Search',false,1,now(),1,now());

insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Estimate Create' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Estimate Update' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Estimate Search' ),'default');
