insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Project Code Create','/works-estimate/projectcodes/_create','Project Code Create',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Project Code Create',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Project Code Update','/works-estimate/projectcodes/_update','Project Code Update',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Project Code Update',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Project Code Search','/works-estimate/projectcodes/_search','Project Code Search',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Project Code Search',false,1,now(),1,now());

insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Project Code Create' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Project Code Update' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Project Code Search' ),'default');

insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Estimate Appropriation Create','/works-services/estimateappropriations/_create','Estimate Appropriation Create',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Estimate Appropriation Create',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Estimate Appropriation Update','/works-services/estimateappropriations/_update','Estimate Appropriation Update',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Estimate Appropriation Update',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Estimate Appropriation Search','/works-services/estimateappropriations/_search','Estimate Appropriation Search',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Estimate Appropriation Search',false,1,now(),1,now());

insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Estimate Appropriation Create' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Estimate Appropriation Update' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Estimate Appropriation Search' ),'default');

insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Document Detail Create','/works-services/documentdetails/_create','Estimate Appropriation Create',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Document Detail Create',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Document Detail Update','/works-services/documentdetails/_update','Estimate Appropriation Update',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Document Detail Update',false,1,now(),1,now());
insert into eg_action(id, name,url,servicecode,queryparams,parentmodule,ordernumber,displayname,enabled,createdby,createddate,lastmodifiedby,lastmodifieddate) values(nextval('SEQ_EG_ACTION'),'Document Detail Search','/works-services/documentdetails/_search','Estimate Appropriation Search',null,(select id from service where code='AbstractEstimate' and tenantid='default'),0,'Document Detail Search',false,1,now(),1,now());

insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Document Detail Create' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Document Detail Update' ),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER',(select id from eg_action where name = 'Document Detail Search' ),'default');