insert into eg_role (id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version)values
(nextval('SEQ_EG_ROLE'),'Citizen','Citizen who can raise complaint',now(),1,1,now(),0);
insert into eg_role (id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version)values
(nextval('SEQ_EG_ROLE'),'Employee','Default role for all employees',now(),1,1,now(),0);
insert into eg_role (id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version)values
(nextval('SEQ_EG_ROLE'),'Super User','System Administrator. Can change all master data and has access to all the system screens.',now(),1,1,now(),0);
insert into eg_role (id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version)values
(nextval('SEQ_EG_ROLE'),'Grievance Officer','Heads the grivance cell. Also all complaints that cannot be routed based on the rules are routed to Grievance Officer.',now(),1,1,now(),0);
insert into eg_role (id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version)values
(nextval('SEQ_EG_ROLE'),'Redressal Officer','Employees that address citizens grievances.',now(),1,1,now(),0);
insert into eg_role (id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version)values
(nextval('SEQ_EG_ROLE'),'Grivance Administrator','System Administator for PGR. Can change PGR Master data only.',now(),1,1,now(),0);
insert into eg_role (id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version)values
(nextval('SEQ_EG_ROLE'),'Grievance Routing Officer','Grievance Routing Officer',now(),1,1,now(),0);


insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get all ReceivingMode'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get all CompaintTypeCategory'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get ComplaintType by type,count and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get all ReceivingCenters'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get location by LocationName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get ComplaintType by type and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get all Statuses'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get next statuses by CurrentStatus and Role'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get Workflow History'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get ChildBoundary by BoundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get Department by code and id'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get File by FileStoreId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get Department by DepartmentId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Get Assignments by DepartmentId Or DesignationId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Seva'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Search Boundary by boundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='Complaint Registration'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='SearchComplaintFormOfficial'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Citizen'),(select id from eg_action where name='UpdateComplaintForm'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get all ReceivingMode'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get all CompaintTypeCategory'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get ComplaintType by type,count and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get all ReceivingCenters'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get location by LocationName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get ComplaintType by type and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get all Statuses'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get next statuses by CurrentStatus and Role'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get Workflow History'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get ChildBoundary by BoundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get Department by code and id'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get File by FileStoreId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get Department by DepartmentId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Get Assignments by DepartmentId Or DesignationId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Seva'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Search Boundary by boundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='Complaint Registration'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='SearchComplaintFormOfficial'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Employee'),(select id from eg_action where name='UpdateComplaintForm'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get all ReceivingMode'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get all CompaintTypeCategory'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get ComplaintType by type,count and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get all ReceivingCenters'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get location by LocationName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get ComplaintType by type and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get all Statuses'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get next statuses by CurrentStatus and Role'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get Workflow History'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get ChildBoundary by BoundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get Department by code and id'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get File by FileStoreId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get Department by DepartmentId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Get Assignments by DepartmentId Or DesignationId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Seva'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search Boundary by boundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='Complaint Registration'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='SearchComplaintFormOfficial'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Super User'),(select id from eg_action where name='UpdateComplaintForm'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get all ReceivingMode'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get all CompaintTypeCategory'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get ComplaintType by type,count and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get all ReceivingCenters'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get location by LocationName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get ComplaintType by type and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get all Statuses'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get next statuses by CurrentStatus and Role'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get Workflow History'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get ChildBoundary by BoundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get Department by code and id'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get File by FileStoreId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get Department by DepartmentId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Get Assignments by DepartmentId Or DesignationId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Seva'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Search Boundary by boundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='Complaint Registration'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='SearchComplaintFormOfficial'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Officer'),(select id from eg_action where name='UpdateComplaintForm'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get all ReceivingMode'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get all CompaintTypeCategory'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get ComplaintType by type,count and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get all ReceivingCenters'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get location by LocationName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get ComplaintType by type and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get all Statuses'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get next statuses by CurrentStatus and Role'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get Workflow History'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get ChildBoundary by BoundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get Department by code and id'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get File by FileStoreId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get Department by DepartmentId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Get Assignments by DepartmentId Or DesignationId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Seva'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Search Boundary by boundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='Complaint Registration'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='SearchComplaintFormOfficial'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Redressal Officer'),(select id from eg_action where name='UpdateComplaintForm'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get all ReceivingMode'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get all CompaintTypeCategory'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get ComplaintType by type,count and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get all ReceivingCenters'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get location by LocationName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get ComplaintType by type and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get all Statuses'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get next statuses by CurrentStatus and Role'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get Workflow History'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get ChildBoundary by BoundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get Department by code and id'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get File by FileStoreId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get Department by DepartmentId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Get Assignments by DepartmentId Or DesignationId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Seva'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Search Boundary by boundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='Complaint Registration'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='SearchComplaintFormOfficial'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grivance Administrator'),(select id from eg_action where name='UpdateComplaintForm'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get all ReceivingMode'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get all CompaintTypeCategory'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get ComplaintType by type,count and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get all ReceivingCenters'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get location by LocationName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get ComplaintType by type and tenantId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get all Statuses'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get next statuses by CurrentStatus and Role'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get Workflow History'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get ChildBoundary by BoundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get Department by code and id'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get File by FileStoreId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get Department by DepartmentId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Get Assignments by DepartmentId Or DesignationId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Seva'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Search Boundary by boundaryId'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='Complaint Registration'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='SearchComplaintFormOfficial'),'ap.public');
insert into eg_roleaction(roleid,actionid,tenantId)values((select id from eg_role where name='Grievance Routing Officer'),(select id from eg_action where name='UpdateComplaintForm'),'ap.public');

