insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'SearchAppconfig', '/pt-property/property/appconfiguration/_search', 'PTIS_MASTERS', null, 25, 'Search Appconfig', true, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'CreateAppconfig', '/pt-property/property/appconfiguration/_create', 'PTIS_MASTERS', null, 26, 'Create Appconfig', true, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'UpdateAppconfig', '/pt-property/property/appconfiguration/_update', 'PTIS_MASTERS', null, 27, 'Update Appconfig', true, 1, now(), 1, now());

insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'SearchGuidanceBoundary', '/pt-property/property/guidancevalueboundary/_search', 'PTIS_MASTERS', null, 28, 'Search Guidance Boundary', true, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'CreateGuidanceBoundary', '/pt-property/property/guidancevalueboundary/_create', 'PTIS_MASTERS', null, 29, 'Create Guidance Boundary', true, 1, now(), 1, now());
insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'UpdateGuidanceBoundary', '/pt-property/property/guidancevalueboundary/_update', 'PTIS_MASTERS', null, 30, 'Update Guidance Boundary', true, 1, now(), 1, now());



insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='SearchAppconfig' and url='/pt-property/property/appconfiguration/_search'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='CreateAppconfig' and url='/pt-property/property/appconfiguration/_create'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='UpdateAppconfig' and url='/pt-property/property/appconfiguration/_update'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');

insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='SearchGuidanceBoundary' and url='/pt-property/property/guidancevalueboundary/_search'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='CreateGuidanceBoundary' and url='/pt-property/property/guidancevalueboundary/_create'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='UpdateGuidanceBoundary' and url='/pt-property/property/guidancevalueboundary/_update'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');

