insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Demand Register', '/property/report/demandRegister/_get', 'PTIS_REPORTS', null, 2, 'Demand Register', false, 1, now(), 1, now());

insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Collection Register', '/property/report/collectionRegister/_get', 'PTIS_REPORTS', null, 2, 'Outstanding Register', false, 1, now(), 1, now());

insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Balance Register', '/property/report/outstandingRegister/_get', 'PTIS_REPORTS', null, 2, 'Balance Register', false, 1, now(), 1, now());

insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Demand Balance CollectionReport', '/property/report/demandBalanceCollectionReport/_get', 'PTIS_REPORTS', null, 2, 'Demand Balance Collection Report', false, 1, now(), 1, now());

insert into eg_action(id,  name, url, servicecode, queryparams, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate) values(nextval('SEQ_EG_ACTION'), 'Assessment Register', '/property/report/assessmentRegister/_get', 'PTIS_REPORTS', null, 2, 'Assessment Register', false, 1, now(), 1, now());

insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='Demand Register' and url='/property/report/demandRegister/_get'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='Collection Register' and url='/property/report/collectionRegister/_get'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='Balance Register' and url='/property/report/outstandingRegister/_get'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='Demand Balance CollectionReport' and url='/property/report/demandBalanceCollectionReport/_get'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
insert into eg_roleaction(roleCode, actionid, tenantId) select code, (select id from eg_action where name='Assessment Register' and url='/property/report/assessmentRegister/_get'), 'default' from eg_ms_role where code in ('SUPERUSER', 'ULB Operator', 'Property Verifier', 'Property Approver');
