--service
insert into service (id,code,name,enabled,contextroot,displayname,ordernumber,parentmodule,tenantId) VALUES (NEXTVAL('SEQ_SERVICE'),'LOCATION_MS','Location',false,'egov-location', 'Location', 1, null, 'default');
--Actions
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Boundary by Boundary Type','/boundarys/getByBoundaryType','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Boundary by Boundary Type',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Child locations by Boundary','/boundarys/childLocationsByBoundaryId','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Child locations by Boundary',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Location by Location Name','/boundarys/getLocationByLocationName','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Location by Location Name',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Boundaries by Code','/boundarys/{code}','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Boundaries by Code',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Boundary Type','/boundarytypes','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Boundary Type',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get BoundaryTypes By Heirarchy Type','/boundarytypes/getByHierarchyType','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get BoundaryTypes By Heirarchy Type',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get City','/city','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get City',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get City By City Request','/city/getCitybyCityRequest','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get City By City Request',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Heirarchy Type','/hierarchytypes','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Heirarchy Type',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Heirarchy Type By Code','/hierarchytypes/{code}','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Heirarchy Type By Code',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Cross Hierarchys','/crosshierarchys','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Cross Hierarchys',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Cross Hierarchy By Code','/crosshierarchys/{code}','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Cross Hierarchy By Code',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Create Boundary Type','/boundarytype/create','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Create Boundary Type',false,1,now(),1,now(),'default');
insert into eg_action(id, name, url, servicecode, queryparams, parentmodule, ordernumber, displayname, enabled, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantId) values (nextval('SEQ_EG_ACTION'), 'Get Boundaries by boundarytype and hierarchy Type','/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName','LOCATION_MS', NULL,(select id from service where code='LOCATION_MS' and tenantid='default'), 1,'Get Boundaries by boundarytype and hierarchy Type','false',1,now(),1,now(),'default');

--super user role mapping
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Boundary by Boundary Type' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Child locations by Boundary' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Location by Location Name' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Boundaries by Code' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Boundary Type' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get BoundaryTypes By Heirarchy Type' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get City' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get City By City Request' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Heirarchy Type' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Heirarchy Type By Code' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Cross Hierarchys' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Cross Hierarchy By Code' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Create Boundary Type' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('SUPERUSER', (select id from eg_action where name = 'Get Boundaries by boundarytype and hierarchy Type' and tenantid='default'),'default');

--mapping to other roles
insert into eg_roleaction(roleCode,actionid,tenantid)values('ULB Operator', (select id from eg_action where name = 'Get Boundaries by boundarytype and hierarchy Type' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('Property Verifier', (select id from eg_action where name = 'Get Boundaries by boundarytype and hierarchy Type' and tenantid='default'),'default');

insert into eg_roleaction(roleCode,actionid,tenantid)values('EMPLOYEE ADMIN', (select id from eg_action where name = 'Get BoundaryTypes By Heirarchy Type' and tenantid='default'),'default');
insert into eg_roleaction(roleCode,actionid,tenantid)values('EMPLOYEE ADMIN', (select id from eg_action where name = 'Get Boundary by Boundary Type' and tenantid='default'),'default');
