/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorRes;
import io.swagger.model.RequestInfo;
import io.swagger.model.ScrapRequest;
import io.swagger.model.ScrapResponse;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;

import java.util.List;
import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-10-28T13:21:55.964+05:30")

@Api(value = "scraps", description = "the scraps API")
public interface ScrapsApi {

    @ApiOperation(value = "Create  new  scraps", nickname = "scrapsCreatePost", notes = "Create  new scraps", response = ScrapResponse.class, tags={ "Inventory","Scrap", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Scrap created Successfully", response = ScrapResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/scraps/_create",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ScrapResponse> scrapsCreatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Create  new"  )  @Valid @RequestBody ScrapRequest scrapRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Get the list of scraps", nickname = "scrapsSearchPost", notes = "scraps", response = ScrapResponse.class, tags={ "Inventory","Scrap", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Scrap retrieved Successfully", response = ScrapResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/scraps/_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ScrapResponse> scrapsSearchPost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Parameter to carry Request metadata in the request body"  )  @Valid @RequestBody RequestInfo requestInfo, @Size(max=50)@ApiParam(value = "comma seperated list of Ids") @Valid @RequestParam(value = "ids", required = false) List<String> ids,@ApiParam(value = "store of the Scrap ") @Valid @RequestParam(value = "store", required = false) Long store,@ApiParam(value = "scrapNumber  Auto generated number, read only ") @Valid @RequestParam(value = "scrapNumber", required = false) String scrapNumber,@ApiParam(value = "scrap date of the Scrap ") @Valid @RequestParam(value = "scrapDate", required = false) Long scrapDate,@ApiParam(value = "description of the Scrap ") @Valid @RequestParam(value = "description", required = false) String description,@ApiParam(value = "scrap status of the Scrap ", allowableValues = "CREATED, APPROVED, REJECTED, CANCELED") @Valid @RequestParam(value = "scrapStatus", required = false) String scrapStatus,@ApiParam(value = "state id of the Scrap ") @Valid @RequestParam(value = "stateId", required = false) Long stateId,@ApiParam(value = "pageSize") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "offset") @Valid @RequestParam(value = "offset", required = false) Integer offset,@ApiParam(value = "This takes any field from the Object seperated by comma and asc,desc keywords.   example name asc,code desc or name,code or name,code desc  ") @Valid @RequestParam(value = "sortBy", required = false) String sortBy, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Update any of the scraps", nickname = "scrapsUpdatePost", notes = "Update any of the scraps", response = ScrapResponse.class, tags={ "Inventory","Scrap", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Scrap updated Successfully", response = ScrapResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/scraps/_update",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ScrapResponse> scrapsUpdatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "common Request info"  )  @Valid @RequestBody ScrapRequest scrapRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
