var dat = {
  'swm.search' : {
     numCols: 4,
      useTimestamp: true,
      objectName: 'vehiclestripsheet',
      url: '/egov-mdms-service/v1/_search',
      groups: [
        {
          name:'vehicleTripEntrySearch',
          label: 'swm.vehiclestripsheet.search.vehicleTripEntrySearch',
          fields: [
            {
              name: ' tripStartdate',
              jsonPath: 'vehiclestripsheet.tripStartdate',
              label: 'swm.vehiclestripsheet.search.tripStartDate',
              pattern: '',
              type: 'datePicker',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              url: '/egov-mdms-service/v1/_get?&moduleName=swm&masterName=ShiftType|$..ShiftType.*.code|$..ShiftType.*.name',
            },
            {
              name: 'tripEndDate',
              jsonPath: 'vehiclestripsheet.tripEndDate',
              label: 'swm.vehiclestripsheet.search.tripEndDate',
              pattern: '',
              type: 'datePicker',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              patternErrorMsg: '',
              url: '/hr-masters/designations/_search?tenantId=default|$..id|$..name',
            },
            {
              name: 'regNumber',
              jsonPath: 'vehiclestripsheet.regNumber',
              label: 'swm.vehiclestripsheet.create.regNumber',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              patternErrorMsg: '',
              url: '/hr-masters/designations/_search?tenantId=default|$..id|$..name',
            },
            {
              name: 'routeName',
              jsonPath: 'vehiclestripsheet.routeName',
              label: 'swm.vehiclestripsheet.search.routeName',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              patternErrorMsg: '',
              url: '/hr-masters/designations/_search?tenantId=default|$..id|$..name',
            },
          ]
        },
      ],
      result: {
        header: [
          {
            label: 'swm.vehiclestripsheet.create.regNumber',
          },
          {
            label: 'swm.vehiclestripsheet.search.routeName',
          },
          {
            label: 'swm.vehiclestripsheet.search.tripStartDate',
            isDate: true
          },
          {
            label: 'swm.vehiclestripsheet.search.tripEndDate',
            isDate: true
          },
        ],
        values: [
          // 'shiftType.name',
          // 'designation.name',
          // 'shiftStartTime',
          // 'shiftEndTime',
        ],
        resultPath: 'MdmsRes.swm.Shift',
        rowClickUrlUpdate: '/update/swm/shiftmasters/{code}',
        rowClickUrlView: '/view/swm/shiftmasters/{code}',
        isMasterScreen: true
      },
    },
  'swm.create': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'vehiclestripsheet',
    title: 'swm.vehiclestripsheet.create.title',
    groups: [
      {
        name: 'VehicleDetails',
        label: '',
        fields: [
          {
            name: 'regNumber',
            jsonPath: 'vehiclestripsheet[0].regNumber',
            label: 'swm.vehiclestripsheet.create.regNumber',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'ulbOwnedVehicle',
            jsonPath: 'vehiclestripsheet[0].ulbOwnedVehicle',
            label: 'swm.vehiclestripsheet.create.ulbOwnedVehicle',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'vendorName',
            jsonPath: 'vehiclestripsheet[0].vendorName',
            label: 'swm.vehiclestripsheet.create.vendorName',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'route',
            jsonPath: 'vehiclestripsheet[0].route',
            label: 'swm.vehiclestripsheet.create.route',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url:'',
          },
          {
            name: 'scheduledDateFrom',
            jsonPath: 'vehiclestripsheet[0].scheduledDateFrom',
            label: 'swm.vehiclestripsheet.create.scheduledDateFrom',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'scheduledDateTo',
            jsonPath: 'vehiclestripsheet[0].scheduledDateTo',
            label: 'swm.vehiclestripsheet.create.scheduledDateTo',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'dumpingGroundName',
            jsonPath: 'vehiclestripsheet[0].dumpingGroundName',
            label: 'swm.vehiclestripsheet.create.dumpingGroundName',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
        ],
      },
      {
        name: 'locationsCovered',
        label: 'swm.vehiclestripsheet.create.group.title.locationsCovered',
        fields: [
        {
          type: 'tableList',
          actionsNotRequired: true,
          jsonPath: 'vehiclestripsheet[0].locationdetails',
          tableList: {
          actionsNotRequired: true,
          serialNoNotRequired:true,
            header: [
              {
                label: 'swm.processingplant.create.title.Ward',
              },
              {
                label: 'swm.processingplant.create.Zone',
              },
              {
                label: 'swm.processingplant.create.block',
              },
              {
                label: 'swm.processingplant.create.Colony',
              },
              {
                label: 'swm.processingplant.create.routestop',
              },
            ],
            values: [
              {
                name: 'advocateName',
                isKeyOtherPair: 'agencyName',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocate.code',
                isRequired: true,
                isDisabled: false,
                url: '/lcms-services/legalcase/advocate/_search?&status=active|$..code|$..name',
              },
              {
                name: 'advocateAssignDate',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].assignedDate',
                isRequired: true,
                isDisabled: false,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
            ],
          },
        },
        ],
      },
      {
        name: 'tripSheetDetails',
        label: 'swm.vehiclestripsheet.create.group.title.tripSheetDetails',
        fields: [
          {
            name: 'inTime',
            jsonPath: 'vehiclestripsheet[0].inTime',
            label: 'swm.vehiclestripsheet.create.inTime',
            type: 'timePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'outTime',
            jsonPath: 'vehiclestripsheet[0].outTime',
            label: 'swm.vehiclestripsheet.create.outTime',
            type: 'timePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'collectionType',
            jsonPath: 'vehiclestripsheet[0].collectionType',
            label: 'swm.vehiclestripsheet.create.collectionType',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'totalDistanceCovered',
            jsonPath: 'vehiclestripsheet[0].totalDistanceCovered',
            label: 'swm.vehiclestripsheet.create.totalDistanceCovered',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'entryWeight',
            jsonPath: 'vehiclestripsheet[0].entryWeight',
            label: 'swm.vehiclestripsheet.create.entryWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
           {
            name: 'exitWeight',
            jsonPath: 'vehiclestripsheet[0].exitWeight',
            label: 'swm.vehiclestripsheet.create.exitWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
           {
            name: 'garbageWeight',
            jsonPath: 'vehiclestripsheet[0].garbageWeight',
            label: 'swm.vehiclestripsheet.create.garbageWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },

        ],
      },
    ],
    url: '/swm-services/vehicles/_create',
    tenantIdRequired: true,
  },
  'swm.update': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'vehiclestripsheet',
    title: 'swm.vehiclestripsheet.create.title',
    groups: [
      {
        name: 'VehicleDetails',
        label: '',
        fields: [
          {
            name: 'regNumber',
            jsonPath: 'vehiclestripsheet[0].regNumber',
            label: 'swm.vehiclestripsheet.create.regNumber',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'ulbOwnedVehicle',
            jsonPath: 'vehiclestripsheet[0].ulbOwnedVehicle',
            label: 'swm.vehiclestripsheet.create.ulbOwnedVehicle',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'vendorName',
            jsonPath: 'vehiclestripsheet[0].vendorName',
            label: 'swm.vehiclestripsheet.create.vendorName',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'route',
            jsonPath: 'vehiclestripsheet[0].route',
            label: 'swm.vehiclestripsheet.create.route',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url:'',
          },
          {
            name: 'scheduledDateFrom',
            jsonPath: 'vehiclestripsheet[0].scheduledDateFrom',
            label: 'swm.vehiclestripsheet.create.scheduledDateFrom',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'scheduledDateTo',
            jsonPath: 'vehiclestripsheet[0].scheduledDateTo',
            label: 'swm.vehiclestripsheet.create.scheduledDateTo',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'dumpingGroundName',
            jsonPath: 'vehiclestripsheet[0].dumpingGroundName',
            label: 'swm.vehiclestripsheet.create.dumpingGroundName',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
        ],
      },
      {
        name: 'locationsCovered',
        label: 'swm.vehiclestripsheet.create.group.title.locationsCovered',
        fields: [
        {
          type: 'tableList',
          actionsNotRequired: true,
          jsonPath: 'vehiclestripsheet[0].locationdetails',
          tableList: {
          actionsNotRequired: true,
          serialNoNotRequired:true,
            header: [
              {
                label: 'swm.processingplant.create.title.Ward',
              },
              {
                label: 'swm.processingplant.create.Zone',
              },
              {
                label: 'swm.processingplant.create.block',
              },
              {
                label: 'swm.processingplant.create.Colony',
              },
              {
                label: 'swm.processingplant.create.routestop',
              },
            ],
            values: [
              {
                name: 'advocateName',
                isKeyOtherPair: 'agencyName',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocate.code',
                isRequired: true,
                isDisabled: false,
                url: '/lcms-services/legalcase/advocate/_search?&status=active|$..code|$..name',
              },
              {
                name: 'advocateAssignDate',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].assignedDate',
                isRequired: true,
                isDisabled: false,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
            ],
          },
        },
        ],
      },
      {
        name: 'tripSheetDetails',
        label: 'swm.vehiclestripsheet.create.group.title.tripSheetDetails',
        fields: [
          {
            name: 'inTime',
            jsonPath: 'vehiclestripsheet[0].inTime',
            label: 'swm.vehiclestripsheet.create.inTime',
            type: 'timePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'outTime',
            jsonPath: 'vehiclestripsheet[0].outTime',
            label: 'swm.vehiclestripsheet.create.outTime',
            type: 'timePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'collectionType',
            jsonPath: 'vehiclestripsheet[0].collectionType',
            label: 'swm.vehiclestripsheet.create.collectionType',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'totalDistanceCovered',
            jsonPath: 'vehiclestripsheet[0].totalDistanceCovered',
            label: 'swm.vehiclestripsheet.create.totalDistanceCovered',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'entryWeight',
            jsonPath: 'vehiclestripsheet[0].entryWeight',
            label: 'swm.vehiclestripsheet.create.entryWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
           {
            name: 'exitWeight',
            jsonPath: 'vehiclestripsheet[0].exitWeight',
            label: 'swm.vehiclestripsheet.create.exitWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
           {
            name: 'garbageWeight',
            jsonPath: 'vehiclestripsheet[0].garbageWeight',
            label: 'swm.vehiclestripsheet.create.garbageWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },

        ],
      },
    ],
    url: '/swm-services/vehicles/_update',
    tenantIdRequired: true,
  },
 'swm.view': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'vehiclestripsheet',
    title: 'swm.vehiclestripsheet.create.title',
    groups: [
      {
        name: 'VehicleDetails',
        label: '',
        fields: [
          {
            name: 'regNumber',
            jsonPath: 'vehiclestripsheet[0].regNumber',
            label: 'swm.vehiclestripsheet.create.regNumber',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'ulbOwnedVehicle',
            jsonPath: 'vehiclestripsheet[0].ulbOwnedVehicle',
            label: 'swm.vehiclestripsheet.create.ulbOwnedVehicle',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'vendorName',
            jsonPath: 'vehiclestripsheet[0].vendorName',
            label: 'swm.vehiclestripsheet.create.vendorName',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'route',
            jsonPath: 'vehiclestripsheet[0].route',
            label: 'swm.vehiclestripsheet.create.route',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url:'',
          },
          {
            name: 'scheduledDateFrom',
            jsonPath: 'vehiclestripsheet[0].scheduledDateFrom',
            label: 'swm.vehiclestripsheet.create.scheduledDateFrom',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'scheduledDateTo',
            jsonPath: 'vehiclestripsheet[0].scheduledDateTo',
            label: 'swm.vehiclestripsheet.create.scheduledDateTo',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          {
            name: 'dumpingGroundName',
            jsonPath: 'vehiclestripsheet[0].dumpingGroundName',
            label: 'swm.vehiclestripsheet.create.dumpingGroundName',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
        ],
      },
      {
        name: 'locationsCovered',
        label: 'swm.vehiclestripsheet.create.group.title.locationsCovered',
        fields: [
        {
          type: 'tableList',
          actionsNotRequired: true,
          jsonPath: 'vehiclestripsheet[0].locationdetails',
          tableList: {
          actionsNotRequired: true,
          serialNoNotRequired:true,
            header: [
              {
                label: 'swm.processingplant.create.title.Ward',
              },
              {
                label: 'swm.processingplant.create.Zone',
              },
              {
                label: 'swm.processingplant.create.block',
              },
              {
                label: 'swm.processingplant.create.Colony',
              },
              {
                label: 'swm.processingplant.create.routestop',
              },
            ],
            values: [
              {
                name: 'advocateName',
                isKeyOtherPair: 'agencyName',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocate.code',
                isRequired: true,
                isDisabled: false,
                url: '/lcms-services/legalcase/advocate/_search?&status=active|$..code|$..name',
              },
              {
                name: 'advocateAssignDate',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].assignedDate',
                isRequired: true,
                isDisabled: false,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
              {
                name: 'advocatestaus',
                pattern: '',
                type: 'label',
                jsonPath: 'cases[0].advocateDetails[0].advocatestaus',
                isRequired: false,
                isDisabled: true,
              },
            ],
          },
        },
        ],
      },
      {
        name: 'tripSheetDetails',
        label: 'swm.vehiclestripsheet.create.group.title.tripSheetDetails',
        fields: [
          {
            name: 'inTime',
            jsonPath: 'vehiclestripsheet[0].inTime',
            label: 'swm.vehiclestripsheet.create.inTime',
            type: 'timePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'outTime',
            jsonPath: 'vehiclestripsheet[0].outTime',
            label: 'swm.vehiclestripsheet.create.outTime',
            type: 'timePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'collectionType',
            jsonPath: 'vehiclestripsheet[0].collectionType',
            label: 'swm.vehiclestripsheet.create.collectionType',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'totalDistanceCovered',
            jsonPath: 'vehiclestripsheet[0].totalDistanceCovered',
            label: 'swm.vehiclestripsheet.create.totalDistanceCovered',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
          {
            name: 'entryWeight',
            jsonPath: 'vehiclestripsheet[0].entryWeight',
            label: 'swm.vehiclestripsheet.create.entryWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
           {
            name: 'exitWeight',
            jsonPath: 'vehiclestripsheet[0].exitWeight',
            label: 'swm.vehiclestripsheet.create.exitWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },
           {
            name: 'garbageWeight',
            jsonPath: 'vehiclestripsheet[0].garbageWeight',
            label: 'swm.vehiclestripsheet.create.garbageWeight',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            defaultValue: '',
          },

        ],
      },
    ],
    url: '/swm-services/vehicles/_view',
    tenantIdRequired: true,
  },

};
export default dat;