insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get location by LocationName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get all Statuses' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get next statuses by CurrentStatus and Role' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get Workflow History' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get ChildBoundary by BoundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get File by FileStoreId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Search Boundary by boundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Complaint Registration' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='SearchComplaintFormOfficial' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='UpdateComplaintForm' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get location by LocationName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get all Statuses' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get next statuses by CurrentStatus and Role' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get Workflow History' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get ChildBoundary by BoundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get File by FileStoreId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Search Boundary by boundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Complaint Registration' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='SearchComplaintFormOfficial' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='UpdateComplaintForm' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get location by LocationName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get all Statuses' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get next statuses by CurrentStatus and Role' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get Workflow History' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get ChildBoundary by BoundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get File by FileStoreId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Search Boundary by boundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Complaint Registration' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='SearchComplaintFormOfficial' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='UpdateComplaintForm' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get location by LocationName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get all Statuses' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get next statuses by CurrentStatus and Role' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get Workflow History' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get ChildBoundary by BoundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get File by FileStoreId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Search Boundary by boundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Complaint Registration' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='SearchComplaintFormOfficial' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='UpdateComplaintForm' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get location by LocationName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Search Boundary by BoundryTypeName and HierarchyTypeName' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get all Statuses' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get next statuses by CurrentStatus and Role' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get Workflow History' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get ChildBoundary by BoundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get File by FileStoreId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Search Boundary by boundaryId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Complaint Registration' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='SearchComplaintFormOfficial' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='UpdateComplaintForm' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='View ESS Employee' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='ESS Leave Application' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Create Leave Applications' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Leave Application Update' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Search Leave Application' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Search Eligible Leaves' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='HOD Employees' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Create Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Create Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Create Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Create Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Create Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Update Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Update Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Update Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Update Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Update Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Search Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Search Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Search Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Search Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Search Complaint' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Search Leave Type' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='LoggedInEmployeeDetails' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get all ReceivingMode' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get all ReceivingCenters' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get all ReceivingMode' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get all ReceivingCenters' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get all ReceivingMode' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get all ReceivingCenters' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get all ReceivingMode' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get all ReceivingCenters' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get all ReceivingMode' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get all ReceivingCenters' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='SearchEmployee' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='processsearch' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get all CompaintTypeCategory' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get all CompaintTypeCategory' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get all CompaintTypeCategory' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get all CompaintTypeCategory' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get all CompaintTypeCategory' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get ComplaintType by type,count and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get ComplaintType by type,count and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get ComplaintType by type,count and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get ComplaintType by type,count and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get ComplaintType by type,count and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get ComplaintType by type and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get ComplaintType by type and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get ComplaintType by type and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get ComplaintType by type and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get ComplaintType by type and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get ComplaintType by type,categoryId and tenantId' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GO',(select id from eg_action where name='Get all service type categories' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('RO',(select id from eg_action where name='Get all service type categories' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GA',(select id from eg_action where name='Get all service type categories' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('EMPLOYEE',(select id from eg_action where name='Get all service type categories' and tenantId='panavel'),'panavel');
insert into eg_roleaction(roleCode,actionid,tenantId)values('GRO',(select id from eg_action where name='Get all service type categories' and tenantId='panavel'),'panavel');
