swagger: '2.0'
# eGSP YAML Template Version: 1.0 
# This is a version number for the YAML template. This must not be changed.

info:
  version: 1.0.0
  title: Performance Management APIs
  description: |
    APIs available for Performance Management
      - Create and Define KPIs
      - Search and View KPI defined
      - Set Target for KPIs for the Tenants / ULBs
      - Enter Actual Values for the KPIs 
      - Search KPI Values based on different parameters
      - Search and Compare KPI Values for different ULBs / Fin Years/ KPIs
  contact:
    name: Darshan Nagesh
host: phoenix-qa.egovernments.org
schemes:
  - https
basePath: '/perfmanagement/v1'

paths:
  /kpi/_create:
    post:
      summary: Creates a KPI Record with KPI Detailing
      description: KPI which is applicable for all the ULBs are created with a description to it. This provides a detail on KPI and its base attributes
      tags:
        - KPI 
      parameters:
        - name: KPI
          in: body
          description: required parameters have to be populated
          required: true
          schema:
            $ref: '#/definitions/KPIRequest'
      responses:
        '201':
          description: Acknowledgment on successful creation of new KPI
          schema:
            $ref: "#/definitions/KPIResponse"
        '400':
          description: Creating a new KPI Request has failed
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'

  /kpi/_update:
      post:
        summary: API to update the values of the KPI Master
        description: Updates the existing values of the KPI Master (Code cannot be updated)
        tags:
          - KPI Master
        parameters:
          - name: KPI
            in: body
            description: required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIRequest'
        responses:
          '200':
            description: KPI Master Record has been updated successfully 
            schema:
              $ref: "#/definitions/KPIResponse"
          '400':
            description: Request failed
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
  
  /kpi/_search:
    post:
      summary: Fetch the KPI Master Record
      description: Search the KPI Record based on the different parameters such as code, name
      tags:
        - KPI Master
      parameters:
        - $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/requestInfo"
        - $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId"
        - $ref: "#/parameters/name"
        - $ref: "#/parameters/code"
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
        - $ref: "#/parameters/sortResult"
      responses:
        200: 
          description: Successful response
          schema:
            $ref: "#/definitions/DepartmentKpiResponse"
        400:
          description: Invalid input
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
            
    # KPI and Actual Value Setting APIs
  /kpivalue/_create: 
      post:
        summary: This API is used to enter the values (Actuals) for the KPI at ULB Level
        tags:
          - KPI Value
        parameters:
          - name: KPIValue
            in: body
            description: Required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIValueRequest'
        responses:
          200: 
            description: Successful response
            schema:
              $ref: '#/definitions/KPIValueResponse'
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  /kpivalue/_update: 
      post:
        summary: This API is used to update the already existing values (Actuals) for the KPI at ULB Level
        tags:
          - KPI Value
        parameters:
          - name: KPIValue
            in: body
            description: Required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIValueRequest'
        responses:
          200: 
            description: Successful response
            schema:
              $ref: '#/definitions/KPIValueResponse'
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  /kpivalue/_search: 
      post:
        summary: Fetch the target value defined for the KPI
        description: Search the KPI Target Values defined for the KPI Record 
        tags:
          - KPI Value
        parameters:
        - $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/requestInfo"
        - name: tenantId
          in: query
          description: Unique id for a tenant.
          type: array
          items: 
            type: string
          format: "state.ulb"
        - name: code
          in: query
          description: KPI codes
          type: array
          items: 
            type: string
        - name: fromDate
          in: query
          description: search the KPIs from the financial year start date as per this date
          type: integer
          format: int64
        - name: toDate
          in: query
          description: search the KPIs from the financial year end date as per this date
          type: integer
          format: int64
        responses:
          200: 
            description: Successful response
            schema:
              $ref: "#/definitions/KPIValueResponse"
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  /kpivalue/_comparesearch: 
      post:
        summary: Fetch the target values for different parameters which will be used to paint the dashboard
        description: Search the KPI Target Values defined for the KPI Record 
        tags:
          - KPI Value
        parameters:
        - $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/requestInfo"
        - name: tenantId
          in: query
          description: Unique id for a tenant.
          type: array
          items: 
            type: string
          format: "state.ulb"
        - name: code
          in: query
          description: KPI codes
          type: array
          items: 
            type: string
        - name: fromDate
          in: query
          description: search the KPIs from the financial year start date as per this date
          type: integer
          format: int64
        - name: toDate
          in: query
          description: search the KPIs from the financial year end date as per this date
          type: integer
          format: int64
        responses:
          200: 
            description: Successful response
            schema:
              $ref: "#/definitions/KPIValueSearchResponse"
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'

definitions:
  
  KPI:
    type: object
    description: This is the object for KPI Details not specific to any ULB
    properties:
      tenantId:
        type: string
        description: Unique teanntid for the ULB - if the KPI is defined at state level use only state part of the namespaced tenantid
      department:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-common-masters/contracts/v1-0-0.yml#/definitions/Department'
      id:
        type: string
        pattern: ^[0-9]+$
        description: unique id of the KPI - will be generated from IDGen service
      name:
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: Name of the KPI
      code:
        type: string
        pattern: ^[a-zA-Z0-9.]+$
        description: Code of the KPI
      remoteSystemId:
        type: string
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Code in remote system if the KPI is from remote
      targetValue: 
        type: number
        format: float
        description: Value for the KPI Target
      instructions: 
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: Instructions on how to achieve the target
      finYear:
        $ref: "#/definitions/FinancialYear"
      documents:
        type: array
        items:
          $ref: "#/definitions/Document"
    required:
      - name
      - id
      - finYear
      
  KpiValue:
    type: object
    description: Object which holds the mapping for KPI and its actual values entered by ULBs
    properties:
      kpi:
        $ref: "#/definitions/KPI"
      resultValue: 
        type: integer
        format: int64
        description: Actual Value at ULB Level for the KPI Target
      tenantId:
        type: string
        pattern: ^[a-zA-Z0-9.]+$
        readOnly: true
        description: Unique Identifier of the tenant
      documents:
        type: array
        items:
          $ref: "#/definitions/Document"
      auditDetails:
        $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/AuditDetails"
    required:
      - kpi
      - resultValue
      - tenantId
      
  KpiValueList:
    type: object
    description: Object which holds the list of KPI Values for each tenant or financial year
    properties:
      tenantId:
        type: string
        readOnly: true
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Identifier of the tenant
      kpi:
        $ref: "#/definitions/KPI"
      finYear:
        type: string
        pattern: ^[a-zA-Z0-9-]+$
        description: Financial Year for which the KPI is applicable
      kpiValue:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KpiValue'
          
  DepartmentKpiList:
    type: object
    description: Object which holds the list of KPI Values against each Department 
    properties:
      department:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-common-masters/contracts/v1-0-0.yml#/definitions/Department'
      kpiList:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KPI'
      
  FinancialYear:
    type: object
    description: Financial year
    properties:
      fromDate:
        type: integer
        format: int64
        x-displayformay: 'dd/mm/YYYY'
        description: timestamp for the start of the fianncial year
      toDate:
        type: integer
        format: int64
        x-displayformay: 'dd/mm/YYYY'
        description: timestamp for the end of the fianncial year
    required:
      - fromDate
      - toDate
      
  Document:
    type: object
    description: documents required under respective KPI 
    properties:
      name: 
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: name of the Document.
        readOnly: true
      code: 
        type: string
        pattern: ^[a-zA-Z0-9.]+$
        description: Unique Code of the Document.
        readOnly: true
      description:
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: description of the Document.
        maxLength: 250
      active:
        type: boolean
        format: varchar
        description: TRUE for active Document Names and FALSE for inactive Document Names.
    required:
      - active
      - code
      - description
     
  KPIRequest:
    type: object
    properties:
      requestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      KPIs:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KPI'
    required:
      - requestInfo
      - KPIs
      
  KPIResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      KPIs:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KPI'
          
  DepartmentKpiResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      KPIs:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/DepartmentKpiList'
      
  KPIValueRequest:
    type: object
    properties:
      requestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      kpiValues:
        type: array
        maximum: 500
        items:
          $ref: "#/definitions/KpiValue"
    required:
      - requestInfo
      - kpiValues
      
  KPIValueResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      kpiValues:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KpiValue'
          
  KPIValueSearchResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      kpiValues:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KpiValueList'
       
parameters:

  name:
    name: kpiName
    in: query
    description: Name of the KPI
    required: false
    type: string

  code:
    name: kpiCode
    in: query
    description: Code of the KPI
    required: false
    type: string
    minLength: 0
    maxLength: 64
    
  pageSize:
    name: pageSize
    in: query
    description: Number of records returned.
    type: integer
    minimum: 0
    exclusiveMinimum: true
    maximum: 100
    exclusiveMaximum: false
    multipleOf: 10
    default: 20

  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
    default: 1

  sortResult:
    name: sort
    in: query
    description: Connections results will be sorted by createdTime ascending by default if this parameter is not provided.
    type: array
    uniqueItems: true
    minItems: 1
    maxItems: 4
    collectionFormat: pipes
    items:
      type: string
      pattern: '[-+](name|mobileNumber|locality|consumerNumber)'
    default:
      - +name
      
