INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'), 'Complaint Cell', true, 8, 0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'), 'Mayor/Chairperson Office', true, 2,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'), 'Zonal Office', true, 7,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'), 'Commissioner Office', true, 6,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'), 'CM Office', true, 1,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'),'Field visits',true,9,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'),'Adverse Items(Paper/news)',true,10,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'),'Public Representatives',true,3,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'),'Office of CDMA',true,4,0, 'default');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (nextval('seq_egpgr_receiving_center'),'Office of RDMA',true,5,0, 'default');