/*
 * Marriage Registration APIs
 * APIs for Marriage registration for citizens are listed here.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swaminathan.s@riflexions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.egov.mr.web.contract;

import java.util.ArrayList;
import java.util.List;

import org.egov.mr.model.Page;
import org.egov.mr.model.ReissueCertAppl;
import org.springframework.stereotype.Component;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Component
@Builder
public class ReissueCertResponse {
	private ResponseInfo responseInfo;

	private List<ReissueCertAppl> reissueApplications = new ArrayList<ReissueCertAppl>();

	private Page page;
}
