var rooms = {
 "name": "Rooms",
 "version": "v1",
 "level": 2,
 "jsonPath": "rooms",
 "groups": [
  {
   "label": "Room",
   "name": "Room",
   "multiple": true,
   "children": [],
   "fields": [
		{
			"name": "FloorNumber",
			"jsonPath": "FloorNumber",
			"label": "pt.create.groups.propertyAddress.fields.floorNumber",
			"pattern": "",
			"type": "singleValueList",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"url":"",
			"patternErrMsg": "",
			"defaultValue":[]
		},
		{
			"name": "UnitType",
			"jsonPath": "UnitType",
			"label": "pt.create.groups.propertyAddress.fields.unitType",
			"pattern": "",
			"type": "singleValueList",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"url":"",
			"patternErrMsg": "",
			"defaultValue":[]
		},
		{
			"name": "UnitNumber",
			"jsonPath": "UnitNumber",
			"label": "pt.create.groups.propertyAddress.fields.unitNumber",
			"pattern": "",
			"type": "number",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		},
		{
			"name": "ConstructionType",
			"jsonPath": "ConstructionType",
			"label": "pt.create.groups.propertyAddress.fields.constructionType",
			"pattern": "",
			"type": "singleValueList",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"url":"",
			"patternErrMsg": "",
			"defaultValue":[]
		},
		{
			"name": "UsageType",
			"jsonPath": "UsageType",
			"label": "pt.create.groups.propertyAddress.fields.usageType",
			"pattern": "",
			"type": "singleValueList",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"url":"",
			"patternErrMsg": "",
			"defaultValue":[]
		},
		{
			"name": "UsageSubType",
			"jsonPath": "UsageSubType",
			"label": "pt.create.groups.propertyAddress.fields.usageSubType",
			"pattern": "",
			"type": "singleValueList",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"url":"",
			"patternErrMsg": "",
			"defaultValue":[]
		},
		{
			"name": "FirmName",
			"jsonPath": "FirmName",
			"label": "pt.create.groups.propertyAddress.fields.firmName",
			"pattern": "",
			"type": "text",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": "",
		},
		{
			"name": "Occupancy",
			"jsonPath": "Occupancy",
			"label": "pt.create.groups.propertyAddress.fields.occupancy",
			"pattern": "",
			"type": "singleValueList",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"url":"",
			"patternErrMsg": "",
			"defaultValue":[]
		},
		{
			"name": "OccupantName",
			"jsonPath": "OccupantName",
			"label": "pt.create.groups.propertyAddress.fields.occupantName",
			"pattern": "",
			"type": "text",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": "",
		},
		{
			"name": "AnnualRent",
			"jsonPath": "AnnualRent",
			"label": "pt.create.groups.propertyAddress.fields.AnnualRent",
			"pattern": "",
			"type": "text",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": "",
		},
		{
			"name": "ManualArv",
			"jsonPath": "ManualArv",
			"label": "pt.create.groups.propertyAddress.fields.manualArv",
			"pattern": "",
			"type": "text",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": "",
		},
		{
			"name": "ConstructionDate",
			"jsonPath": "ConstructionDate",
			"label": "pt.create.groups.propertyAddress.fields.constructionDate",
			"pattern": "",
			"type": "datePicker",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": "",
		},
		{
			"name": "EffectiveFromDate",
			"jsonPath": "EffectiveFromDate",
			"label": "pt.create.groups.propertyAddress.fields.effectiveFromDate",
			"pattern": "",
			"type": "datePicker",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": "",
		},
		{
			"name": "UnstructuredLand",
			"jsonPath": "UnstructuredLand",
			"label": "pt.create.groups.propertyAddress.fields.unstructuredLand",
			"pattern": "",
			"type": "singleValueList",
			"url":"",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": "",
			"defaultValue":[]
		},
		{
			"name": "Length",
			"jsonPath": "Length",
			"label": "pt.create.groups.propertyAddress.fields.length",
			"pattern": "",
			"type": "number",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		},
		{
			"name": "Breadth",
			"jsonPath": "Breadth",
			"label": "pt.create.groups.propertyAddress.fields.breadth",
			"pattern": "",
			"type": "number",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		},
		{
			"name": "PlinthArea",
			"jsonPath": "PlinthArea",
			"label": "pt.create.groups.propertyAddress.fields.plinthArea",
			"pattern": "",
			"type": "number",
			"isRequired": true,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		},
		{
			"name": "OccupancyCertificateNumber",
			"jsonPath": "OccupancyCertificateNumber",
			"label": "pt.create.groups.propertyAddress.fields.occupancyCertificateNumber",
			"pattern": "",
			"type": "number",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		},
		{
			"name": "BuildingPermissionNumber",
			"jsonPath": "BuildingPermissionNumber",
			"label": "pt.create.groups.propertyAddress.fields.buildingPermissionNumber",
			"pattern": "",
			"type": "number",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		},
		{
			"name": "BuildingPermissionDate",
			"jsonPath": "BuildingPermissionDate",
			"label": "pt.create.groups.propertyAddress.fields.buildingPermissionDate",
			"pattern": "",
			"type": "datePicker",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		},
		{
			"name": "PlinthAreaInBuildingPlan",
			"jsonPath": "PlinthAreaInBuildingPlan",
			"label": "pt.create.groups.propertyAddress.fields.plinthAreaInBuildingPlan",
			"pattern": "",
			"type": "number",
			"isRequired": false,
			"isDisabled": false,
			"requiredErrMsg": "",
			"patternErrMsg": ""
		}
   ]
  }
 ]
}

var dat = {
	"dataEntry.create": {
		"numCols": 12/3,
		"version": "v1",
		"url": "pt-property/properties/_create",
		"useTimestamp": true,
		"objectName": "properties",
		"level": 0,
		"groups": [
			{
				"label": "Owner Details",
				"name": "OwnerDetails",
				"multiple":true,
				"fields": [
						{
							"name": "AadhaarNumber",
							"jsonPath": "AadhaarNumber",
							"label": "pt.create.groups.propertyAddress.fields.aadhaarNumber",
							"pattern": "",
							"type": "number",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "PhoneNumber",
							"jsonPath": "PhoneNumber",
							"label": "pt.create.groups.propertyAddress.fields.phoneNumber",
							"pattern": "",
							"type": "number",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "OwnerName",
							"jsonPath": "OwnerName",
							"label": "pt.create.groups.propertyAddress.fields.ownerName",
							"pattern": "",
							"type": "text",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "Gender",
							"jsonPath": "Gender",
							"label": "pt.create.groups.propertyAddress.fields.gender",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "Email",
							"jsonPath": "Email",
							"label": "pt.create.groups.propertyAddress.fields.email",
							"pattern": "",
							"type": "text",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "GuardianRelation",
							"jsonPath": "GuardianRelation",
							"label": "pt.create.groups.propertyAddress.fields.guardianRelation",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "Guardian",
							"jsonPath": "Guardian",
							"label": "pt.create.groups.propertyAddress.fields.guardian",
							"pattern": "",
							"type": "text",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "OwnerType",
							"jsonPath": "OwnerType",
							"label": "pt.create.groups.propertyAddress.fields.ownerType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "PercentageOfOwnerShip",
							"jsonPath": "PercentageOfOwnerShip",
							"label": "pt.create.groups.propertyAddress.fields.percentageOfOwnerShip",
							"pattern": "",
							"type": "text",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "PrimaryOwner",
							"jsonPath": "PrimaryOwner",
							"label": "",
							"pattern": "",
							"type": "radio",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"values": [{"label":"Primary Owner", "value":true},{"label":"Secondary Owner", "value":false}],
							"defaultValue":true
						},
						
				]
			},
			{
				"label": "Property Address",
				"name": "PropertyAddress",
				"fields": [
						{
							"name": "ReferancePropertyNumber",
							"jsonPath": "ReferancePropertyNumber",
							"label": "pt.create.groups.propertyAddress.fields.referancePropertyNumber",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "Appartment",
							"jsonPath": "Appartment",
							"label": "pt.create.groups.propertyAddress.fields.appartment",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "DoorNo",
							"jsonPath": "DoorNo",
							"label": "pt.create.groups.propertyAddress.fields.doorNo",
							"pattern": "",
							"type": "number",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "Locality",
							"jsonPath": "Locality",
							"label": "pt.create.groups.propertyAddress.fields.locality",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "ElectionWard",
							"jsonPath": "ElectionWard",
							"label": "pt.create.groups.propertyAddress.fields.electionWard",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "ZoneNo",
							"jsonPath": "ZoneNo",
							"label": "pt.create.groups.propertyAddress.fields.zoneNo",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "WardNo",
							"jsonPath": "WardNo",
							"label": "pt.create.groups.propertyAddress.fields.wardNo",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "BlockNo",
							"jsonPath": "BlockNo",
							"label": "pt.create.groups.propertyAddress.fields.blockNo",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "Street",
							"jsonPath": "Street",
							"label": "pt.create.groups.propertyAddress.fields.street",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "RevenueCircle",
							"jsonPath": "RevenueCircle",
							"label": "pt.create.groups.propertyAddress.fields.revenueCircle",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": [],
						},
						{
							"name": "Pin",
							"jsonPath": "Pin",
							"label": "pt.create.groups.propertyAddress.fields.pin",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "IsCorrespondanceAddressDifferentFromAddress",
							"jsonPath": "IsCorrespondanceAddressDifferentFromAddress",
							"label": "pt.create.groups.propertyAddress.fields.isCorrespondanceAddressDifferentFromAddress",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue": false,
						},
						{
							"name": "DoorNo",
							"jsonPath": "DoorNo2",
							"label": "pt.create.groups.propertyAddress.fields.doorNo",
							"pattern": "",
							"type": "number",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "Address1",
							"jsonPath": "Address1",
							"label": "pt.create.groups.propertyAddress.fields.address1",
							"pattern": "",
							"type": "text",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "Pin",
							"jsonPath": "Pin2",
							"label": "pt.create.groups.propertyAddress.fields.pin",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
				]
			},
			{
				"label": "Assessment details",
				"name": "AssessmentDetails",
				"fields": [
						{
							"name": "CreationReason",
							"jsonPath": "CreationReason",
							"label": "pt.create.groups.propertyAddress.fields.creationReason",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "PropertyType",
							"jsonPath": "PropertyType",
							"label": "pt.create.groups.propertyAddress.fields.propertyType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "PropertySubType",
							"jsonPath": "PropertySubType",
							"label": "pt.create.groups.propertyAddress.fields.propertySubType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "Department",
							"jsonPath": "Department",
							"label": "pt.create.groups.propertyAddress.fields.department",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"url": "",
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "ExtentOfSite",
							"jsonPath": "ExtentOfSite",
							"label": "pt.create.groups.propertyAddress.fields.extentOfSite",
							"pattern": "",
							"type": "number",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
				]
			},
			{
				"label": "Amenities",
				"name": "Amenities",
				"fields": [
						{
							"name": "Lift",
							"jsonPath": "Lift",
							"label": "pt.create.groups.propertyAddress.fields.lift",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "Toilet",
							"jsonPath": "Toilet",
							"label": "pt.create.groups.propertyAddress.fields.toilet",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "WaterTap",
							"jsonPath": "WaterTap",
							"label": "pt.create.groups.propertyAddress.fields.waterTap",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "Electricity",
							"jsonPath": "Electricity",
							"label": "pt.create.groups.propertyAddress.fields.electricity",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "AttachedBathroom",
							"jsonPath": "AttachedBathroom",
							"label": "pt.create.groups.propertyAddress.fields.attachedBathroom",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "CableConnection",
							"jsonPath": "CableConnection",
							"label": "pt.create.groups.propertyAddress.fields.cableConnection",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "WaterHarvesting",
							"jsonPath": "WaterHarvesting",
							"label": "pt.create.groups.propertyAddress.fields.waterHarvesting",
							"pattern": "",
							"type": "checkbox",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						
				]
			},
			{
				"label": "Construction Type",
				"name": "ConstructionType",
				"fields": [
						{
							"name": "FloorType",
							"jsonPath": "FloorType",
							"label": "pt.create.groups.propertyAddress.fields.floorType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "RoofType",
							"jsonPath": "RoofType",
							"label": "pt.create.groups.propertyAddress.fields.roofType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "WallType",
							"jsonPath": "WallType",
							"label": "pt.create.groups.propertyAddress.fields.wallType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},	
						{
							"name": "WoodType",
							"jsonPath": "WoodType",
							"label": "pt.create.groups.propertyAddress.fields.woodType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},	
						
				]
			},
			{
				"label": "Floor Details",
				"name": "FloorDetails",
				"multiple":true,
				"children":[rooms],
				"fields": [
						{
							"name": "FloorNumber",
							"jsonPath": "FloorNumber",
							"label": "pt.create.groups.propertyAddress.fields.floorNumber",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "UnitType",
							"jsonPath": "UnitType",
							"label": "pt.create.groups.propertyAddress.fields.unitType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "UnitNumber",
							"jsonPath": "UnitNumber",
							"label": "pt.create.groups.propertyAddress.fields.unitNumber",
							"pattern": "",
							"type": "number",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "ConstructionType",
							"jsonPath": "ConstructionType",
							"label": "pt.create.groups.propertyAddress.fields.constructionType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "UsageType",
							"jsonPath": "UsageType",
							"label": "pt.create.groups.propertyAddress.fields.usageType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "UsageSubType",
							"jsonPath": "UsageSubType",
							"label": "pt.create.groups.propertyAddress.fields.usageSubType",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "FirmName",
							"jsonPath": "FirmName",
							"label": "pt.create.groups.propertyAddress.fields.firmName",
							"pattern": "",
							"type": "text",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "Occupancy",
							"jsonPath": "Occupancy",
							"label": "pt.create.groups.propertyAddress.fields.occupancy",
							"pattern": "",
							"type": "singleValueList",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"url":"",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "OccupantName",
							"jsonPath": "OccupantName",
							"label": "pt.create.groups.propertyAddress.fields.occupantName",
							"pattern": "",
							"type": "text",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "AnnualRent",
							"jsonPath": "AnnualRent",
							"label": "pt.create.groups.propertyAddress.fields.AnnualRent",
							"pattern": "",
							"type": "text",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "ManualArv",
							"jsonPath": "ManualArv",
							"label": "pt.create.groups.propertyAddress.fields.manualArv",
							"pattern": "",
							"type": "text",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "ConstructionDate",
							"jsonPath": "ConstructionDate",
							"label": "pt.create.groups.propertyAddress.fields.constructionDate",
							"pattern": "",
							"type": "datePicker",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "EffectiveFromDate",
							"jsonPath": "EffectiveFromDate",
							"label": "pt.create.groups.propertyAddress.fields.effectiveFromDate",
							"pattern": "",
							"type": "datePicker",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
						},
						{
							"name": "UnstructuredLand",
							"jsonPath": "UnstructuredLand",
							"label": "pt.create.groups.propertyAddress.fields.unstructuredLand",
							"pattern": "",
							"type": "singleValueList",
							"url":"",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": "",
							"defaultValue":[]
						},
						{
							"name": "Length",
							"jsonPath": "Length",
							"label": "pt.create.groups.propertyAddress.fields.length",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "Breadth",
							"jsonPath": "Breadth",
							"label": "pt.create.groups.propertyAddress.fields.breadth",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "PlinthArea",
							"jsonPath": "PlinthArea",
							"label": "pt.create.groups.propertyAddress.fields.plinthArea",
							"pattern": "",
							"type": "number",
							"isRequired": true,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "OccupancyCertificateNumber",
							"jsonPath": "OccupancyCertificateNumber",
							"label": "pt.create.groups.propertyAddress.fields.occupancyCertificateNumber",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "BuildingPermissionNumber",
							"jsonPath": "BuildingPermissionNumber",
							"label": "pt.create.groups.propertyAddress.fields.buildingPermissionNumber",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "BuildingPermissionDate",
							"jsonPath": "BuildingPermissionDate",
							"label": "pt.create.groups.propertyAddress.fields.buildingPermissionDate",
							"pattern": "",
							"type": "datePicker",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
						{
							"name": "PlinthAreaInBuildingPlan",
							"jsonPath": "PlinthAreaInBuildingPlan",
							"label": "pt.create.groups.propertyAddress.fields.plinthAreaInBuildingPlan",
							"pattern": "",
							"type": "number",
							"isRequired": false,
							"isDisabled": false,
							"requiredErrMsg": "",
							"patternErrMsg": ""
						},
	
				]
			},
			{
				"label": "Documents",
				"name": "Documents",
				"fields": [
						{
						  "name": "File",
						  "jsonPath": "File",
						  "type": "documentList",
						  "pathToArray": "DocumentTypeApplicationTypes",
						  "displayNameJsonPath": "documentType",
						  "url": "",
						  "autoFillFields": [{
							"name": "document",
							"jsonPath": "documentTypeId"
						  }]
						}	
				]
			}
			
			
		]
	}
}

export default dat;


//doubts

//Reference property number
