CREATE SEQUENCE seq_egasset_assetcategory;
CREATE SEQUENCE seq_egasset_categorycode;

CREATE TABLE EGASSET_ASSETCATEGORY (
	id BIGINT NOT NULL,
	name CHARACTER VARYING(250) NOT NULL,
	code CHARACTER VARYING(250) NOT NULL,
	parentId CHARACTER VARYING(250),
	depreciationMethod CHARACTER VARYING(250),
	assetAccount CHARACTER VARYING(250) NOT NULL,
	accumulatedDepreciationAccount CHARACTER VARYING(250),
	revaluationReserveAccount CHARACTER VARYING(250) NOT NULL,
	depreciationExpenseAccount CHARACTER VARYING(250),
	unitOfMeasurement CHARACTER VARYING(250),
	customFields CHARACTER VARYING(250),
	tenantId CHARACTER VARYING(250),
	createdBy CHARACTER VARYING(64) NOT NULL,
	createdDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lastModifiedBy CHARACTER VARYING(64),
    lastModifiedDate TIMESTAMP WITHOUT TIME ZONE,

	CONSTRAINT PK_EGASSET_ASSETCATEGORY PRIMARY KEY (id),
	CONSTRAINT UK_EGASSET_ASSETCATEGORY_CODE UNIQUE (code)
);