/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorRes;
import io.swagger.model.PurchaseIndentRequest;
import io.swagger.model.PurchaseIndentResponse;
import io.swagger.model.RequestInfo;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;

import java.util.List;
import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-10-28T13:21:55.964+05:30")

@Api(value = "purchaseindents", description = "the purchaseindents API")
public interface PurchaseindentsApi {

    @ApiOperation(value = "Create  new  purchaseindents", nickname = "purchaseindentsCreatePost", notes = "Create  new purchaseindents", response = PurchaseIndentResponse.class, tags={ "Inventory","PurchaseIndent", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "PurchaseIndent created Successfully", response = PurchaseIndentResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/purchaseindents/_create",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PurchaseIndentResponse> purchaseindentsCreatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Create  new"  )  @Valid @RequestBody PurchaseIndentRequest purchaseIndentRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Get the list of purchaseindents", nickname = "purchaseindentsSearchPost", notes = "purchaseindents", response = PurchaseIndentResponse.class, tags={ "Inventory","PurchaseIndent", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "PurchaseIndent retrieved Successfully", response = PurchaseIndentResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/purchaseindents/_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PurchaseIndentResponse> purchaseindentsSearchPost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Parameter to carry Request metadata in the request body"  )  @Valid @RequestBody RequestInfo requestInfo,@ApiParam(value = "purchase order of the PurchaseIndent ") @Valid @RequestParam(value = "purchaseOrder", required = false) Long purchaseOrder,@ApiParam(value = "indent of the PurchaseIndent ") @Valid @RequestParam(value = "indent", required = false) Long indent,@ApiParam(value = "pageSize") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "offset") @Valid @RequestParam(value = "offset", required = false) Integer offset,@ApiParam(value = "This takes any field from the Object seperated by comma and asc,desc keywords.   example name asc,code desc or name,code or name,code desc  ") @Valid @RequestParam(value = "sortBy", required = false) String sortBy, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Update any of the purchaseindents", nickname = "purchaseindentsUpdatePost", notes = "Update any of the purchaseindents", response = PurchaseIndentResponse.class, tags={ "Inventory","PurchaseIndent", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "PurchaseIndent updated Successfully", response = PurchaseIndentResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/purchaseindents/_update",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PurchaseIndentResponse> purchaseindentsUpdatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "common Request info"  )  @Valid @RequestBody PurchaseIndentRequest purchaseIndentRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
