CREATE TABLE egeis_hrStatus (
	id BIGINT NOT NULL,
	objectName CHARACTER VARYING(50) NOT NULL,
	code CHARACTER VARYING(20) NOT NULL,
	description CHARACTER VARYING(250) NOT NULL,
	tenantId CHARACTER VARYING(250) NOT NULL,

	CONSTRAINT pk_egeis_hrStatus PRIMARY KEY (id)
);

CREATE SEQUENCE seq_egeis_hrStatus
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;