---------demand reasons for FY 2013-14 and 2014-15

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODE, tenantid) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Rent' and module='Leases And Agreements' and tenantid='default'), inst.id, null, null, current_timestamp, current_timestamp, '1301001', 'default' from eg_installment_master inst where inst.module='Leases And Agreements' and inst.tenantid='default' and inst.id not in(select ID_INSTALLMENT from eg_demand_reason where tenantid='default'and ID_DEMAND_REASON_MASTER = (select id from EG_DEMAND_REASON_MASTER where code='RENT' and tenantid='default'));

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODE, tenantid) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Advance Tax' and module='Leases And Agreements' and tenantid='default'), inst.id, null, null, current_timestamp, current_timestamp, '1301001', 'default' from eg_installment_master inst where inst.module='Leases And Agreements' and inst.tenantid='default'  and inst.id not in(select ID_INSTALLMENT from eg_demand_reason where tenantid='default' and ID_DEMAND_REASON_MASTER = (select id from EG_DEMAND_REASON_MASTER where code='ADVANCE_TAX' and tenantid='default'));

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODE, tenantid) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Goodwill Amount' and module='Leases And Agreements' and tenantid='default'), inst.id, null, null, current_timestamp, current_timestamp, '1301001', 'default' from eg_installment_master inst where inst.module='Leases And Agreements' and inst.tenantid='default' and inst.id not in(select ID_INSTALLMENT from eg_demand_reason where tenantid='default' and ID_DEMAND_REASON_MASTER = (select id from EG_DEMAND_REASON_MASTER where code='GOODWILL_AMOUNT' and tenantid='default'));

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODE, tenantid) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Penalty' and module='Leases And Agreements' and tenantid='default'), inst.id, null, null, current_timestamp, current_timestamp, '1402010', 'default' from eg_installment_master inst where inst.module='Leases And Agreements' and inst.tenantid='default' and inst.id not in(select ID_INSTALLMENT from eg_demand_reason where tenantid='default' and ID_DEMAND_REASON_MASTER = (select id from EG_DEMAND_REASON_MASTER where code='PENALTY' and tenantid='default'));
