package org.egov.egf.voucher.web.contract;

public enum VoucherTypeContract {
    STANDARD_VOUCHER_TYPE_CONTRA, STANDARD_VOUCHER_TYPE_PAYMENT, STANDARD_VOUCHER_TYPE_RECEIPT, STANDARD_VOUCHER_TYPE_JOURNAL
}
