var dat ={  
  "swm.search":{  
     "numCols":3,
     "useTimestamp":true,
     "objectName":"refillingPumpStations",
     "url":"/swm-services/refillingpumpstations/_search",
     "groups":[  
        {  
           "name":"search",
           "label":"swm.search.refillingPumpStations.title",
           "fields":[  
            {  
              "name":"name",
              "jsonPath":"name",
              "label":"swm.refillingpumpstations.create.name",
              "type":"text",
              "isRequired":false,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
            },
            {  
              "name":"code",
              "jsonPath":"typeOfPumpCode",
              "label":"swm.refillingpumpstations.typeOfPump.name",
              "type":"singleValueList",
              "isRequired":false,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":"",
              "url": "/egov-mdms-service/v1/_get?&moduleName=SWM&masterName=OilCompany|$..code|$..name"
            },
	   {  
                "name":"name",
                "jsonPath":"typeOfFuelCode",
                "label":"swm.refillingpumpstations.typeOfFuel",
                "type":"singleValueList",
                "isRequired":false,
                "isDisabled":false,
                "maxLength":128,
                "minLength":1,
                "patternErrorMsg":"",
                "url": "/egov-mdms-service/v1/_get?&moduleName=SWM&masterName=FuelType|$..code|$..name"
            }
          ]
        }
     ],
     "result":{  
        "header":[  
           {  
              "label":"swm.refillingpumpstations.create.name"
           },
           {  
              "label":"swm.refillingpumpstations.typeOfPump.name"
           },
	  {  
              "label":"swm.refillingpumpstations.typeOfFuel"
           },
          {  
              "label":"swm.refillingpumpstations.quantity"
           },
	  {  
              "label":"swm.collectionpoints.create.colony"
           }
        ],
        "values":[  
           "name",
           "typeOfPump.name",
	   "typeOfFuel.name",
	   "quantity",
	   "location.name"
        ],
        "resultPath":"refillingPumpStations",
        "rowClickUrlUpdate":"/update/swm/refillingpumpstations/{code}",
        "rowClickUrlView":"/view/swm/refillingpumpstations/{code}"
     }
  },
  "swm.create":{  
     "numCols":3,
     "useTimestamp":true,
     "objectName":"refillingPumpStations",
     "idJsonPath": "refillingPumpStations[0].code",
     "title": "swm.refillingpumpstations.create.title",
     "groups":[  
        {  
          "name":"LocationDetails",
          "label":"swm.collectionpoints.create.group.title.LocationDetails",
          "fields":[  
            {  
              "name":"Ward",
              "jsonPath":"refillingPumpStations[0].location.ward",
              "label":"swm.collectionpoints.create.ward",
              "type":"singleValueList",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "url": "egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?tenantId=default&boundaryTypeName=Ward&hierarchyTypeName=REVENUE|$.Boundary.*.id|$.Boundary.*.name",
              "minLength":1,
              "patternErrorMsg":"",
              "depedants": [{
                "jsonPath": "refillingPumpStations[0].location.zone",
                "type": "dropDown",
                "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={refillingPumpStations[0].location.ward}|$.Boundary.*.id|$.Boundary.*.name"
              }]
            },
            {  
                "name":"Zone",
                "jsonPath":"refillingPumpStations[0].location.zone",
                "label":"swm.collectionpoints.create.zone",
                "type":"singleValueList",
                "isRequired":true,
                "isDisabled":false,
                "maxLength":128,
                "minLength":1,
                "patternErrorMsg":"",
                "depedants": [{
                  "jsonPath": "refillingPumpStations[0].location.block",
                  "type": "dropDown",
                  "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={refillingPumpStations[0].location.zone}|$.Boundary.*.id|$.Boundary.*.name"
                }]
            },
            {  
                "name":"Road/Street",
                "jsonPath":"refillingPumpStations[0].location.block",
                "label":"swm.collectionpoints.create.block",
                "type":"singleValueList",
                "isRequired":true,
                "isDisabled":false,
                "maxLength":128,
                "minLength":1,
                "patternErrorMsg":"",
                "depedants": [{
                  "jsonPath": "refillingPumpStations[0].location.code",
                  "type": "dropDown",
                  "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={refillingPumpStations[0].location.block}|$.Boundary.*.id|$.Boundary.*.name"
                }]
            },
            {  
                "name":"Colony",
                "jsonPath":"refillingPumpStations[0].location.code",
                "label":"swm.collectionpoints.create.colony",
                "type":"singleValueList",
                "isRequired":true,
                "isDisabled":false,
                "maxLength":128,
                "minLength":1,
                "patternErrorMsg":""
            }
          ]
        },
        {  
          "name":"RefillingPumpName",
          "label":"swm.refillingpumpstations.create.group.title.RefillingPumpName",
          "fields":[  
            {  
                "name":"name",
                "jsonPath":"refillingPumpStations[0].name",
                "label":"swm.refillingpumpstations.create.name",
                "type":"text",
                "isRequired":true,
                "isDisabled":false,
                "maxLength":128,
                "minLength":1,
                "patternErrorMsg":""
            },
            {  
              "name":"name",
              "jsonPath":"refillingPumpStations[0].typeOfPump.code",
              "label":"swm.refillingpumpstations.typeOfPump.name",
              "type":"singleValueList",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":"",
              "url": "/egov-mdms-service/v1/_get?&moduleName=SWM&masterName=OilCompany|$..code|$..name"
            },
            {  
              "name":"name",
              "jsonPath":"refillingPumpStations[0].remarks",
              "label":"legacylegal.create.remarks",
              "type":"text",
              "isRequired":false,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
            }
          ]
        },
        {  
          "name":"FuelDetails",
          "label":"swm.refillingpumpstations.create.group.title.FuelDetails",
          "fields":[  
            {  
                "name":"name",
                "jsonPath":"refillingPumpStations[0].typeOfFuel.code",
                "label":"swm.refillingpumpstations.typeOfFuel",
                "type":"singleValueList",
                "isRequired":true,
                "isDisabled":false,
                "maxLength":128,
                "minLength":1,
                "patternErrorMsg":"",
                "url": "/egov-mdms-service/v1/_get?&moduleName=SWM&masterName=FuelType|$..code|$..name"
            },
            {  
              "name":"name",
              "jsonPath":"refillingPumpStations[0].quantity",
              "label":"swm.refillingpumpstations.quantity",
              "type":"number",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
            }
          ]
        }
     ],
     "url":"/swm-services/refillingpumpstations/_create",
     "tenantIdRequired":true
  },
  "swm.view":{  
     "numCols":3,
     "useTimestamp":true,
     "objectName":"refillingpumpstations",
     "groups":[  
      {  
        "name":"LocationDetails",
        "label":"swm.collectionpoints.create.group.title.LocationDetails",
        "fields":[  
          {  
              "name":"Colony",
              "jsonPath":"refillingPumpStations[0].location.name",
              "label":"swm.collectionpoints.create.colony",
              "type":"singleValueList",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
          }
        ]
      },
      {  
        "name":"RefillingPumpName",
        "label":"swm.refillingpumpstations.create.group.title.RefillingPumpName",
        "fields":[  
          {  
              "name":"name",
              "jsonPath":"refillingPumpStations[0].name",
              "label":"swm.refillingpumpstations.create.name",
              "type":"text",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
          },
          {  
            "name":"name",
            "jsonPath":"refillingPumpStations[0].typeOfPump.name",
            "label":"swm.refillingpumpstations.typeOfPump.name",
            "type":"text",
            "isRequired":true,
            "isDisabled":false,
            "maxLength":128,
            "minLength":1,
            "patternErrorMsg":""
          },
          {  
            "name":"name",
            "jsonPath":"refillingPumpStations[0].remarks",
            "label":"legacylegal.create.remarks",
            "type":"text",
            "isRequired":true,
            "isDisabled":false,
            "maxLength":128,
            "minLength":1,
            "patternErrorMsg":""
          }
        ]
      },
      {  
        "name":"FuelDetails",
        "label":"swm.refillingpumpstations.create.group.title.FuelDetails",
        "fields":[  
          {  
              "name":"name",
              "jsonPath":"refillingPumpStations[0].typeOfFuel.name",
              "label":"swm.refillingpumpstations.typeOfFuel",
              "type":"text",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
          },
          {  
            "name":"name",
            "jsonPath":"refillingPumpStations[0].quantity",
            "label":"swm.refillingpumpstations.quantity",
            "type":"text",
            "isRequired":true,
            "isDisabled":false,
            "maxLength":128,
            "minLength":1,
            "patternErrorMsg":""
          }
        ]
      }
    ],
     "tenantIdRequired":true,
     "url":"/swm-services/refillingpumpstations/_search?code={code}"
  },
  "swm.update":{  
     "numCols":3,
     "useTimestamp":true,
     "objectName":"refillingpumpstations",
     "idJsonPath": "refillingPumpStations[0].code",
     "groups":[  
      {  
        "name":"LocationDetails",
        "label":"swm.collectionpoints.create.group.title.LocationDetails",
        "fields":[  
          {  
            "name":"Ward",
            "jsonPath":"refillingPumpStations[0].location.ward",
            "label":"swm.collectionpoints.create.ward",
            "type":"singleValueList",
            "isRequired":true,
            "isDisabled":false,
            "maxLength":128,
            "url": "egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?tenantId=default&boundaryTypeName=Ward&hierarchyTypeName=REVENUE|$.Boundary.*.id|$.Boundary.*.name",
            "minLength":1,
            "patternErrorMsg":"",
            "depedants": [{
              "jsonPath": "refillingPumpStations[0].location.zone",
              "type": "dropDown",
              "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={refillingPumpStations[0].location.ward}|$.Boundary.*.id|$.Boundary.*.name"
            }]
          },
          {  
              "name":"Zone",
              "jsonPath":"refillingPumpStations[0].location.zone",
              "label":"swm.collectionpoints.create.zone",
              "type":"singleValueList",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":"",
              "depedants": [{
                "jsonPath": "refillingPumpStations[0].location.block",
                "type": "dropDown",
                "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={refillingPumpStations[0].location.zone}|$.Boundary.*.id|$.Boundary.*.name"
              }]
          },
          {  
              "name":"Road/Street",
              "jsonPath":"refillingPumpStations[0].location.block",
              "label":"swm.collectionpoints.create.block",
              "type":"singleValueList",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":"",
              "depedants": [{
                "jsonPath": "refillingPumpStations[0].location.code",
                "type": "dropDown",
                "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={refillingPumpStations[0].location.block}|$.Boundary.*.id|$.Boundary.*.name"
              }]
          },
          {  
              "name":"Colony",
              "jsonPath":"refillingPumpStations[0].location.code",
              "label":"swm.collectionpoints.create.colony",
              "type":"singleValueList",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
          }
        ]
      },
      {  
        "name":"RefillingPumpName",
        "label":"swm.refillingpumpstations.create.group.title.RefillingPumpName",
        "fields":[  
          {  
              "name":"name",
              "jsonPath":"refillingPumpStations[0].name",
              "label":"swm.refillingpumpstations.create.name",
              "type":"text",
              "isRequired":true,
              "isDisabled":true,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":""
          },
          {  
            "name":"name",
            "jsonPath":"refillingPumpStations[0].typeOfPump.code",
            "label":"swm.refillingpumpstations.typeOfPump.name",
            "type":"singleValueList",
            "isRequired":true,
            "isDisabled":false,
            "maxLength":128,
            "minLength":1,
            "patternErrorMsg":"",
            "url": "/egov-mdms-service/v1/_get?&moduleName=SWM&masterName=OilCompany|$..code|$..name"
          },
          {  
            "name":"name",
            "jsonPath":"refillingPumpStations[0].remarks",
            "label":"legacylegal.create.remarks",
            "type":"text",
            "isRequired":false,
            "isDisabled":false,
            "maxLength":128,
            "minLength":1,
            "patternErrorMsg":""
          }
        ]
      },
      {  
        "name":"FuelDetails",
        "label":"swm.refillingpumpstations.create.group.title.FuelDetails",
        "fields":[  
          {  
              "name":"name",
              "jsonPath":"refillingPumpStations[0].typeOfFuel.code",
              "label":"swm.refillingpumpstations.typeOfFuel",
              "type":"singleValueList",
              "isRequired":true,
              "isDisabled":false,
              "maxLength":128,
              "minLength":1,
              "patternErrorMsg":"",
	      "url": "/egov-mdms-service/v1/_get?&moduleName=SWM&masterName=FuelType|$..code|$..name"
          },
          {  
            "name":"name",
            "jsonPath":"refillingPumpStations[0].quantity",
            "label":"swm.refillingpumpstations.quantity",
            "type":"number",
            "isRequired":true,
            "isDisabled":false,
            "maxLength":128,
            "minLength":1,
            "patternErrorMsg":""
          }
        ]
      }
     ],
     "url":"/swm-services/refillingpumpstations/_update",
     "tenantIdRequired":true,
     "searchUrl":"/swm-services/refillingpumpstations/_search?code={code}"
  }
}
export default dat;
