var dat = {
  "swm.search":{
     "numCols":4,
     "useTimestamp":true,
     "objectName":"",
     "url":"/swm-services/vendors/_search",
     "groups":[
        {
            "name":"search",
            "label":"swm.search.title",
            "fields":[
              {
                 "name":"vendorNos",
                 "jsonPath":"vendorNos",
                 "label":"swm.create.vendorNos",
                 "type":"",
                 "isDisabled":false,
                 "patternErrorMsg":"swm.create.field.message.vendorNos"
              },
              {
                 "name":"vendorNo",
                 "jsonPath":"vendorNo",
                 "label":"swm.create.vendorNo",
                 "type":"text",
                 "isDisabled":false,
                 "patternErrorMsg":"swm.create.field.message.vendorNo"
              },
              {
                 "name":"name",
                 "jsonPath":"name",
                 "label":"swm.create.name",
                 "type":"text",
                 "isDisabled":false,
                 "patternErrorMsg":"swm.create.field.message.name"
              },
              {
                 "name":"registrationNo",
                 "jsonPath":"registrationNo",
                 "label":"swm.create.registrationNo",
                 "type":"text",
                 "isDisabled":false,
                 "maxLength":256,
                 "patternErrorMsg":"swm.create.field.message.registrationNo"
              },
              {
                 "name":"supplier",
                 "jsonPath":"supplier",
                 "label":"swm.create.supplier",
                 "type":"text",
                 "isDisabled":false,
                 "maxLength":256,
                 "patternErrorMsg":"swm.create.field.message.supplier"
              },
              {
                 "name":"offSet",
                 "jsonPath":"offSet",
                 "label":"swm.create.offSet",
                 "type":"number",
                 "isDisabled":false,
                 "patternErrorMsg":"swm.create.field.message.offSet"
              },
              {
                 "name":"sortBy",
                 "jsonPath":"sortBy",
                 "label":"swm.create.sortBy",
                 "type":"text",
                 "isDisabled":false,
                 "patternErrorMsg":"swm.create.field.message.sortBy"
              }
           ]
        }
     ],
     "result":{
        "header":[
           {
              "label":"swm.search.result.vendorNo"
           }
        ],
        "values":[
           "vendorNo"
        ],
        "resultPath":"vendors",
        "rowClickUrlUpdate":"/update/swm/vendors/{vendorNo}",
        "rowClickUrlView":"/view/swm/vendors/{vendorNo}"
     }
  },
  "swm.create":{
     "numCols":3,
     "useTimestamp":true,
     "objectName":"vendors",
     "groups":[
        {
           "name":"vendors",
           "label":"swm.create.group.title.vendors",
           "fields":[
              {
                 "name":"vendorNo",
                 "jsonPath":"vendors[0].vendorNo",
                 "label":"swm.create.vendorNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":128,
                 "minLength":1,
                 "patternErrorMsg":""
              }
           ]
        },  
        {
            "name":"VendorDetails",
            "label":"swm.create.group.title.VendorDetails",
            "fields":[
              {
                 "name":"name",
                 "jsonPath":"vendors[0].name",
                 "label":"swm.create.name",
                 "pattern":"",
                 "type":"text",
                 "isRequired":true,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"mobileNo",
                 "jsonPath":"vendors[0].supplier.mobileNo",
                 "label":"swm.create.supplier.mobileNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"registrationNo",
                 "jsonPath":"vendors[0].registrationNo",
                 "label":"swm.create.registrationNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":true,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"contactNo",
                 "jsonPath":"vendors[0].supplier.contactNo",
                 "label":"swm.create.supplier.contactNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"email",
                 "jsonPath":"vendors[0].supplier.email",
                 "label":"swm.create.supplier.email",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":100,
                 "minLength":6,
                 "patternErrorMsg":""
              },
              {
                 "name":"faxNumber",
                 "jsonPath":"vendors[0].supplier.faxNumber",
                 "label":"swm.create.supplier.faxNumber",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"tinNumber",
                 "jsonPath":"vendors[0].supplier.tinNumber",
                 "label":"swm.create.supplier.tinNumber",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"address",
                 "jsonPath":"vendors[0].supplier.address",
                 "label":"swm.create.supplier.address",
                 "pattern":"",
                 "type":"textarea",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":500,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"gst",
                 "jsonPath":"vendors[0].supplier.gst",
                 "label":"swm.create.supplier.gst",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              }
           ]
        },
        {
          "name":"LocationDetails",
          "label":"swm.collectionpoints.create.group.title.LocationDetails",
          "fields": [
            {
              "name": "",
              "label": "",
              "type": "multiFieldAddToTable",
              "jsonPath": "vendors[0].myTable",
              "header": [{
                  "label": "Ward"
                }, {
                  "label": "Zone"
                },
                {
                  "label": "Road/Street"
                },
                {
                  "label": "Colony"
              }],
              "values": [
                {  
                  "name":"Ward",
                  "jsonPath":"vendors[0].myTable[0].ward",
                  "label":"swm.collectionpoints.create.ward",
                  "type":"singleValueList",
                  "isRequired":true,
                  "isDisabled":false,
                  "maxLength":128,
                  "url": "egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?tenantId=default&boundaryTypeName=Ward&hierarchyTypeName=REVENUE|$.Boundary.*.id|$.Boundary.*.name",
                  "minLength":1,
                  "patternErrorMsg":"",
                  "depedants": [{
                    "jsonPath": "vendors[0].myTable[0].zone",
                    "type": "dropDown",
                    "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={vendors[0].myTable[0].ward}|$.Boundary.*.id|$.Boundary.*.name"
                  }]
                },
                {  
                  "name":"Zone",
                  "jsonPath":"vendors[0].myTable[0].zone",
                  "label":"swm.collectionpoints.create.zone",
                  "type":"singleValueList",
                  "isRequired":true,
                  "isDisabled":false,
                  "maxLength":128,
                  "minLength":1,
                  "patternErrorMsg":"",
                  "depedants": [{
                    "jsonPath": "vendors[0].myTable[0].block",
                    "type": "dropDown",
                    "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={vendors[0].myTable[0].zone}|$.Boundary.*.id|$.Boundary.*.name"
                  }]
                },
                {  
                  "name":"Road/Street",
                  "jsonPath":"vendors[0].myTable[0].block",
                  "label":"swm.collectionpoints.create.block",
                  "type":"singleValueList",
                  "isRequired":true,
                  "isDisabled":false,
                  "maxLength":128,
                  "minLength":1,
                  "patternErrorMsg":"",
                  "depedants": [{
                    "jsonPath": "vendors[0].myTable[0].code",
                    "type": "dropDown",
                    "pattern": "egov-location/boundarys/childLocationsByBoundaryId?tenantId=default&boundaryId={vendors[0].myTable[0].block}|$.Boundary.*.id|$.Boundary.*.name"
                  }]
                },
                {  
                  "name":"Colony",
                  "jsonPath":"vendors[0].myTable[0].code",
                  "label":"swm.collectionpoints.create.colony",
                  "type":"singleValueList",
                  "isRequired":true,
                  "isDisabled":false,
                  "maxLength":128,
                  "minLength":1,
                  "patternErrorMsg":""
                }
              ]
            }
          ]
        },
        {
           "name":"ServicesOffered",
           "label":"swm.create.group.title.ServicesOffered",
           "fields":[
              {
                 "name":"details",
                 "jsonPath":"vendors[0].details",
                 "label":"swm.create.details",
                 "pattern":"",
                 "type":"textarea",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":500,
                 "minLength":10,
                 "patternErrorMsg":""
              }
           ]
        }
     ],
     "url":"/swm-services/vendors/_create",
     "tenantIdRequired":true
  },
  "swm.view":{
      "numCols":4,
      "useTimestamp":true,
      "objectName":"vendors",
      "groups":[
        {
           "name":"vendors",
           "label":"swm.create.group.title.vendors",
           "fields":[
              {
                 "name":"vendorNo",
                 "jsonPath":"vendors[0].vendorNo",
                 "label":"swm.create.vendorNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":128,
                 "minLength":1,
                 "patternErrorMsg":""
              }
           ]
        },
        {
           "name":"VendorDetails",
           "label":"swm.create.group.title.VendorDetails",
           "fields":[
              {
                 "name":"name",
                 "jsonPath":"vendors[0].name",
                 "label":"swm.create.name",
                 "pattern":"",
                 "type":"text",
                 "isRequired":true,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"mobileNo",
                 "jsonPath":"vendors[0].supplier.mobileNo",
                 "label":"swm.create.supplier.mobileNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"registrationNo",
                 "jsonPath":"vendors[0].registrationNo",
                 "label":"swm.create.registrationNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":true,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"contactNo",
                 "jsonPath":"vendors[0].supplier.contactNo",
                 "label":"swm.create.supplier.contactNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"email",
                 "jsonPath":"vendors[0].supplier.email",
                 "label":"swm.create.supplier.email",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":100,
                 "minLength":6,
                 "patternErrorMsg":""
              },
              {
                 "name":"faxNumber",
                 "jsonPath":"vendors[0].supplier.faxNumber",
                 "label":"swm.create.supplier.faxNumber",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"tinNumber",
                 "jsonPath":"vendors[0].supplier.tinNumber",
                 "label":"swm.create.supplier.tinNumber",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"address",
                 "jsonPath":"vendors[0].supplier.address",
                 "label":"swm.create.supplier.address",
                 "pattern":"",
                 "type":"textarea",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":500,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"gst",
                 "jsonPath":"vendors[0].supplier.gst",
                 "label":"swm.create.supplier.gst",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              }
           ]
        },
        {
          "name":"ServicesOffered",
          "label":"swm.create.group.title.ServicesOffered",
          "fields":[
            {
              "name":"details",
              "jsonPath":"vendors[0].details",
              "label":"swm.create.details",
              "pattern":"",
              "type":"textarea",
              "isRequired":false,
              "isDisabled":false,
              "defaultValue":"",
              "maxLength":500,
              "minLength":10,
              "patternErrorMsg":""
            }
          ]
        }
     ],
     "tenantIdRequired":true,
     "url":"/swm-services/vendors/_search?vendorNo={vendorNo}"
  },
  "swm.update":{
     "numCols":4,
     "useTimestamp":true,
     "objectName":"vendors",
     "groups":[
        {
           "name":"vendors",
           "label":"swm.create.group.title.vendors",
           "fields":[
              {
                 "name":"vendorNo",
                 "jsonPath":"vendors[0].vendorNo",
                 "label":"swm.create.vendorNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":128,
                 "minLength":1,
                 "patternErrorMsg":""
              }
           ]
        },
        {
           "name":"VendorDetails",
           "label":"swm.create.group.title.VendorDetails",
           "fields":[
              {
                 "name":"name",
                 "jsonPath":"vendors[0].name",
                 "label":"swm.create.name",
                 "pattern":"",
                 "type":"text",
                 "isRequired":true,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"mobileNo",
                 "jsonPath":"vendors[0].supplier.mobileNo",
                 "label":"swm.create.supplier.mobileNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"registrationNo",
                 "jsonPath":"vendors[0].registrationNo",
                 "label":"swm.create.registrationNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":true,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"contactNo",
                 "jsonPath":"vendors[0].supplier.contactNo",
                 "label":"swm.create.supplier.contactNo",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"email",
                 "jsonPath":"vendors[0].supplier.email",
                 "label":"swm.create.supplier.email",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":100,
                 "minLength":6,
                 "patternErrorMsg":""
              },
              {
                 "name":"faxNumber",
                 "jsonPath":"vendors[0].supplier.faxNumber",
                 "label":"swm.create.supplier.faxNumber",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":10,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"tinNumber",
                 "jsonPath":"vendors[0].supplier.tinNumber",
                 "label":"swm.create.supplier.tinNumber",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              },
              {
                 "name":"address",
                 "jsonPath":"vendors[0].supplier.address",
                 "label":"swm.create.supplier.address",
                 "pattern":"",
                 "type":"textarea",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":500,
                 "minLength":10,
                 "patternErrorMsg":""
              },
              {
                 "name":"gst",
                 "jsonPath":"vendors[0].supplier.gst",
                 "label":"swm.create.supplier.gst",
                 "pattern":"",
                 "type":"text",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":256,
                 "minLength":1,
                 "patternErrorMsg":""
              }
           ]
        },
        {
           "name":"ServicesOffered",
           "label":"swm.create.group.title.ServicesOffered",
           "fields":[
              {
                 "name":"details",
                 "jsonPath":"vendors[0].details",
                 "label":"swm.create.details",
                 "pattern":"",
                 "type":"textarea",
                 "isRequired":false,
                 "isDisabled":false,
                 "defaultValue":"",
                 "maxLength":500,
                 "minLength":10,
                 "patternErrorMsg":""
              }
           ]
        }
     ],
     "url":"/swm-services/vendors/_update",
     "tenantIdRequired":true,
     "searchUrl":"/swm-services/vendors/_search?vendorNo={vendorNo}"
  }
}
 export default dat;