const defaultState = {
  "core.lbl.login": "Login",
  "core.lbl.register": "Register",
  "core.lbl.forgot.password": "Forgot Password?",
  "core.lbl.password": "Password",
  "core.lbl.new.password": "New Password",
  "core.lbl.confirm.password": "Confirm Password",
  "core.lbl.fullname": "Full Name",
  "core.lbl.city": "City",
  "core.lbl.code": "Code",
  "core.lbl.mobilenumber": "Mobile Number",
  "core.error.username.blank": "Username can't be blank",
  "core.error.city.blank": "City can't be blank",
  "core.error.otp.blank": "OTP can't be blank",
  "core.error.fullname.blank": "Enter your full name!",
  "core.error.password.confirmpassword.same": "Password and Confirm Password should be same",
  "core.alert.pleasewait": "Processing your request. Please wait..",
  "core.lbl.signup": "Sign Up",
  "core.error.user.creation": "User couldn't have been created.",
  "core.error.username.update": "Not able to update user {$userName}.",
  "core.error.signup.failed": "Sign-up failed",
  "core.error.login.failed": "Login failed",
  "core.error.invalid.credentials": "Invalid Credentials",
  "core.error.opt.generation": "Could not generate or send OTP.",
  "core.lbl.otp": "OTP",
  "pgr.lbl.post.servicerequest": "Post Service Request",
  "pgr.lbl.generate.otp": "Generate OTP",
  "core.lbl.send": "Send",
  "core.lbl.servicename": "Service Name",
  "core.lbl.address": "Address",
  "core.lbl.description": "Description",
  "core.lbl.landmark": "Landmark",
  "pgr.error.servicerequest.notfound": "service code or jurisdiction id was not provided or General service error.",
  "pgr.error.bad.servicerequest": "service code or jurisdiction id provided were not found.",
  "core.lbl.alert.goto.settings.enable.permissions": "Go to settings and enable permissions",
  "core.lbl.alert.externalstorageaccesspermission.harddisk": "External storage Permission is required for this app to access images from SD card",
  "core.lbl.select.source": "Select Source",
  "core.lbl.photo": "Photo",
  "core.alert.search.here": "Search here..",
  "pgr.lbl.complaint.category": "Complaint Category",
  "core.lbl.upload.photoimage": "Upload Photograph/Video",
  "pgr.lbl.sla.limit": "SLA upto 4 days",
  "core.title.mseva.appname": "mSeva",
  "pgr.location.change.infomessage": "By default it will show your current location. You can always change the location by clicking on the location pin",
  "pgr.lbl.select.location": "Select Location",
  "pgr.lbl.file.complaint": "File a complaint",
  "pgr.lbl.my.complaints": "My complaints",
  "core.uri.list": "uri list",
  "core.deleted.uri.list": "deleted uri index list",
  "core.uri.selection": "uri selection",
  "core.msg.complete.signup": "It just takes 2 minute to complete sign-up",
  "pgr.lbl.complaintno": "Complaint No",
  "pgr.lbl.complainttype": "Complaint Type",
  "core.lbl.department": "Department",
  "core.lbl.date.format": "dd-MM-yyyy hh:mm:ss",
  "core.lbl.date.format.mobileui": "dd MMMM yyyy",
  "pgr.lbl.complainthistory.date.format": "dd MMM yyyy",
  "pgr.lbl.selected.servicerequest.key": "selected_service_request",
  "core.lbl.notifications": "Notifications",
  "pgr.lbl.complaint.field": "Complaint Filed",
  "pgr.lbl.complaint.update": "Complaint Update",
  "core.title.listen": "We Listen",
  "core.title.connect": "We Connect",
  "core.title.track": "We Track",
  "core.title.solve": "We Solve",
  "pgr.msg.complaint.tellus": "Have a complaint tell us.",
  "pgr.msg.complaint.connectto.official": "We connect you to the responsible official",
  "pgr.msg.complaintstatus.anytime": "Know the status of your complaint anytime!",
  "pgr.msg.official.resolve.complaint": "Our official resolves the complaint",
  "pgr.title.create.grievence": "Create Grievance",
  "core.lbl.page.footer": "Powered by eGovernments Foundation",
  "pgr.msg.servicerequest.underprocess": "Service Request is received and is under process",
  "core.msg.account.create": "Create Your Account",
  "pgr.msg.future.reference": "Please use this for all your future references",
  "core.lbl.contact.information": "Contact Information",
  "pgr.lbl.receivingmode": "Receiving Mode",
  "pgr.lbl.receivingcenter": "Receiving Center",
  "core.error.required": "Required",
  "pgr.lbl.grievence.information": "Grievance Information",
  "pgr.lbl.top.griencetypes": "Select from Top Grievance types",
  "core.lbl.or": "OR",
  "core.lbl.moredetails": "More Details",
  "pgr.lbl.grievancedetails": "Grievance Details",
  "pgr.lbl.minmax.characters": "Minimum 10 and maximum 500 characters",
  "core.lbl.close": "Close",
  "pgr.lbl.grievance.location": "Grievance Location",
  "core.lbl.ok": "Ok",
  "core.msg.acknowledgement": "Acknowledgement",
  "core.title.egoverp": "eGov ERP",
  "core.lbl.signout": "Sign Out",
  "core.lbl.worklist": "Worklist",
  "core.lbl.drafts": "Drafts",
  "core.lbl.history": "History",
  "core.lbl.cancel": "Cancel",
  "core.lbl.resetclear": "Reset / Clear",
  "core.lbl.date": "Date",
  "core.lbl.sender": "Sender",
  "core.lbl.natureofwork": "Nature of Work",
  "core.lbl.status": "Status",
  "core.lbl.comments": "Comments",
  "core.title.citizenportal": "Citizen Portal",
  "core.lbl.inbox": "Inbox",
  "core.lbl.myaccount": "My Account",
  "core.lbl.newrequest": "New Request",
  "core.lbl.sortby": "Sort by",
  "core.lbl.recentmessages": "Recent Messages",
  "core.lbl.usermessages": "User Messages",
  "core.lbl.system.notifications": "System Notifications",
  "pgr.lbl.grievance.redressal": "Grievance Redressal",
  "pgr.lbl.register.grievance": "Register Grievance",
  "pgr.lbl.view.grievance": "View Grievance",
  "core.error": "Error!",
  "pgr.title.create.account": "Create an account",
  "core.lbl.enter.mobilenumber": "Please enter your valid 10 digit mobile number",
  "core.alert.agree.signup": "By doing sign up, you understood and agree to our Terms of use Privacy and security policies",
  "core.lbl.completed": "Completed",
  "core.account.created.successfully": "Your account created successfully",
  "core.otp.validation.failed": "OTP validation failed!",
  "pgr.lbl.grievance.date": "Grievance Date",
  "pgr.lbl.grievance.department": "Grievance Department",
  "pgr.lbl.nextescalation.date": "Next Escalation Date",
  "pgr.lbl.filedvia": "Filed via",
  "pgr.lbl.updatedby": "Updated By",
  "pgr.lbl.currentowner": "Current Owner/Officer Responsible",
  "pgr.lbl.grievance.history": "Grievance History",
  "pgr.lbl.actions": "Actions",
  "pgr.lbl.change.status": "Change Status",
  "pgr.lbl.change.grievancetype": "Change Grievance Type",
  "pgr.lbl.change.jurisdiction": "Change Jurisdiction",
  "pgr.lbl.forwardto": "Forward Grievance To",
  "core.lbl.include.message": "Include Message",
  "core.lbl.submit": "Submit",
  "pgr.lbl.search.grievance": "Search Grievance",
  "core.lbl.more": "More..",
  "core.lbl.less": "Less..",
  "core.lbl.search": "Search",
  "pgr.lbl.complaintnumber": "Complaint Number",
  "pgr.lbl.registered.date": "Registered Date",
  "core.msg.clickfor.demo": "Click for Demo",
  "core.error.valid.email": "Enter your valid email id!",
  "core.error.residential.address": "Enter your present residential address!",
  "pgr.error.select.grievance.categoryandtype": "Select your grievance from here or else choose it from below grievance category and grievance type!",
  "pgr.error.select.grievance.category": "Select your grievance category!",
  "pgr.error.select.grievance.type": "Select your grievance type!",
  "pgr.error.describe.grievance.details": "Describe your grievance details briefly!",
  "pgr.error.upload.photovideo": "Upload grievance relevated photo / video (Max : 3 files)!",
  "pgr.error.select.grievancelocation": "Enter your grievance location or click on the location icon to select your desired location from the map!",
  "pgr.error.landmark.optional": "Enter your landmark (if any)!",
  "pgr.msg.finalgrievance.submit": "Finally, Click here to submit your grievance!",
  "core.lbl.save": "Save",
  "core.lbl.setlanguage": "Set Language",
  "pgr.msg.complaint.moredetails": "Give more details about the complaint to help us solve your issue",
  "pgr.msg.creategrievance.avail.onlineservices": "Create an Grievance to avail our online services",
  "pgr.lbl.pending": "Pending",
  "core.msg.resolved": "Resolved",
  "core.msg.mark.resolved": "Mark resolved",
  "core.lbl.upload.image": "Upload Image",
  "core.lbl.location": "Location",
  "core.lbl.signin": "Sign In",
  "core.lbl.locale": "Select locale",
  "core.lbl.follow": "Follow us on",
  "core.lbl.forgot": "forgot?",
  "pgr.error.msg.number.required": "Grievance number is mandatory",
  "core.lbl.addmobilenumber/login": "Mobile number / Login ID",
  "core.error.incorrect.usename/password": "Username or Password is incorrect",
  "core.msg.terms": "Terms of use",
  "core.msg.policies": "Privacy & Security Policies",
  "core.msg.privacy.policy": "Privacy Policy",
  "core.msg.security.policy": "Security Policy",
  "core.lbl.email.compulsory": "Email ID",
  "pgr.lbl.grievance.category": "Grievance Category",
  "pgr.lbl.grievance.type": "Grievance Type",
  "pgr.lbl.grievance.location.icon": "Start typing your Grievance location or select it from location icon",
  "pgr.lbl.grievance.types": "Top Grievance Types",
  "core.lbl.email": "Email Id (Optional)",
  "core.lbl.grievance.photo/video": "Photos/Video",
  "pgr.lbl.grievance.update": "Update Grievance",
  "pgr.lbl.home.page": "Copyright",
  "core.msg.otp.notreceived": "Didn't receive OTP?",
  "core.error.password": "Use atleast 8 characters.Should contain upper and lower case alphabet, number and special character except [& < > # % \" ' / \\ and space]",
  "pgr.msg.sla.infomessage": "To ensure timely resolution of your complaint, we have defined \"Service Level Agreement - SLA\" for each complaint type. The estimation for this category is up to %d days",
  "pgr.0001": "latitude/longitude or cross hierarchy id is required",
  "pgr.0002": "latitude/longitude or cross hierarchy id is required",
  "pgr.0003": "latitude/longitude or cross hierarchy id is required",
  "pgr.0004": "Location id is required",
  "pgr.0005": "First name is required",
  "pgr.0006": "Phone is required",
  "pgr.0008": "User id is required",
  "pgr.0009": "Receiving mode is required",
  "pgr.0010": "Receiving center is required",
  "pgr.0011": "Tenant id is required",
  "pgr.0012": "Service code is required",
  "pgr.0013": "Description is required",
  "pgr.0014": "Service request id is required",
  "core.lbl.date.fromdate": "From Date",
  "core.lbl.date.todate": "To Date",
  "core.lbl.reset": "Reset",
  "core.lbl.add.name": "Name",
  "pgr.msg.success.grievanceupdated": "Grievance updated succesfully",
  "core.msg.criteria.required": "Atleast one search criteria is required",
  "core.error.fileformat.notallowed": "file format is not allowed",
  "pgr.error.notvalid.srn": "Not a valid SRN",
  "USER.USER_NAME_ALREADY_EXISTS": "User name already exists",
  "core-user.006": "Otp validation is pending.",
  "USER.USER_NOT_FOUND": "User not found",
  "core-user.001": "Gender is required",
  "core-user.002": "Type is required",
  "core-user.004": "Mobile number is required",
  "OTP.IDENTITY_MANDATORY": "Identity field is mandatory",
  "OTP.TENANT_ID_MANDATORY": "Tenant field is mandatory",
  "OTP.UUID_MANDATORY": "UUID field is mandatory",
  "OTP.OTP_MANDATORY": "Otp field is mandatory",
  "pgr.lbl.grievance.citizen": "My Grievances",
  "pgr.lbl.srn": "SRN(Service Request No.)",
  "core.msg.signup.agree": "By doing sign up, you understood and agree to our",
  "core.error.file.exceed": "File size exceeds 5MB limit",
  "core.lbl.add.comment": "Add Comment",
  "core.lbl.address.mandatory": "Address required",
  "pgr.msg.complaint.resolved": "Complaint resolved",
  "core.lbl.contact.us": "Contact",
  "core.lbl.dept": "Dept",
  "core.msg.work.done": "Done",
  "core.lbl.eGov": "eGovernments Foundation",
  "core.lbl.enter.OTP": "Enter OTP",
  "core.lbl.work.finish": "FINISH",
  "core.error.fullname.cantblank": "Full Name can't be blank",
  "core.lbl.letsgetstarted": "GET STARTED",
  "core.lbl.know.more": "Know More",
  "core.lbl.login/signup": "LogIn or SignUp",
  "core.lbl.logout": "Logout",
  "core.lbl.closenavigation": "Close navigation drawer",
  "core.lbl.opennavigation": "Open navigation drawer",
  "core.error.servicejuridiction.notfound": "service_code or jurisdiction_id provided were not found.",
  "core.error.generalservice": "service_code or jurisdiction_id was not provided or General service error.",
  "core.lbl.nxt": "NEXT",
  "core.error.user.notupdatable": "Not able to update user.",
  "core.msg.otp.sent.entertocreateaccount": "We have sent 4 digit otp number to your registered mobile number. Enter the OTP to create your account.",
  "core.error.notblank.password": "Password can't be blank",
  "core.error.notblank.phone": "Phone number can't be blank",
  "core.error.internet.tryagain": "Please check internet connection and try again",
  "core.msg.plse.wait": "Please Wait. . .",
  "core.lbl.poweredby": "Powered by",
  "core.lbl.profile": "Profile",
  "core.msg.enter.mobileno": "Enter Mobile Number",
  "core.msg.Resend": "RESEND",
  "pgr.all.complaints": "Complaints",
  "core.lbl.skip": "SKIP",
  "core.msg.status.update": "updated the status",
  "core.lbl.welcome": "WELCOME",
  "pgr.list.complaint.history": "Complaint History",
  "core.lbl.details": "Details",
  "core.msg.SLA.days.of": "SLA of %d Days",
  "core.msg.SLA.days.upto": "SLA upto %d days",
  "core.msg.month.day.year": "MM-dd-yyyy hh:mm:ss a",
  "pgr.lbl.complaint.sentto": "Complaint Sent to",
  "core.lbl.city.kurnool": "Kurnool",
  "core.lbl.home": "Home",
  "core.msg.more": "More.."
};

export default (state = defaultState, action) => {
    switch(action.type) {
        case 'LABELS':
            if(action && action.payload && action.payload.messages && action.payload.messages.length) {
                let _labels = {};
                for(let i=0; i<action.payload.messages.length; i++) {
                    _labels[action.payload.messages[i].code] = action.payload.messages[i].message;
                }
                return {
                    ...state,
                    ..._labels
                }
            } else {
                return {
                    ...state
                }
            }
        default:
            return state;
    }
}
