def app = "";
def commit_id="";
def module_name = "${env.JOB_NAME}".split("/")[-2];
def service_name = "${env.JOB_BASE_NAME}";
def path = "${module_name}/${service_name}"
def build_wkflo;
def ci_image = "egovio/ci:0.0.4"
def notifier = "";

try {
    node("slave"){
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id".trim()
        commit_id = readFile('.git/commit-id')
        code_builder = load("jenkins/code_builder.groovy")
        archiver = load("jenkins/archiver.groovy")
        notifier = load("jenkins/notifier.groovy")

        code_builder.build(path, ci_image)

        archiver.archiveArtifacts(["${path}/target/*.jar", "${path}/target/*.html"])
    }
} catch (e) {
    node{
        notifier.notifyBuild("FAILED")
        throw e
    }
}
