
Create table material( 
	id varchar(50),
	tenantId varchar(128),
	code varchar(50),
	name varchar(50),
	description varchar(1000),
	oldCode varchar(50),
	materialType varchar(50),
	baseUom varchar(50),
	inventoryType varchar(10),
	status varchar(9),
	purchaseUom varchar(50),
	expenseAccount varchar(50),
	minQuantity numeric (13,2),
	maxQuantity numeric (13,2),
	stockingUom varchar(50),
	materialClass varchar(11),
	reorderLevel numeric (13,2),
	reorderQuantity numeric (13,2),
	materialControlType varchar(18),
	model varchar(50),
	manufacturePartNo varchar(50),
	techincalSpecs varchar(50),
	termsOfDelivery varchar(50),
	overrideMaterialControlType boolean,
	scrapable boolean,
	createdby bigint,
		createdTime timestamp without time zone,
		lastmodifiedby bigint,
		lastModifiedTime timestamp without time zone,
		tenantId varchar(250),
			version bigint
);
alter table material add constraint pk_material primary key (code,tenantId);
create sequence seq_material;
