Create table egf_billregister(
	billType varchar(50) NOT NULL,
	billSubType varchar(50),
	billNumber varchar(50),
	billDate bigint NOT NULL,
	billAmount numeric (13,2) NOT NULL,
	passedAmount numeric (13,2),
	moduleName varchar(50),
	status varchar(50),
	fund varchar(50),
	function varchar(50),
	fundsource varchar(50),
	scheme varchar(50),
	subScheme varchar(50),
	functionary varchar(50),
	division varchar(50),
	department varchar(50),
	sourcePath varchar(50),
	budgetCheckRequired boolean,
	budgetAppropriationNo varchar(50),
	partyBillNumber varchar(50),
	partyBillDate bigint,
	description varchar(50),
	createdby varchar(50),
	createdtime bigint,
	lastmodifiedby varchar(50),
	lastmodifiedtime bigint,
	tenantId varchar(250),
	version bigint
);
alter table egf_billregister add constraint pk_egf_billregister primary key (billNumber,tenantId);
create sequence seq_egf_billregister;