Create table egf_billregister(
id varchar(50),
billType varchar(50) NOT NULL,
billSubType varchar(50),
billNumber varchar(50),
billDate date NOT NULL,
billAmount numeric (13,2) NOT NULL,
passedAmount numeric (13,2),
moduleName varchar(50),
statusId varchar(50),
fundId varchar(50),
functionId varchar(50),
fundsourceId varchar(50),
schemeId varchar(50),
subSchemeId varchar(50),
functionaryId varchar(50),
divisionId varchar(50),
departmentId varchar(50),
sourcePath varchar(50),
budgetCheckRequired boolean,
budgetAppropriationNo varchar(50),
partyBillNumber varchar(50),
partyBillDate date,
description varchar(50),
createdby varchar(50),
createddate timestamp without time zone,
lastmodifiedby varchar(50),
lastmodifieddate timestamp without time zone,
tenantId varchar(250),
version bigint
);
alter table egf_billregister add constraint pk_egf_billregister primary key (id);
create sequence seq_egf_billregister;