insert into eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid,enabled,grouped) values (nextval('seq_eg_wf_types'),NULL, 'Cancel Agreement', '/lams-web/app/search-agreement/view-renew-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Cancel Agreement', 0, 'default',true,true);


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'CANCEL AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Agreement', 'Advance Paid', NULL, NULL, 'Commissioner', 'CANCEL AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'CANCEL AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CANCEL AGREEMENT', 'END', 'END', NULL, NULL, NULL, NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CANCEL AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

