insert into eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, enabled, grouped, version, tenantid) values (nextval('seq_eg_wf_types'),NULL, 'Title Transfer', '/propertytax-web/view-title-transfer.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.ptis.models.Property', 'Title Transfer', true, false, 0, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Title Transfer', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'TITLE TRANSFER', 'Assistant Approved', 'Payament Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-04-01', '2099-03-31', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Title Transfer', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'TITLE TRANSFER', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Revenue Officer Approved', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Title Transfer', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'TITLE TRANSFER', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Print Notice', NULL, NULL, '2017-04-01', '2099-03-31', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Title Transfer', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'TITLE TRANSFER', 'END', 'END', NULL, NULL, NULL, NULL, NULL, '2017-04-01', '2099-03-31', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Title Transfer', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'TITLE TRANSFER', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-04-01', '2099-03-31', 'default');
