
---Deleting existing WF Matrix data

delete from eg_wf_matrix where objecttype in ('Renew Corporation Agreement','Renew Municipality Agreement');

-------RENEWAL AGREEMENT WF MATRIX

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'RENEWAL AGREEMENT', 'Assistant Approved', 'Payament Pending', 'UD Revenue Inspector,Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Assistant Approved', NULL, 'Payament Pending', 'UD Revenue Inspector', 'RENEWAL AGREEMENT', 'Advance Paid', 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'Advance Paid', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Assistant Approved', NULL, 'Payament Pending', 'Revenue Officer', 'RENEWAL AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

----UD RI verify

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Advance Paid', NULL, 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'RENEWAL AGREEMENT', 'UD Revenue Inspector Approved', NULL,'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','UD Revenue Inspector Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


----RO verify
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Advance Paid', NULL, 'Revenue Officer Approval Pending', 'Revenue Officer', 'RENEWAL AGREEMENT', 'Revenue Officer Approved', NULL,'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','Revenue Officer Approved','Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

--------UDRI Approved
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'RENEWAL AGREEMENT', 'Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'Assistant Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'RENEWAL AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'RENEWAL AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'RENEWAL AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'RENEWAL AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

------RO approved
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Revenue Officer Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'RENEWAL AGREEMENT', 'Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'Assistant Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Revenue Officer Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'RENEWAL AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Revenue Officer Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'RENEWAL AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Revenue Officer Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'RENEWAL AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Revenue Officer Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'RENEWAL AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

------------Asst.COMM
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'RENEWAL AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'RENEWAL AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'RENEWAL AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'RENEWAL AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


------------Zonal COMM
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'RENEWAL AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'RENEWAL AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'RENEWAL AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

-----Deputy COMM

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Deputy Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'RENEWAL AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Deputy Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'RENEWAL AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

-----Addtiional COMM

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Additional Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'RENEWAL AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

----Notice Print 

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Assistant Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'RENEWAL AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Zonal Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'RENEWAL AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Deputy Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'RENEWAL AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Additional Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'RENEWAL AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'RENEWAL AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

---Reject

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renewal LeaseAgreement', 'Rejected', NULL, 'Assistant Approval Pending', 'Senior Assistant, Junior Assistant', 'RENEWAL AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'UD Revenue Inspector,Revenue Officer', 'Assistant Approved', 'Forward,Cancel', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

