--------deleting existing WF matrix data

delete from eg_wf_matrix where objecttype in ('Create Municipality Agreement','Create Corporation Agreement');

-------CREATE NEW AGREEMENT WF MATRIX

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'CREATE AGREEMENT', 'Assistant Approved', 'Payament Pending', 'UD Revenue Inspector,Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Assistant Approved', NULL, 'Payament Pending', 'UD Revenue Inspector', 'CREATE AGREEMENT', 'Advance Paid', 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'Advance Paid', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Assistant Approved', NULL, 'Payament Pending', 'Revenue Officer', 'CREATE AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

----UD RI verify

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Advance Paid', NULL, 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'CREATE AGREEMENT', 'UD Revenue Inspector Approved', NULL,'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','UD Revenue Inspector Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


----RO verify
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Advance Paid', NULL, 'Revenue Officer Approval Pending', 'Revenue Officer', 'CREATE AGREEMENT', 'Revenue Officer Approved', NULL,'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','Revenue Officer Approved','Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

--------UDRI Approved
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'CREATE AGREEMENT', 'Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'Assistant Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'CREATE AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CREATE AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CREATE AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CREATE AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

------RO approved
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Revenue Officer Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'CREATE AGREEMENT', 'Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'Assistant Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Revenue Officer Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'CREATE AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Revenue Officer Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CREATE AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Revenue Officer Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CREATE AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Revenue Officer Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CREATE AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

------------Asst.COMM
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'CREATE AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CREATE AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CREATE AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CREATE AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


------------Zonal COMM
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CREATE AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CREATE AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CREATE AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

-----Deputy COMM

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Deputy Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CREATE AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Deputy Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CREATE AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

-----Additional COMM

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Additional Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CREATE AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

----Notice Print 

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Assistant Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CREATE AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Zonal Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CREATE AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Deputy Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CREATE AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Additional Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CREATE AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CREATE AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

---Reject

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'New LeaseAgreement', 'Rejected', NULL, 'Assistant Approval Pending', 'Senior Assistant, Junior Assistant', 'CREATE AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'UD Revenue Inspector,Revenue Officer', 'Assistant Approved', 'Forward,Cancel', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

