delete from eg_wf_matrix where objecttype='New Trade License' and tenantId='default';

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'New Trade License', 'NEW', NULL, NULL, null, null, 'Pending For Application processing', 'Junior Assistant Approval Pending', 'Junior Assistant', 'Pending For Application processing', NULL, NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate,tenantId) VALUES (nextval('SEQ_EG_WF_MATRIX'), 'ANY', 'New Trade License','Pending For Application processing', 'Application Fee paid', NULL, 'Junior Assistant', NULL, 'Pending For Field Inspection', 'SI/MHO/SS Approval Pending', 'Sanitary Inspector,Municipal Health Officer,Sanitary Supervisor', 'Scrutiny Completed', 'Forward,Reject', NULL, NULL, '2016-01-01', '2099-04-01','default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate,tenantId) VALUES (nextval('SEQ_EG_WF_MATRIX'), 'ANY', 'New Trade License', 'Pending For Field Inspection', NULL, NULL, 'Sanitary Inspector,Municipal Health Officer,Sanitary Supervisor', NULL, 'SI/MHO/SS Approved', 'Commissioner Approval pending', 'Commissioner', 'Inspection Completed', 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01','default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate,tenantId) VALUES (nextval('SEQ_EG_WF_MATRIX'), 'ANY', 'New Trade License', 'SI/MHO/SS Approved', NULL, NULL, 'Commissioner', NULL,'Commissioner Approved', 'Pending For License Fee Collection', 'Junior Assistant', 'License Fee Paid', 'Approve,Reject', NULL, NULL, '2016-01-01', '2099-04-01','default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate,tenantId) VALUES (nextval('SEQ_EG_WF_MATRIX'), 'ANY', 'New Trade License', 'Commissioner Approved', 'License Fee Paid', NULL, 'Junior Assistant', NULL,'License Fee Paid', 'Print Certificate Pending', 'Junior Assistant', 'License Issued', NULL, NULL, NULL, '2016-01-01', '2099-04-01','default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate,tenantId) VALUES (nextval('SEQ_EG_WF_MATRIX'), 'ANY', 'New Trade License', 'License Fee Paid', NULL, NULL, 'Junior Assistant', NULL,'END', 'END', NULL, NULL, 'Print Certificate', NULL, NULL, '2016-01-01', '2099-04-01','default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'New Trade License', 'Rejected', NULL, NULL, null, null, 'Pending For Application processing', 'Junior Assistant Approval Pending', 'Junior Assistant', 'Pending For Application processing', NULL, NULL, NULL, '2017-01-01', '2099-04-01', 'default');
