
------Deleting existing WF Matrix data

delete from eg_wf_matrix where objecttype in ('Cancel Corporation Agreement','Cancel Municipality Agreement');

----Agreement Cancellation WF Matrix

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'CANCELLATION AGREEMENT', 'Assistant Approved', NULL, 'UD Revenue Inspector,Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');
 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'Assistant Approved', NULL, 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'CANCELLATION AGREEMENT', 'UD Revenue Inspector Approved', NULL, 'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'UD Revenue Inspector Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'Assistant Approved', NULL, 'Revenue Officer Approval Pending', 'Revenue Officer', 'CANCELLATION AGREEMENT', 'Revenue Officer Approved', NULL, 'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

--------------UD RI
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'CANCELLATION AGREEMENT', 'Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'Assistant Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'CANCELLATION AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CANCELLATION AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CANCELLATION AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'UD Revenue Inspector Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CANCELLATION AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

--------------RO 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'Revenue Officer Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'CANCELLATION AGREEMENT', 'Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner', 'Assistant Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'Revenue Officer Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'CANCELLATION AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'Revenue Officer Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CANCELLATION AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'Revenue Officer Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CANCELLATION AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved', 'Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancellation LeaseAgreement', 'Revenue Officer Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CANCELLATION AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  1,now(),1,now(), NULL, 'default');

------------Asst.COMM
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'CANCELLATION AGREEMENT', 'Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner', 'Zonal Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CANCELLATION AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CANCELLATION AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Assistant Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CANCELLATION AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


------------Zonal COMM
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'CANCELLATION AGREEMENT', 'Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner', 'Deputy Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CANCELLATION AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Zonal Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CANCELLATION AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

-----Deputy COMM

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Deputy Commissioner Forwarded', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'CANCELLATION AGREEMENT', 'Additional Commissioner Approved', NULL, 'Commissioner', 'Additional Commissioner Approved','Forward,Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Deputy Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CANCELLATION AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

-----Addtiional COMM

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Addtiional Commissioner Forwarded', NULL, 'Commissioner Approval Pending', 'Commissioner', 'CANCELLATION AGREEMENT', 'Commissioner Approved', NULL, NULL, 'Commissioner Approved','Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

----Notice Print 

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Assistant Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CANCELLATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Zonal Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CANCELLATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Deputy Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CANCELLATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Additional Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CANCELLATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Commissioner Approved', NULL, 'Notice Print Pending', 'Senior Assistant, Junior Assistant', 'CANCELLATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');


---Reject

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Cancellation LeaseAgreement', 'Rejected', NULL, 'Assistant Approval Pending', 'Senior Assistant, Junior Assistant', 'CANCELLATION AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'UD Revenue Inspector,Revenue Officer', 'Assistant Approved', 'Forward,Cancel', NULL, NULL, '2017-01-01', '2099-04-01', 1,now(),1,now(), NULL, 'default');

