delete from eg_wf_matrix where objecttype = 'AbstractEstimate' and tenantid = 'default';
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, NULL, 'Clerk', NULL, 'CREATED', 'Pending Check', 'HOD,Junior Engineer', 'CREATED', 'Forward', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'CREATED', NULL, 'Pending Check', 'HOD,Junior Engineer', NULL, 'CHECKED', 'Pending Financial Sanction', 'Accountant', 'CHECKED', 'Submit,Reject', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'CHECKED', NULL, 'Pending Financial Sanction', 'Accountant', NULL, 'FINANCIAL_SANCTIONED', 'Pending Admin Sanction', 'Chief Officer', NULL, 'Submit,Reject', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'FINANCIAL_SANCTIONED', NULL, 'Pending Admin Sanction', 'Chief Officer', NULL, 'ADMIN_SANCTIONED', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'REJECTED', NULL, 'Pending Submission', 'Clerk', NULL, 'RESUBMITTED', 'Pending Check', 'HOD,Junior Engineer', 'RESUBMITTED', 'Forward,Cancel', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'RESUBMITTED', NULL, 'Pending Check', 'HOD,Junior Engineer', NULL, 'CHECKED', 'Pending Financial Sanction', 'Accountant', 'CHECKED', 'Submit,Reject', 0, NULL, now(), now(), 'default');

delete from eg_wf_matrix where objecttype = 'DetailedEstimate' and tenantid = 'default';
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'DetailedEstimate', 'NEW', NULL, NULL, 'Clerk', NULL, 'CREATED', 'Pending Check', 'HOD,Junior Engineer', 'CREATED', 'Forward', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'DetailedEstimate', 'CREATED', NULL, 'Pending Check', 'HOD,Junior Engineer', NULL, 'CHECKED', 'Pending Technical Sanction', 'Chief Officer', 'CHECKED', 'Submit,Reject', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'DetailedEstimate', 'CHECKED', NULL, 'Pending Technical Sanction', 'Chief Officer', NULL, 'TECHNICAL_SANCTIONED', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'DetailedEstimate', 'REJECTED', NULL, 'Pending Submission', 'Clerk', NULL, 'RESUBMITTED', 'Pending Check', 'HOD,Junior Engineer', 'RESUBMITTED', 'Forward,Cancel', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'DetailedEstimate', 'RESUBMITTED', NULL, 'Pending Check', 'HOD,Junior Engineer', NULL, 'CHECKED', 'Pending Technical Sanction', 'Chief Officer', 'CHECKED', 'Submit,Reject', 0, NULL, now(), now(), 'default');

delete from eg_wf_matrix where objecttype = 'SpilloverAbstractEstimate' and tenantid = 'default';
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverAbstractEstimate', 'NEW', NULL, NULL, 'Clerk', NULL, 'CREATED', 'Pending Admin Sanction', 'Chief Officer', 'CREATED', 'Forward', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverAbstractEstimate', 'CREATED', NULL, 'Pending Admin Sanction', 'Chief Officer', NULL, 'ADMIN_SANCTIONED', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverAbstractEstimate', 'REJECTED', NULL, 'Pending Submission', 'Clerk', NULL, 'RESUBMITTED', 'Pending Admin Sanction', 'Chief Officer', 'RESUBMITTED', 'Forward,Cancel', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverAbstractEstimate', 'RESUBMITTED', NULL, 'Pending Admin Sanction', 'Chief Officer', NULL, 'ADMIN_SANCTIONED', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now(), 'default');

delete from eg_wf_matrix where objecttype = 'SpilloverDetailedEstimate' and tenantid = 'default';
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverDetailedEstimate', 'NEW', NULL, NULL, NULL, NULL, 'CREATED', 'Pending Technical Sanction', NULL, 'CREATED', 'Forward', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverDetailedEstimate', 'CREATED', NULL, 'Pending Technical Sanction', NULL, NULL, 'TECHNICAL_SANCTIONED', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverDetailedEstimate', 'REJECTED', NULL, 'Pending Submission', 'Clerk', NULL, 'RESUBMITTED', 'Pending Technical Sanction', 'Chief Officer', 'RESUBMITTED', 'Forward,Cancel', 0, NULL, now(), now(), 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'SpilloverDetailedEstimate', 'RESUBMITTED', NULL, 'Pending Technical Sanction', 'Chief Officer', NULL, 'TECHNICAL_SANCTIONED', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now(), 'default');