CREATE TABLE egw_abstractestimate
(
  id character varying(256),
  tenantId character varying(256) NOT NULL,
  abstractestimatenumber character varying(20),
  subject character varying(100) NOT NULL,
  fund character varying(50),
  referencetype character varying(128),
  referencenumber character varying(100) NOT NULL,
  function character varying(50),
  description character varying(1024) NOT NULL,
  budgethead character varying(50),
  scheme character varying(50),
  subscheme character varying(50),
  dateofproposal bigint NOT NULL,
  department character varying(50) NOT NULL,
  adminsanctionnumber character varying(50),
  adminsanctiondate bigint,
  adminsanctionby character varying(50),
  status character varying(50) NOT NULL,
  beneficiary character varying(100) NOT NULL,
  modeofallotment character varying(100) NOT NULL,
  typeofwork character varying(50) NOT NULL,
  natureofwork character varying(50) NOT NULL,
  subtypeofwork character varying(50),
  ward character varying(50) NOT NULL,
  technicalsanctionnumber character varying(50),
  technicalsanctiondate bigint,
  technicalsanctionby character varying(50),
  locality character varying(50),
  workcategory character varying(100) NOT NULL,
  councilresolutionnumber character varying(100),
  councilresolutiondate bigint,
  workordercreated boolean DEFAULT false,
  billscreated boolean DEFAULT false,
  spilloverflag boolean DEFAULT false,
  cancellationreason character varying(512),
  cancellationremarks character varying(512),
  detailedEstimateCreated boolean DEFAULT false,
  stateId character varying(50),
  asset character varying(50),
  implementationPeriod bigint,
  fundAvailable boolean DEFAULT false,
  fundSanctioningAuthority character varying(50),
  pmcRequired boolean DEFAULT false,
  pmcType character varying(50),
  pmcName character varying(50),
  createdby character varying(256) NOT NULL,
  createdtime bigint NOT NULL,
  lastmodifiedby character varying(256),
  lastmodifiedtime bigint,
  CONSTRAINT estimate_pkey PRIMARY  KEY(id,tenantId),
  CONSTRAINT tenantid_abstractestimatenumber_unique UNIQUE (tenantId, abstractestimatenumber)
  );


CREATE TABLE egw_abstractestimate_details
(
  id character varying(256),
  tenantId character varying(256) NOT NULL,
  abstractEstimate character varying(50),
  nameofwork character varying(1024) NOT NULL,
  estimateamount double precision NOT NULL,
  estimatenumber character varying(50) NOT NULL,
  createdby character varying(256) NOT NULL,
  createdtime bigint NOT NULL,
  lastmodifiedby character varying(256),
  lastmodifiedtime bigint,
  grossAmountBilled double precision,
  projectCode character varying(50),
  CONSTRAINT estimate_details_pkey PRIMARY KEY(id,tenantId),
  CONSTRAINT tenantid_estimatenumber_unique UNIQUE (tenantId, estimatenumber)
);

CREATE TABLE egw_projectcode
(
  id character varying(256),
  tenantId character varying(256) NOT NULL,
  code character varying(100) NOT NULL,
  description character varying(1024),
  name character varying(100),
  status character varying(50),
  active boolean NOT NULL,
  completionDate bigint,
  projectValue double precision DEFAULT 0,
  createdby character varying(256) NOT NULL,
  createdtime bigint NOT NULL,
  lastmodifiedby character varying(256),
  lastmodifiedtime bigint,
  CONSTRAINT projectcode_pkey PRIMARY KEY(id,tenantId),
  CONSTRAINT tenantid_code_unique UNIQUE (tenantId, code)
);
