ALTER TABLE egpt_mstr_factor ALTER COLUMN fromdate TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE egpt_mstr_factor ALTER COLUMN todate TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE egpt_mstr_guidancevalue  ALTER COLUMN fromdate TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE egpt_mstr_guidancevalue ALTER COLUMN todate TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE egpt_mstr_taxrates ALTER COLUMN fromdate TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE egpt_mstr_taxrates ALTER COLUMN todate TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE egpt_mstr_taxperiods ALTER COLUMN fromdate TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE egpt_mstr_taxperiods ALTER COLUMN todate TYPE TIMESTAMP WITHOUT TIME ZONE;