INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (1, 'Complaint Cell', true, 8, 0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (2, 'Mayor/Chairperson Office', true, 2,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (3, 'Zonal Office', true, 7,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (4, 'Commissioner Office', true, 6,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (5, 'CM Office', true, 1,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (6,'Field visits',true,9,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (7,'Adverse Items(Paper/news)',true,10,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (8,'Public Representatives',true,3,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (9,'Office of CDMA',true,4,0);
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version) VALUES (10,'Office of RDMA',true,5,0);