INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (1, 'Complaint Cell', true, 8, 0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (2, 'Mayor/Chairperson Office', true, 2,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (3, 'Zonal Office', true, 7,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (4, 'Commissioner Office', true, 6,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (5, 'CM Office', true, 1,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (6,'Field visits',true,9,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (7,'Adverse Items(Paper/news)',true,10,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (8,'Public Representatives',true,3,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (9,'Office of CDMA',true,4,0, 'ap.public');
INSERT INTO egpgr_receiving_center (id, name, iscrnrequired, orderno, version, tenantid) VALUES (10,'Office of RDMA',true,5,0, 'ap.public');