/*
 * Marriage Registration APIs
 * APIs for Marriage registration for citizens are listed here.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swaminathan.s@riflexions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.egov.mr.model;

import org.springframework.stereotype.Component;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Component
@Builder
public class ReceiptAccountDetail {
	
  private String glCode;

  private String function;

  private String functionName;

  private Double drAmount;

  private Double crAmount;

  private String orderNo;

  private Boolean isRevenueAccount;

  private String accountDescription;

  private String purpose;

  private String accountName;

  private String financialYear;

	private Double creditAmountToBePaid;
}

