package pages;

import org.apache.commons.lang.math.RandomUtils;
import org.json.JSONObject;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Random;
import java.util.concurrent.TimeUnit;

import static com.jayway.awaitility.Awaitility.await;

public class GenericPage extends BasePage {

    private WebDriver driver;

    public GenericPage(WebDriver driver) {
        this.driver = driver;
    }

    public String checkValueCanBeAutoGeneratedOrNot(String v) {
        String value = v.replaceAll("\"", "");
        if (value.contains("--")) {
            if (value.contains(",") && !value.contains("characters")) {
                value = value.split(",")[0] +
                        getRandomNumber(Integer.parseInt(value.split(",")[1].replaceAll("[^0-9]+", "")));
            } else if (value.contains("characters")) {
                value = value.split(",")[0] +
                        getRandomCharacters(Integer.parseInt(value.split(",")[1].replaceAll("[^0-9]+", "")));
            } else if (value.contains("email")) {
                value = getRandomEmail();
            } else {
                value = getRandomNumber(Integer.parseInt(value.replaceAll("[^0-9]+", "")));
            }
        }
        return value.replaceAll("-", "");
    }

    private String getRandomNumber(int c) {
        int a = (int) Math.pow(10, c - 1);
        int b = (int) Math.pow(10, c) - 1;
        return String.valueOf(a + RandomUtils.nextInt(b));
    }

    private String getRandomCharacters(int noOfCharacters) {
        Random random = new Random();
        String[] alphabet = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", " ", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
        String required = "";

        for (int i = 0; i < noOfCharacters; i++) {
            required = required + alphabet[random.nextInt(27 - 0) + 0];
        }

        return required;
    }

    private String getRandomEmail() {
        return "email" + String.valueOf(100 + (RandomUtils.nextInt(9999))) + "@gmail.com";
    }

    public WebElement buildElement(String screen, String element, String value) throws IOException {
        WebElement webElement = null;
        String path = "src/test/resources/elements/Egov/" + screen + ".elements";
        BufferedReader in = new BufferedReader(new FileReader(path));
        String str = "";
        StringBuilder json = new StringBuilder();

        while ((str = in.readLine()) != null) {
            json.append(str);
        }
        in.close();

        JSONObject jsonObject = new JSONObject(json.toString());
        int pos = 0;

        for (int i = 0; i < jsonObject.getJSONArray("elements").length(); i++) {
            if ((jsonObject.getJSONArray("elements").getJSONObject(pos).getString("elementName").equals(element)))
                break;
            else pos++;
        }

        if (jsonObject.getJSONArray("elements").getJSONObject(pos).getString("value").contains("%s")) {
            String locator = jsonObject.getJSONArray("elements").getJSONObject(pos).getString("value");
            jsonObject.getJSONArray("elements").getJSONObject(pos).put("value", locator.replace("%s", value));
        }

        str = jsonObject.getJSONArray("elements").getJSONObject(pos).getString("value");
        switch (jsonObject.getJSONArray("elements").getJSONObject(pos).getString("identifier")) {
            case "id":
                waitForTheElementToBePresent((By.id(str)));
                webElement = driver.findElement(By.id(str));
                break;

            case "css":
                waitForTheElementToBePresent((By.cssSelector(str)));
                webElement = driver.findElement(By.cssSelector(str));
                break;

            case "xpath":
                waitForTheElementToBePresent((By.xpath(str)));
                webElement = driver.findElement(By.xpath(str));
                break;

            case "linkText":
                waitForTheElementToBePresent((By.linkText(str)));
                webElement = driver.findElement(By.linkText(str));
                break;

            case "className":
                waitForTheElementToBePresent((By.className(str)));
                webElement = driver.findElement(By.className(str));
                break;

            case "name":
                waitForTheElementToBePresent((By.name(str)));
                webElement = driver.findElement(By.name(str));
                break;

            case "tagName":
                waitForTheElementToBePresent((By.tagName(str)));
                webElement = driver.findElement(By.tagName(str));
                break;

            case "partialLinkText":
                waitForTheElementToBePresent((By.partialLinkText(str)));
                webElement = driver.findElement(By.partialLinkText(str));
                break;
        }
        return webElement;
    }

    public void clickOnDropdown(WebElement webElement, String value) {

        do {
            clickOnButton(webElement, driver);
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
//            waitForElementToBeVisible(driver.findElement(By.cssSelector("div[role=presentation]:nth-child(1)")), driver);
//            WebElement scroll = driver.findElement(By.cssSelector("div[role=presentation]:nth-child(1)"));
//            ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView();", scroll);

            String element = "//*[text()='" + value + "']";
            WebElement element1 = driver.findElement(By.xpath(element));
            clickOnButton(element1, driver);
        } while (!(value.equals(driver.findElement(By.xpath("//*[text()='" + value + "']")).getText())));
    }

    public void actionOnSuggestionBox(WebElement webElement, String value) {
        waitForElementToBeVisible(webElement, driver);
        webElement.sendKeys(value);
        webElement.sendKeys(Keys.ARROW_DOWN, Keys.ENTER);
    }

    public WebElement openApplication(String number) throws IOException {

        List<WebElement> totalRows;
        totalRows = buildElement("Home","dashBoardApplications","").findElements(By.tagName("tr"));
        try {
            for (WebElement applicationRow : totalRows) {
                if (applicationRow.findElements(By.tagName("td")).get(4).getText().contains(number)) {
                    return applicationRow;
                }
            }
        }catch (Exception e){}
        throw new RuntimeException("No application row found in Inbox -- " + number);
    }

    public void waitForTheElementToBePresent(By by) throws IOException {
        await().atMost(20, TimeUnit.SECONDS).until(() -> driver.findElements(by).size() > 0);
    }
}
