/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorRes;
import io.swagger.model.IndentNoteRequest;
import io.swagger.model.IndentNoteResponse;
import io.swagger.model.RequestInfo;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;

import java.util.List;
import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-10-28T13:21:55.964+05:30")

@Api(value = "indentnotes", description = "the indentnotes API")
public interface IndentnotesApi {

    @ApiOperation(value = "Create new Indent Note", nickname = "indentnotesCreatePost", notes = "Create new Indent Note", response = IndentNoteResponse.class, tags={ "Inventory","IndentNote", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Indent Note created Successfully", response = IndentNoteResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/indentnotes/_create",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<IndentNoteResponse> indentnotesCreatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Create new Indent Notes"  )  @Valid @RequestBody IndentNoteRequest indentNoteRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Get the list of Indent Notes", nickname = "indentnotesSearchPost", notes = "This API is used to search the indent notes raised in the system. There are 2 types of indents i.e., Indent Note (that is )raised by individual to request material(s) from store) and Transfer Indent(raised by store to request material(s) from other store)", response = IndentNoteResponse.class, tags={ "Inventory","IndentNote", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Indent Note retrieved Successfully", response = IndentNoteResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/indentnotes/_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<IndentNoteResponse> indentnotesSearchPost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Parameter to carry Request metadata in the request body"  )  @Valid @RequestBody RequestInfo requestInfo, @Size(max=50)@ApiParam(value = "comma seperated list of Ids") @Valid @RequestParam(value = "ids", required = false) List<String> ids,@ApiParam(value = "indent of the Indent Note ") @Valid @RequestParam(value = "indent", required = false) Long indent,@ApiParam(value = "indent store of the Indent Note ") @Valid @RequestParam(value = "indentStore", required = false) Long indentStore,@ApiParam(value = "inventory Type of the Indent Note  ") @Valid @RequestParam(value = "inventoryType", required = false) String inventoryType,@ApiParam(value = "state id of the Indent Note ") @Valid @RequestParam(value = "stateId", required = false) Long stateId,@ApiParam(value = "pageSize") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "offset") @Valid @RequestParam(value = "offset", required = false) Integer offset,@ApiParam(value = "This takes any field from the Object seperated by comma and asc,desc keywords.   example name asc,code desc or name,code or name,code desc  ") @Valid @RequestParam(value = "sortBy", required = false) String sortBy, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Update Indent Notes", nickname = "indentnotesUpdatePost", notes = "Update Indent Notes", response = IndentNoteResponse.class, tags={ "Inventory","IndentNote", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Indent Note updated Successfully", response = IndentNoteResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/indentnotes/_update",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<IndentNoteResponse> indentnotesUpdatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "common Request info"  )  @Valid @RequestBody IndentNoteRequest indentNoteRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
