/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.ErrorRes;
import io.swagger.model.MaterialStoreMappingRequest;
import io.swagger.model.MaterialStoreMappingResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-02T16:27:56.269+05:30")

@Api(value = "materialstoremapping", description = "the materialstoremapping API")
public interface MaterialStoreMappingApi {

    @ApiOperation(value = "Create  new  material store mappings", nickname = "materialstoremappingCreatePost", notes = "Create  new  material store mappings", response = MaterialStoreMappingResponse.class, tags = {"MaterialStoreMappings",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Material Store Mapping created Successfully", response = MaterialStoreMappingResponse.class),
            @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class)})
    @RequestMapping(value = "/materialstoremapping/_create",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<MaterialStoreMappingResponse> materialstoremappingCreatePost(@NotNull @ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId, @ApiParam(value = "Create  new") @Valid @RequestBody MaterialStoreMappingRequest materialStoreMappingRequest, @RequestHeader(value = "Accept", required = false) String accept, BindingResult errors) throws Exception;


    @ApiOperation(value = "Update any of the materials", nickname = "materialstoremappingUpdatePost", notes = "Update any of the materials", response = MaterialStoreMappingResponse.class, tags = {"Material",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Material store mapping updated Successfully", response = MaterialStoreMappingResponse.class),
            @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class)})
    @RequestMapping(value = "/materialstoremapping/_update",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<MaterialStoreMappingResponse> materialstoremappingUpdatePost(@NotNull @ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId, @ApiParam(value = "common Request info") @Valid @RequestBody MaterialStoreMappingRequest materialStoreMappingRequest);

}
