/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorRes;
import io.swagger.model.PurchaseMaterialRequest;
import io.swagger.model.PurchaseMaterialResponse;
import io.swagger.model.RequestInfo;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;

import java.util.List;
import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-10-28T13:21:55.964+05:30")

@Api(value = "purchasematerials", description = "the purchasematerials API")
public interface PurchasematerialsApi {

    @ApiOperation(value = "Create  new  purchasematerials", nickname = "purchasematerialsCreatePost", notes = "Create  new purchasematerials", response = PurchaseMaterialResponse.class, tags={ "Inventory","PurchaseMaterial", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "PurchaseMaterial created Successfully", response = PurchaseMaterialResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/purchasematerials/_create",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PurchaseMaterialResponse> purchasematerialsCreatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Create  new"  )  @Valid @RequestBody PurchaseMaterialRequest purchaseMaterialRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Get the list of purchasematerials", nickname = "purchasematerialsSearchPost", notes = "purchasematerials", response = PurchaseMaterialResponse.class, tags={ "Inventory","PurchaseMaterial", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "PurchaseMaterial retrieved Successfully", response = PurchaseMaterialResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/purchasematerials/_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PurchaseMaterialResponse> purchasematerialsSearchPost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "Parameter to carry Request metadata in the request body"  )  @Valid @RequestBody RequestInfo requestInfo, @Size(max=50)@ApiParam(value = "comma seperated list of Ids") @Valid @RequestParam(value = "ids", required = false) List<String> ids,@ApiParam(value = "material of the PurchaseMaterial ") @Valid @RequestParam(value = "material", required = false) Long material,@ApiParam(value = "uom of the PurchaseMaterial ") @Valid @RequestParam(value = "uom", required = false) Long uom,@ApiParam(value = "order quantity of the PurchaseMaterial ") @Valid @RequestParam(value = "orderQuantity", required = false) Integer orderQuantity,@ApiParam(value = "remarks of the PurchaseMaterial ") @Valid @RequestParam(value = "remarks", required = false) String remarks,@ApiParam(value = "pageSize") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "offset") @Valid @RequestParam(value = "offset", required = false) Integer offset,@ApiParam(value = "This takes any field from the Object seperated by comma and asc,desc keywords.   example name asc,code desc or name,code or name,code desc  ") @Valid @RequestParam(value = "sortBy", required = false) String sortBy, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Update any of the purchasematerials", nickname = "purchasematerialsUpdatePost", notes = "Update any of the purchasematerials", response = PurchaseMaterialResponse.class, tags={ "Inventory","PurchaseMaterial", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "PurchaseMaterial updated Successfully", response = PurchaseMaterialResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    @RequestMapping(value = "/purchasematerials/_update",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PurchaseMaterialResponse> purchasematerialsUpdatePost( @NotNull@ApiParam(value = "Unique id for a tenant.", required = true) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,@ApiParam(value = "common Request info"  )  @Valid @RequestBody PurchaseMaterialRequest purchaseMaterialRequest, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
