/*
 * eGov suite of products aim to improve the internal efficiency,transparency,
 * accountability and the service delivery of the government  organizations.
 *
 *  Copyright (C) 2016  eGovernments Foundation
 *
 *  The updated version of eGov suite of products as by eGovernments Foundation
 *  is available at http://www.egovernments.org
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see http://www.gnu.org/licenses/ or
 *  http://www.gnu.org/licenses/gpl.html .
 *
 *  In addition to the terms of the GPL license to be adhered to in using this
 *  program, the following additional terms are to be complied with:
 *
 *      1) All versions of this program, verbatim or modified must carry this
 *         Legal Notice.
 *
 *      2) Any misrepresentation of the origin of the material is prohibited. It
 *         is required that all modified versions of this material be marked in
 *         reasonable ways as different from the original version.
 *
 *      3) This license does not grant any rights to any user of the program
 *         with regards to rights under trademark law for use of the trade names
 *         or trademarks of eGovernments Foundation.
 *
 *  In case of any queries, you can reach eGovernments Foundation at contact@egovernments.org.
 */

package org.egov.eis.repository.builder;

import static org.springframework.util.ObjectUtils.isEmpty;

import java.util.Map;

import org.egov.eis.config.ApplicationProperties;
import org.egov.eis.web.contract.PositionGetRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class PositionAssignmentQueryBuilder {

	private static final Logger logger = LoggerFactory.getLogger(PositionAssignmentQueryBuilder.class);

	@Autowired
	private ApplicationProperties applicationProperties;

	/**
	 * FIXME : Had to select fromDate along with id as the default selection order is fromDate DESC by default.
	 * The sorting logic will not work apart from order by id or fromDate because we can't use orderBy
	 * on the non-selected columns with DISTINCT, which will be problematic in any sort conditions.
	 * Also, we should not use the sorting logic in 2nd query, because then we may not get the desired result.
	 * As it'll then sort the limited result having ids generated by this query. Rather than sorting the actual
	 * data & limiting the records.
	 * So, find a better solution for this.
	 */
	private static final String BASE_QUERY = "SELECT DISTINCT positionId AS id, fromDate FROM egeis_assignment" +
			" WHERE employeeId = :employeeId AND tenantId = :tenantId";

	public String getQuery(Long employeeId, PositionGetRequest positionGetRequest, Map<String, Object> namedParameters) {
		StringBuilder selectQuery = new StringBuilder(BASE_QUERY);

		addWhereClause(employeeId, selectQuery, namedParameters, positionGetRequest);
		addOrderByClause(selectQuery, positionGetRequest);
		addPagingClause(selectQuery, namedParameters, positionGetRequest);

		logger.debug("Position Ids Query : " + selectQuery);
		return selectQuery.toString();
	}

	private void addWhereClause(Long employeeId, StringBuilder selectQuery, Map<String, Object> namedParameters,
								PositionGetRequest positionGetRequest) {

		namedParameters.put("employeeId", employeeId);
		namedParameters.put("tenantId", positionGetRequest.getTenantId());

		if (isEmpty(positionGetRequest.getId()) && isEmpty(positionGetRequest.getIsPrimary())
				&& isEmpty(positionGetRequest.getAsOnDate()) && isEmpty(positionGetRequest.getDesignationId())
				&& isEmpty(positionGetRequest.getDepartmentId()))
			return;

		if (!isEmpty(positionGetRequest.getId())) {
			selectQuery.append(" AND positionId IN (:ids)");
			namedParameters.put("ids", positionGetRequest.getId());
		}

		if (!isEmpty(positionGetRequest.getIsPrimary())) {
			selectQuery.append(" AND isPrimary = :isPrimary");
			namedParameters.put("isPrimary", positionGetRequest.getIsPrimary());
		}

		if (!isEmpty(positionGetRequest.getAsOnDate())) {
			selectQuery.append(" AND :asOnDate BETWEEN fromDate AND toDate");
			namedParameters.put("asOnDate", positionGetRequest.getAsOnDate());
		}

		if (!isEmpty(positionGetRequest.getDepartmentId())) {
			selectQuery.append(" AND departmentId = :departmentId");
			namedParameters.put("departmentId", positionGetRequest.getDepartmentId());
		}

		if (!isEmpty(positionGetRequest.getDesignationId())) {
			selectQuery.append(" AND designationId = :designationId");
			namedParameters.put("designationId", positionGetRequest.getDesignationId());
		}
	}

	private void addOrderByClause(StringBuilder selectQuery, PositionGetRequest positionGetRequest) {
		String sortBy = (isEmpty(positionGetRequest.getSortBy()) ? "fromDate" : positionGetRequest.getSortBy());
		String sortOrder = (isEmpty(positionGetRequest.getSortOrder()) ? "DESC" : positionGetRequest.getSortOrder());
		selectQuery.append(" ORDER BY " + sortBy + " " + sortOrder);
	}

	private void addPagingClause(StringBuilder selectQuery, Map<String, Object> preparedStatementValues,
								 PositionGetRequest positionGetRequest) {
		// handle limit(also called pageSize) here
		selectQuery.append(" LIMIT :pageSize");
		long pageSize = Integer.parseInt(applicationProperties.empSearchPageSizeDefault());
		if (!isEmpty(positionGetRequest.getPageSize()))
			pageSize = positionGetRequest.getPageSize();
		preparedStatementValues.put("pageSize", pageSize); // Set limit to pageSize

		// handle offset here
		selectQuery.append(" OFFSET :pageNumber");
		int pageNumber = 0; // Default pageNo is zero meaning first page
		if (!isEmpty(positionGetRequest.getPageNumber()))
			pageNumber = positionGetRequest.getPageNumber() - 1;
		preparedStatementValues.put("pageNumber", pageNumber * pageSize); // Set offset to pageNo * pageSize
	}
}
