title Create Voucher Process flow

Client->VoucherSvc: Create Voucher Request
activate Client
activate VoucherSvc
note over Client,VoucherSvc
            VoucherCreator posts a new create voucher request
end note
VoucherSvc->VoucherSvc : validation 
note over  VoucherSvc
    A. Request format validations like size of texts,allowed formats etc
    B. Validate Voucher
        1. Validated the total amount,subledger total
        2. Validate glcode active,function,fund etc
        3. Validate financial year for posting
end note
alt Validation failed
VoucherSvc->Client : throw Validation Error
else
VoucherSvc->+Kafka : Data put on Kafka Q with topic "voucher.validated"
VoucherSvc->Client :Acknowledge client with transaction number
deactivate Client
deactivate VoucherSvc
end
Kafka->+BudgetSvc : Business validation  Budget Check
note over  Kafka,BudgetSvc
   Do budget check based on application configuration 
   return Budget appropriation number or Budget check failure error
   end note  over
BudgetSvc->-Kafka : Budget check response is pushed to kafka with topic voucher_budget_check_completed
Kafka->+VoucherNoGenerator: VoucherNoGenerator picks voucher_budget_check_completed and generates vouchernumber  
VoucherNoGenerator->-Kafka : VoucherNoGenerator puts back the data to Kafka with topic "voucher.number.generated"
Kafka->+WorkflowSvc: WorkflowSvc picks and completes workflow
WorkflowSvc->-Kafka :WorkflowSvc puts back the data to Kafka  with topic "voucher.workflow.completed"
Kafka->+VoucherSvc : Data persisted on db with vouchernumber
VoucherSvc->-Kafka : VoucherSvc puts data back with Kafka  with topic "voucher.persisted"
Kafka->+VoucherIndexer : VoucherIndexer picks and uploads to Elastic search 

