update eg_wf_types set type='Renew Municipality Agreement' where type='Renew Agreement';
update eg_wf_types set type='Evict Municipality Agreement' where type='Evict Agreement';
update eg_wf_types set type='Cancel Municipality Agreement' where type='Cancel Agreement';

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid, enabled, grouped) 
values (nextval('seq_eg_wf_types'), 'Renew Corporation Agreement', '/lams-web/app/search-agreement/view-renew-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Renew Agreement', 0, 'default', true, true);

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid, enabled, grouped) 
values (nextval('seq_eg_wf_types'), 'Evict Corporation Agreement', '/lams-web/app/search-agreement/view-evict-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Evict Agreement', 0, 'default', true, true);

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid, enabled, grouped) 
values (nextval('seq_eg_wf_types'), 'Cancel Corporation Agreement', '/lams-web/app/search-agreement/view-cancel-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Cancel Agreement', 0, 'default', true, true);

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid, enabled, grouped) 
values (nextval('seq_eg_wf_types'), 'Objection Municipality Agreement', '/lams-web/app/search-agreement/view-objection-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Objection Agreement', 0, 'default', true, true);

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid, enabled, grouped) 
values (nextval('seq_eg_wf_types'), 'Objection Corporation Agreement', '/lams-web/app/search-agreement/view-objection-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Objection Agreement', 0, 'default', true, true);

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid, enabled, grouped) 
values (nextval('seq_eg_wf_types'), 'Judgement Municipality Agreement', '/lams-web/app/search-agreement/view-judgement-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Judgement Agreement', 0, 'default', true, true);

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid, enabled, grouped) 
values (nextval('seq_eg_wf_types'), 'Judgement Corporation Agreement', '/lams-web/app/search-agreement/view-judgement-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Judgement Agreement', 0, 'default', true, true);


delete from eg_wf_matrix where objecttype = 'Renew Agreement';
delete from eg_wf_matrix where objecttype = 'Evict Agreement';
delete from eg_wf_matrix where objecttype = 'Cancel Agreement';

--Renew Municipality Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Municipality Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'RENEW MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Payament Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Municipality Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'RENEW MUNICIPALITY AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Municipality Agreement', 'Advance Paid', NULL, NULL, 'Commissioner', 'RENEW MUNICIPALITY AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Municipality Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'RENEW MUNICIPALITY AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Municipality Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'RENEW MUNICIPALITY AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Municipality Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'RENEW MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');


--Renew Corporation Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'RENEW CORPORATION AGREEMENT', 'Assistant Approved', 'Payament Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'RENEW CORPORATION AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'Advance Paid', NULL, NULL, 'Revenue Officer', 'RENEW CORPORATION AGREEMENT', 'Revenue Officer Approved', 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'Revenue Officer Approved', NULL, NULL, 'Deputy Commissioner', 'RENEW CORPORATION AGREEMENT', 'Deputy Commissioner Approved', 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'Deputy Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'Deputy Commissioner Approved', NULL, NULL, 'Assistant Commissioner', 'RENEW CORPORATION AGREEMENT', 'Assistant Commissioner Approved', 'Commissioner Approval Pending', 'Commissioner', 'Assistant Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'Assistant Commissioner Approved', NULL, NULL, 'Commissioner', 'RENEW CORPORATION AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'RENEW CORPORATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Renew Corporation Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'RENEW CORPORATION AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');


--Evict Municipality Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Municipality Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'EVICT MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');
 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Municipality Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'EVICT MUNICIPALITY AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Municipality Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'EVICT MUNICIPALITY AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Municipality Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'EVICT MUNICIPALITY AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Municipality Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'EVICT MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');


--Evict Corporation Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Corporation Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'EVICT CORPORATION AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');
 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Corporation Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'EVICT CORPORATION AGREEMENT', 'Revenue Officer Approved', 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Corporation Agreement', 'Revenue Officer Approved', NULL, NULL, 'Deputy Commissioner', 'EVICT CORPORATION AGREEMENT', 'Deputy Commissioner Approved', 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'Deputy Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Corporation Agreement', 'Deputy Commissioner Approved', NULL, NULL, 'Assistant Commissioner', 'EVICT CORPORATION AGREEMENT', 'Assistant Commissioner Approved', 'Commissioner Approval Pending', 'Commissioner', 'Assistant Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Corporation Agreement', 'Assistant Commissioner Approved', NULL, NULL, 'Commissioner', 'EVICT CORPORATION AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Corporation Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'EVICT CORPORATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Corporation Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'EVICT CORPORATION AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');


--Cancel Municipality Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Municipality Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'CANCEL MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Municipality Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'CANCEL MUNICIPALITY AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Municipality Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'CANCEL MUNICIPALITY AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Municipality Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CANCEL MUNICIPALITY AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Municipality Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CANCEL MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');


--Cancel Corporation Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Corporation Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'CANCEL CORPORATION AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Corporation Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'CANCEL CORPORATION AGREEMENT', 'Revenue Officer Approved', 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Corporation Agreement', 'Revenue Officer Approved', NULL, NULL, 'Deputy Commissioner', 'CANCEL CORPORATION AGREEMENT', 'Deputy Commissioner Approved', 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'Deputy Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Corporation Agreement', 'Deputy Commissioner Approved', NULL, NULL, 'Assistant Commissioner', 'CANCEL CORPORATION AGREEMENT', 'Assistant Commissioner Approved', 'Commissioner Approval Pending', 'Commissioner', 'Assistant Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Corporation Agreement', 'Assistant Commissioner Approved', NULL, NULL, 'Commissioner', 'CANCEL CORPORATION AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Corporation Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CANCEL CORPORATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Cancel Corporation Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CANCEL CORPORATION AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');


--Objection Municipality Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Municipality Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'OBJECTION MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');
 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Municipality Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'OBJECTION MUNICIPALITY AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Municipality Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'OBJECTION MUNICIPALITY AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Municipality Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'OBJECTION MUNICIPALITY AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Municipality Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'OBJECTION MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');


--Objection Corporation Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Corporation Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'OBJECTION CORPORATION AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');
 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Corporation Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'OBJECTION CORPORATION AGREEMENT', 'Revenue Officer Approved', 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Corporation Agreement', 'Revenue Officer Approved', NULL, NULL, 'Deputy Commissioner', 'OBJECTION CORPORATION AGREEMENT', 'Deputy Commissioner Approved', 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'Deputy Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Corporation Agreement', 'Deputy Commissioner Approved', NULL, NULL, 'Assistant Commissioner', 'OBJECTION CORPORATION AGREEMENT', 'Assistant Commissioner Approved', 'Commissioner Approval Pending', 'Commissioner', 'Assistant Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Corporation Agreement', 'Assistant Commissioner Approved', NULL, NULL, 'Commissioner', 'OBJECTION CORPORATION AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Corporation Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'OBJECTION CORPORATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Objection Corporation Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'OBJECTION CORPORATION AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');


--Judgement Municipality Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Municipality Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'JUDGEMENT MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');
 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Municipality Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'JUDGEMENT MUNICIPALITY AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Municipality Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'JUDGEMENT MUNICIPALITY AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Municipality Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'JUDGEMENT MUNICIPALITY AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Municipality Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'JUDGEMENT MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');


--Judgement Corporation Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Corporation Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'JUDGEMENT CORPORATION AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');
 
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Corporation Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'JUDGEMENT CORPORATION AGREEMENT', 'Revenue Officer Approved', 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Corporation Agreement', 'Revenue Officer Approved', NULL, NULL, 'Deputy Commissioner', 'JUDGEMENT CORPORATION AGREEMENT', 'Deputy Commissioner Approved', 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'Deputy Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Corporation Agreement', 'Deputy Commissioner Approved', NULL, NULL, 'Assistant Commissioner', 'JUDGEMENT CORPORATION AGREEMENT', 'Assistant Commissioner Approved', 'Commissioner Approval Pending', 'Commissioner', 'Assistant Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Corporation Agreement', 'Assistant Commissioner Approved', NULL, NULL, 'Commissioner', 'JUDGEMENT CORPORATION AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Corporation Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'JUDGEMENT CORPORATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Judgement Corporation Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'JUDGEMENT CORPORATION AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01',  NULL, NULL, NULL, NULL, NULL, 'default');
