DELETE FROM eg_wf_types WHERE type = 'Renew Agreement';
DELETE FROM eg_wf_matrix WHERE objecttype = 'Renew Agreement';


insert into eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid,enabled,grouped) values (nextval('seq_eg_wf_types'),NULL, 'Evict Agreement', '/lams-web/app/search-agreement/view-evict-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Evict Agreement', 0, 'default',true,true);

insert into eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid,enabled,grouped) values (nextval('seq_eg_wf_types'),NULL, 'Renew Agreement', '/lams-web/app/search-agreement/view-renew-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Renew Agreement', 0, 'default',true,true);


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'EVICT AGREEMENT', 'Assistant Approved', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'EVICT AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'EVICT AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'EVICT AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Evict Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'EVICT AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Cancel', NULL, NULL, '2017-01-01', '2099-04-01', 'default');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'RENEW AGREEMENT', 'Assistant Approved', 'Payament Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'RENEW AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Agreement', 'Advance Paid', NULL, NULL, 'Commissioner', 'RENEW AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'RENEW AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'RENEW AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantId) VALUES (NEXTVAL('SEQ_EG_WF_MATRIX'), 'ANY', 'Renew Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'RENEW AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Cancel', NULL, NULL, '2017-01-01', '2099-04-01', 'default');
