
update eg_wf_types set type='Create Municipality Agreement' where type='Create Agreement';

insert into eg_wf_types (id, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid) 
values (nextval('seq_eg_wf_types'), 'Create Corporation Agreement', '/lams-web/app/search-agreement/view-renew-agreement.html?view=inbox&state=:ID', 1, now(), 1, now(), 'org.egov.lams.models.Agreement', 'Create Agreement', 0, 'default');

delete from eg_wf_matrix where objecttype = 'Create Agreement';

--Create Municipality Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Municipality Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'CREATE MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Payament Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Municipality Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'CREATE MUNICIPALITY AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Municipality Agreement', 'Advance Paid', NULL, NULL, 'Revenue Officer', 'CREATE MUNICIPALITY AGREEMENT', 'Revenue Officer Approved', 'Commissioner Approval Pending', 'Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Municipality Agreement', 'Revenue Officer Approved', NULL, NULL, 'Commissioner', 'CREATE MUNICIPALITY AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Municipality Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CREATE MUNICIPALITY AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Municipality Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CREATE MUNICIPALITY AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

--Create Corporation Agreement

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'NEW', NULL, NULL, 'Senior Assistant,Junior Assistant', 'CREATE CORPORATION AGREEMENT', 'Assistant Approved', 'Payament Pending', 'Revenue Officer', 'Assistant Approved', NULL, NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'Assistant Approved', NULL, NULL, 'Revenue Officer', 'CREATE CORPORATION AGREEMENT', 'Advance Paid', 'Revenue Officer Approval Pending', 'Revenue Officer', 'Advance Paid', 'Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'Advance Paid', NULL, NULL, 'Revenue Officer', 'CREATE CORPORATION AGREEMENT', 'Revenue Officer Approved', 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'Revenue Officer Approved', NULL, NULL, 'Deputy Commissioner', 'CREATE CORPORATION AGREEMENT', 'Deputy Commissioner Approved', 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'Deputy Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'Deputy Commissioner Approved', NULL, NULL, 'Assistant Commissioner', 'CREATE CORPORATION AGREEMENT', 'Assistant Commissioner Approved', 'Commissioner Approval Pending', 'Commissioner', 'Assistant Commissioner Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'Assistant Commissioner Approved', NULL, NULL, 'Commissioner', 'CREATE CORPORATION AGREEMENT', 'Commissioner Approved', 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'Commissioner Approved', 'Approve,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'Commissioner approved', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CREATE CORPORATION AGREEMENT', 'END', 'END', NULL, NULL, 'Print Notice', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'Create Corporation Agreement', 'Rejected', NULL, NULL, 'Senior Assistant, Junior Assistant', 'CREATE CORPORATION AGREEMENT', 'Assistant Approved', 'Assistant Approval Pending', 'Revenue Officer', 'Assistant Approved', 'Forward,Reject', NULL, NULL, '2017-01-01', '2099-04-01', NULL, NULL, NULL, NULL, NULL, 'default');
