-- Workflow matrix for Employee Transfer
Insert into eg_wf_types (id, module, type, link, enabled, grouped, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid) values (nextval('seq_eg_wf_types'),(select id from eg_module where name='Employee'), 'EmployeeTransfer', '/hr-web/app/hr/transfer/update-transfer.html?stateId=:ID', true, false, 1, now(), 1, now(), 'org.egov.eis.model.Movement', 'Create Employee Transfer', 0, 'default');

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeeTransfer', 'NEW', NULL, NULL, NULL, NULL, 'Applied', 'Pending Approval', NULL, 'Applied', 'Apply', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeeTransfer', 'Applied', NULL, 'Pending Approval', NULL, NULL, 'Approved', 'END', NULL, 'Approved', 'Approve,Reject', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeeTransfer', 'Rejected', NULL, NULL, NULL, NULL, 'Resubmitted', 'Pending Resubmission', NULL, 'Resubmitted', 'Submit,Cancel', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeeTransfer', 'Resubmitted', NULL, 'Pending Resubmission', NULL, NULL, 'Applied', 'Pending Approval', NULL, 'Applied', 'Approve,Reject', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeeTransfer', 'Approved', NULL, NULL, NULL, NULL, 'Approved', 'END', NULL, NULL, NULL, NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeeTransfer', 'Cancelled', NULL, NULL, NULL, NULL, 'Cancelled', 'END', NULL, NULL, NULL, NULL, NULL, now(), '2099-04-01', 'default');

-- Workflow matrix for Employee Promotion
Insert into eg_wf_types (id, module, type, link, enabled, grouped, createdby, createddate, lastmodifiedby, lastmodifieddate, typefqn, displayname, version, tenantid) values (nextval('seq_eg_wf_types'),(select id from eg_module where name='Employee'), 'EmployeePromotion', '/hr-web/app/hr/promotion/update-promotion.html?stateId=:ID', true, false, 1, now(), 1, now(), 'org.egov.eis.model.Movement', 'Create Employee Promotion', 0, 'default');

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeePromotion', 'NEW', NULL, NULL, NULL, NULL, 'Applied', 'Pending Approval', NULL, 'Applied', 'Apply', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeePromotion', 'Applied', NULL, 'Pending Approval', NULL, NULL, 'Approved', 'END', NULL, 'Approved', 'Approve,Reject', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeePromotion', 'Rejected', NULL, NULL, NULL, NULL, 'Resubmitted', 'Pending Resubmission', NULL, 'Resubmitted', 'Submit,Cancel', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeePromotion', 'Resubmitted', NULL, 'Pending Resubmission', NULL, NULL, 'Applied', 'Pending Approval', NULL, 'Applied', 'Approve,Reject', NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeePromotion', 'Approved', NULL, NULL, NULL, NULL, 'Approved', 'END', NULL, NULL, NULL, NULL, NULL, now(), '2099-04-01', 'default');
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, tenantid) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'EmployeePromotion', 'Cancelled', NULL, NULL, NULL, NULL, 'Cancelled', 'END', NULL, NULL, NULL, NULL, NULL, now(), '2099-04-01', 'default');