swagger: '2.0'

info:
  version: "1.0.0"
  title: Instrument Service
  description: Instrument services APIs - to create, update and search Instrument. 
  contact:
    name: Manikanta P T
    email: info@egovernments.org
  
basePath: "/egf-instrument/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egf-instrument/contracts/v1-0-0.yml'
x-api-id: 'org.egov.egf.instrument'
swagger: '2.0'

info:
  version: "1.0.0"
  title: Instrument Service
  description: Instrument services APIs - to create, update and search Instrument. 
  contact:
    name: Manikanta P T
    email: info@egovernments.org
  
basePath: "/egf-instrument/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egf-instrument/contracts/v1-0-0.yml'
x-api-id: 'org.egov.egf.instrument'
swagger: '2.0'

info:
  version: "1.0.0"
  title: Instrument Service
  description: Instrument services APIs - to create, update and search Instrument. 
  contact:
    name: Manikanta P T
    email: info@egovernments.org
  
basePath: "/egf-instrument/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egf-instrument/contracts/v1-0-0.yml'
x-api-id: 'org.egov.egf.instrument'
