/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.egov.inv.api;

import org.egov.inv.model.ErrorRes;
import org.egov.inv.model.OpeningBalanceRequest;
import org.egov.inv.model.OpeningBalanceResponse;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "org.egov.inv.codegen.languages.SpringCodegen", date = "2017-11-08T13:51:07.770Z")

@Api(value = "openingbalance", description = "the openingbalance API")
public interface OpeningbalanceApi {

    @ApiOperation(value = "Create New Opening Balanace.", notes = "Create a new  Opening Balanace. This will handle  Opening Balanace detail.", response = OpeningBalanceResponse.class, tags={ "Opening Balance", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Opening Balance Created", response = OpeningBalanceResponse.class),
        @ApiResponse(code = 400, message = "Invalid input.", response = ErrorRes.class) })
    
    @RequestMapping(value = "/openingbalance/_create",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<OpeningBalanceResponse> openingbalanceCreatePost(@ApiParam(value = "Details for the new Oening Balance request." ,required=true )  @Valid @RequestBody OpeningBalanceRequest openingBalance);


    @ApiOperation(value = "Update existing  Opening Balanace. This will handle  Opening Balanace detail.", notes = "Existing Opening Balanace can be updated.", response = OpeningBalanceResponse.class, tags={ "Opening Balance", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Opening Balance  Updated Successfully.", response = OpeningBalanceResponse.class),
        @ApiResponse(code = 400, message = "Invalid Input", response = ErrorRes.class) })
    
    @RequestMapping(value = "/openingbalance/_update",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<OpeningBalanceResponse> openingbalanceUpdatePost(@ApiParam(value = "Details for the new opening balance." ,required=true )  @Valid @RequestBody OpeningBalanceRequest openingBalanace);

}
