INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (77, 14, (select id from service_status where code = 'DSNEW'), 1, (select id from service_status where code = 'DSPROGRESS'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (78, 14, (select id from service_status where code = 'DSNEW'), 2, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (79, 14, (select id from service_status where code = 'DSNEW'), 3, (select id from service_status where code = 'DSREJECTED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (80, 14, (select id from service_status where code = 'DSPROGRESS'), 1, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (81, 14, (select id from service_status where code = 'DSPROGRESS'), 2, (select id from service_status where code = 'DSREJECTED'), 0,'default');

INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (82, 15, (select id from service_status where code = 'DSNEW'), 1, (select id from service_status where code = 'DSPROGRESS'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (83, 15, (select id from service_status where code = 'DSNEW'), 2, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (84, 15, (select id from service_status where code = 'DSNEW'), 3, (select id from service_status where code = 'DSREJECTED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (85, 15, (select id from service_status where code = 'DSPROGRESS'), 1, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (86, 15, (select id from service_status where code = 'DSPROGRESS'), 2, (select id from service_status where code = 'DSREJECTED'), 0,'default');

INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (87, 16, (select id from service_status where code = 'DSNEW'), 1, (select id from service_status where code = 'DSPROGRESS'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (88, 16, (select id from service_status where code = 'DSNEW'), 2, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (89, 16, (select id from service_status where code = 'DSNEW'), 3, (select id from service_status where code = 'DSREJECTED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (90, 16, (select id from service_status where code = 'DSNEW'), 1, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (91, 16, (select id from service_status where code = 'DSPROGRESS'), 2, (select id from service_status where code = 'DSREJECTED'), 0,'default');

INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (92, 17, (select id from service_status where code = 'DSNEW'), 1, (select id from service_status where code = 'DSPROGRESS'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (93, 17, (select id from service_status where code = 'DSNEW'), 2, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (94, 17, (select id from service_status where code = 'DSNEW'), 3, (select id from service_status where code = 'DSREJECTED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (95, 17, (select id from service_status where code = 'DSPROGRESS'), 1, (select id from service_status where code = 'DSAPPROVED'), 0,'default');
INSERT INTO egpgr_complaintstatus_mapping (id, role_id, current_status_id, orderno, show_status_id, version,tenantid) VALUES (96, 17, (select id from service_status where code = 'DSPROGRESS'), 2, (select id from service_status where code = 'DSREJECTED'), 0,'default');

