// filters
export const FROM_DATE_FILTER = "FROM_DATE_FILTER";
export const TO_DATE_FILTER = "TO_DATE_FILTER";
export const JOBS_STATUS_FILTER = "APPLY_JOBS_STAUTS_FILTER";
export const JOB_CODE_FITLER = "JOB_CODE_FITLER";
// user jobs
export const INITIATE_USER_JOBS_FETCH = "INITIATE_USER_JOBS_FETCH";
export const FETCH_USER_JOBS_SUCCESS = "FETCH_USER_JOBS_SUCCESS";
export const FETCH_USER_JOBS_FAILURE = "FETCH_USER_JOBS_FAILURE";
export const FILTER_USER_JOBS = "FILTER_USER_JOBS";
// create job
export const INITIATE_JOB_CREATE = "INITIATE_JOB_CREATE";
export const JOB_CREATE_SUCCESS = "JOB_CREATE_SUCCESS";
export const JOB_CREATE_FAILED = "JOB_CREATE_FAILED";
// upload definitions
export const INITIATE_UPLOAD_DEFINITIONS_FETCH =
  "INITIATE_UPLOAD_DEFINITIONS_FETCH";
export const UPLOAD_DEFINTIONS_RECEIVED = "UPLOAD_DEFINTIONS_RECEIVED";
export const FETCH_UPLOAD_DEFINITIONS_FAILURE =
  "FETCH_UPLOAD_DEFINITIONS_FAILURE";
// selected module and file types
export const MODULE_SELECTED = "MODULE_SELECTED";
export const MOUDULE_DEFINITION_SELECTED = "MOUDULE_DEFINITION_SELECTED";
//file select action
export const FILE_SELECTED = "FILE_SELECTED";
