SELECT setval('seq_egeis_designation', nextval('seq_egeis_designation'), true);

INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant Examiner of Accounts', 'AEOA', 'Assistant Examiner of Accounts', null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Commissioner', 'COMM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Examiner of Accounts', 'EOA', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Junior Accounts Officer', 'JAO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Senior Accountant', 'SACC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Junior Accountant', 'JACC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Accountant Category - IV', 'ACIV', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Manager', 'MGR', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Deputy Executive Engineer', 'DEE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Senior Stenographer', 'SSTEN', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Typist', 'TYP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Record Assistant', 'RC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'System Manager', 'SM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'System Assistant/ Data Entry Operator', 'SYASST', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Office Subordinate', 'OS', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Night Watchmen', 'NW', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Ayah', 'AYH', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Secretary', 'SEC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant Commissioner', 'ACOMM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Public Relations Officer', 'PRO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Deputy Commissioner', 'DYCOMM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Superintendent', 'SUPR', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Education Officer', 'EO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'School Supervisor', 'SCHSUP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant Engineer', 'AE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Draughtsman', 'DRM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Work Inspector/ Technical Mastry', 'WI', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'CAD/GIS Operator', 'CADOP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Environmental Engineer (AE/AEE)', 'ENVE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Fitter', 'FIT', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Tank Watchers', 'TW', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Turn Cock', 'TC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Bore Well Attender', 'BOREA', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Electrician', 'ELEC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Lighting Superintendent', 'LS', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Park Mazdor', 'PM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Driver', 'DRV', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Chief Engineer', 'CE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'PA to Chief Engineer', 'PACE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Superintending Engineer', 'SUPRE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Executive Engineer', 'EE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant Executive Engineer', 'AEE', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Homeo Medical Officer', 'HMO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Sanitary Inspector', 'SI', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Health Assistant/Birth and Death Registrar', 'HA', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Sanitary Maistry/Jawan', 'SANM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'P H Worker', 'PHW', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Chief Medical Officer', 'CMO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant Medical Officer', 'AMO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Municipal Health Officer', 'MHO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Sanitary Supervisor', 'SS', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Revenue Officer', 'RO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Bill Collector', 'BC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'UD Revenue Inspector', 'UDRI', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Planning Officer (Special Grade)', 'TPOSPG', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Planning Supervisor', 'TPS', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Planning Building Overseer', 'TPB', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Tracer', 'TRC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Surveyor', 'TS', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Chainman', 'CHNM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Horticulture Officer', 'HRO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Chief City Planner', 'CCP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'City Planner', 'CP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Deputy City Planner', 'DCP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant City Planner', 'ACP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Planning Offcer (Selection Grade)', 'TPOSCG', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Planning Offcer (Ordinary Grade)', 'TPOORG', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Transportation Planner', 'TRANP', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Project Officer', 'TPRJO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Community Organiser', 'CO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Project Officer', 'PO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Town Corodinator', 'TWC', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant Project Officer', 'APO', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Deputy Statistical Officer', 'DSO', 'Deputy Statistical Officer', null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Veterinary officer', 'VO', 'Veterinary officer', null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Additional Commissioner', 'ADCOM', null, null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Deputy Chief Engineer', 'DCE', 'Deputy Chief Engineer', null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Technical Officer', 'TO', 'Technical Officer', null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Assistant Technical Officer', 'ATO', 'Assistant Technical Officer', null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Junior Technical Officer', 'JTO', 'Junior Technical Officer', null, true, 'default');
INSERT INTO egeis_designation (id, name, code, description, chartofaccounts, active, tenantid) VALUES (nextval('seq_egeis_designation'), 'Municipal Engineer', 'ME', 'Municipal Engineer', null, true, 'default');