title Bill Based Collection

Client->+BillingSvc: Search Demand & Generate Bill
note over Client,BillingSvc
    Validate search request and Post the request to
    billing service to generate bill for the 
    given parameters and prepare bill response
end note
BillingSvc->-Client: Bill Response

Client->+ReceiptSvc: Get collection modes allowed and bank List
note over Client,ReceiptSvc
    Get the collection modes allowed
    for the logged in user and the list 
    of bank from financial Service.
end note
ReceiptSvc->+FinancialSvc: Get bank list
note over ReceiptSvc,FinancialSvc
    Get the list of bank for Cheque/DD
    payments.
end note
FinancialSvc->-ReceiptSvc: Bank list response.
ReceiptSvc->-Client: Response with Collection modes allowed and bank list.

Client->+ReceiptSvc: Submit payment request
ReceiptSvc->ReceiptSvc: Validate payment request
ReceiptSvc->BillingSvc: Get the  apportioned receipt details list.
note over BillingSvc,ReceiptSvc
    Apportion the paid amount by invoking
    BillingSvc 
end note
BillingSvc->ReceiptSvc : Response apportioned receipt details list.
ReceiptSvc->IDGenSvc: Generate receipt number
ReceiptSvc->+BusinessDetailsSvc: Fetch misc information to enrich receipt
note over ReceiptSvc,BusinessDetailsSvc
    Fund, Function, Department defined for Business Details
    will be used to persist receipt.
end note
BusinessDetailsSvc->-ReceiptSvc: BusinessDetailsSvc
ReceiptSvc->ReceiptSvc: Persist receipt
ReceiptSvc->+KafkaQSvc: Queue for further processing
ReceiptSvc->-Client: Create receipt response

KafkaQSvc->WorkflowSvc: Initiate workflow
KafkaQSvc->InstrumentSvc : Persist instrument
KafkaQSvc->VoucherSvc: Post voucher in financials
KafkaQSvc->BillingSvc: Update demand system based on receipt created.
KafkaQSvc->ESSvc: Push to elastic search
KafkaQSvc->NotificationSvc: Send email/sms
