title Bill Based Collection

Client->+BillingSvc: Search Bill
note over Client,BillingSvc
    Validate search request and 
    prepare bill response
end note
BillingSvc->-Client: Demand/Bill Response


Client->+ReceiptSvc: Get collection modes allowed
note over Client,ReceiptSvc
    Get the collection modes allowed
    for the logged in user.
end note
ReceiptSvc->-Client: Response apportioned receipt details list.

Client->+FinancialSvc: Get bank list
note over Client,FinancialSvc
    Get the list of bank for Cheque/DD
    payments.
end note
FinancialSvc->-Client: Bank list reponse.

Client->+ReceiptSvc: Submit payment request
note over Client,ReceiptSvc
    Apportion the paid amount by invoking
    BillingSvc, create receipt
end note
ReceiptSvc->ReceiptSvc: Validate payment request
ReceiptSvc->IDGenSvc: Generate receipt number
ReceiptSvc->ReceiptSvc: Persist receipt
ReceiptSvc->+KafkaQSvc: Queue for further processing
ReceiptSvc->-Client: Create receipt response

KafkaQSvc->WorkflowSvc: Initiate workflow
KafkaQSvc->VoucherSvc: Post voucher in financials
KafkaQSvc->BillingSvc: Update demand system based on receipt date.
KafkaQSvc->ESSvc: Push to elastic search
KafkaQSvc->NotificationSvc: Send email/sms
