title Interaction Diagram for Collection Integration with Citizen Service

AdminBrowser->+CitizenSvc: Submit Application Request
CitizenSvc->+BillingSvc: Create Demand 
BillingSvc->CitizenSvc: Response with Business Details and Application number
CitizenSvc->AdminBrowser: Return Response with Business Details and Application number

AdminBrowser->+ReceiptSvc: [Redirect] : With BusinessDetails and Application number
note over ReceiptSvc
Refer BillBasedReceipt Interaction Diagram 
For the details of Receipt Creation
end note over 
AdminBrowser->+BillingSvc: [Auto submit] : Search Bill request with BusinessDetails and Application number
BillingSvc->ReceiptSvc: Request with bill generated and get the collection modes not allowed
ReceiptSvc->ReceiptSvc : Create Receipt
ReceiptSvc->-AdminBrowser: [Return URL] : With Created Receipt response Invoke CitizenSvc with return URL
note over ReceiptSvc,CitizenSvc
Invoke return url of the citizen service with 
Receipt Status, Receipt Number and Hash value(to be implemented later)
end note
