CREATE TABLE EGCL_RECEIPTHEADER(
  ID BIGINT,
  PAYEENAME CHARACTER VARYING(256),
  PAYEEADDRESS CHARACTER VARYING(1024),
  PAYEEEMAIL CHARACTER VARYING(254),
  PAIDBY CHARACTER VARYING(1024),
  REFERENCENUMBER CHARACTER VARYING(50),
  REFERENCEDATE TIMESTAMP WITHOUT TIME ZONE,
  RECEIPTTYPE CHARACTER(50) NOT NULL,
  RECEIPTNUMBER CHARACTER VARYING(50),
  RECEIPTDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  REFERENCEDESC CHARACTER VARYING(250),
  MANUALRECEIPTNUMBER CHARACTER VARYING(50),
  MANUALRECEIPTDATE TIMESTAMP WITHOUT TIME ZONE,
  BUSINESSDETAILS CHARACTER(50) NOT NULL,
  COLLECTIONTYPE CHARACTER(50),
  DISPLAYMSG CHARACTER VARYING(256),
  REFERENCE_CH_ID BIGINT,
  STATEID BIGINT,
  LOCATION BIGINT,
  ISRECONCILED BOOLEAN,
  STATUS CHARACTER(30) NOT NULL,
  REASONFORCANCELLATION CHARACTER VARYING(250),
  MINIMUMAMOUNT DOUBLE PRECISION,
  TOTALAMOUNT DOUBLE PRECISION,
  COLLMODESNOTALLWD CHARACTER VARYING(256),
  CONSUMERCODE CHARACTER VARYING(256),
  CHANNEL CHARACTER VARYING(20), 
  CONSUMERTYPE CHARACTER VARYING(100),
  FUND CHARACTER VARYING,
  FUNDSOURCE CHARACTER VARYING,
  FUNCTION CHARACTER VARYING,
  BOUNDARY CHARACTER VARYING,
  DEPARTMENT CHARACTER VARYING,
  VOUCHERHEADER CHARACTER VARYING,
  DEPOSITEDBRANCH CHARACTER VARYING,
  VERSION BIGINT NOT NULL DEFAULT 1,
  CREATEDBY BIGINT NOT NULL,
  CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
  LASTMODIFIEDBY BIGINT NOT NULL,
  LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE,
  TENANTID CHARACTER VARYING NOT NULL,
  CONSTRAINT PK_EGCL_RECEIPTHEADER PRIMARY KEY (ID,TENANTID),
  CONSTRAINT FK_RCPTHEAD_CHID FOREIGN KEY (REFERENCE_CH_ID, TENANTID) REFERENCES EGCL_RECEIPTHEADER (ID, TENANTID)
);

CREATE SEQUENCE SEQ_EGCL_RECEIPTHEADER;

CREATE TABLE EGCL_RECEIPTDETAILS
(
  ID BIGINT NOT NULL,
  CHARTOFACCOUNT CHARACTER VARYING NOT NULL,
  DRAMOUNT DOUBLE PRECISION,
  CRAMOUNT DOUBLE PRECISION,
  ORDERNUMBER BIGINT,
  RECEIPTHEADER BIGINT,
  ACTUALCRAMOUNTTOBEPAID DOUBLE PRECISION,
  DESCRIPTION CHARACTER VARYING(500),
  FINANCIALYEAR CHARACTER VARYING,
  ISACTUALDEMAND BOOLEAN,
  PURPOSE CHARACTER VARYING(50) NOT NULL,
  TENANTID CHARACTER VARYING NOT NULL,
  CONSTRAINT PK_EGCL_RECEIPTDETAILS PRIMARY KEY (ID,TENANTID),
  CONSTRAINT FK_RCPTDTLS_RCPTHEAD FOREIGN KEY (RECEIPTHEADER, TENANTID) REFERENCES EGCL_RECEIPTHEADER (ID, TENANTID) 
);

CREATE SEQUENCE SEQ_EGCL_RECEIPTDETAILS;

CREATE TABLE EGCL_RECEIPTINSTRUMENT
(
  RECEIPTHEADER BIGINT NOT NULL,
  INSTRUMENTHEADER CHARACTER VARYING NOT NULL,
  TENANTID CHARACTER VARYING NOT NULL,

  CONSTRAINT FK_RCPTINST_RCPTHEAD FOREIGN KEY (RECEIPTHEADER, TENANTID) REFERENCES EGCL_RECEIPTHEADER (ID, TENANTID)
); 

CREATE INDEX idx_rcpthd_consumercode
  ON egcl_receiptheader(consumercode);

CREATE INDEX idx_rcpthd_state
  ON egcl_receiptheader(stateid);

CREATE INDEX idx_rcpthd_createdby
  ON egcl_receiptheader(createdby);

CREATE INDEX idx_rcpthd_createddate
  ON egcl_receiptheader(receiptdate);

CREATE INDEX idx_rcpthd_mreceiptnumber
  ON egcl_receiptheader(manualreceiptnumber);

CREATE INDEX idx_rcpthd_refno
  ON egcl_receiptheader(referencenumber);

CREATE INDEX idx_rcpthd_business
  ON egcl_receiptheader(businessdetails);

CREATE INDEX idx_rcpthd_status
  ON egcl_receiptheader(status);



