CREATE TABLE EGASSET_ASSET (
	id bigint NOT NULL,
	assetCategory BIGINT NOT NULL,
	name CHARACTER VARYING(250) NOT NULL,
	code CHARACTER VARYING(250) NOT NULL,
	department BIGINT NOT NULL,
	location BIGINT,
	assetDetails CHARACTER VARYING(4000),
	description CHARACTER VARYING(1024),
	dateOfCreation TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	remarks CHARACTER VARYING(250),
	length CHARACTER VARYING(250),
	width CHARACTER VARYING(250),
	totalArea CHARACTER VARYING(250),
	properties CHARACTER VARYING(250),
	modeOfAcquisition CHARACTER VARYING(250),
    status CHARACTER VARYING(250) NOT NULL,
	tenantId CHARACTER VARYING(250),
	createdBy CHARACTER VARYING(64) NOT NULL,
	createdDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lastModifiedBy CHARACTER VARYING(64),
    lastModifiedDate TIMESTAMP WITHOUT TIME ZONE,

	CONSTRAINT PK_EGASSET_ASSET PRIMARY KEY (id)
);

CREATE SEQUENCE SEQ_EGASSET_ASSET INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;