package org.egov.lams.common.web.contract;
/*
 * eGov LAMS (Leases And Agreements System) APIs
 * eGov LAMS manages the Lease data for immovable assets owned by a ULB. This module aim is to improve lease operations in ULB. This will gives a comprehensive details of agreements for immovable assets like Land, Shopping Complex, Market, Kalyanamandapam, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * This object holds list of documents attached during the transacitons on agreement
 */
@ApiModel(description = "This object holds list of documents attached during the transacitons on agreement")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-01T12:22:22.713Z")
public class AgreementDocs {
  @SerializedName("id")
  private String id = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("agreement")
  private Agreement agreement = null;

  @SerializedName("documentType")
  private DocumentType documentType = null;

  @SerializedName("fileStore")
  private String fileStore = null;

  public AgreementDocs id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique Identifier of the AgreementDocs.
   * @return id
  **/
  @ApiModelProperty(value = "Unique Identifier of the AgreementDocs.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgreementDocs tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * tenant id of the AgreementDocs
   * @return tenantId
  **/
  @ApiModelProperty(value = "tenant id of the AgreementDocs")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public AgreementDocs agreement(Agreement agreement) {
    this.agreement = agreement;
    return this;
  }

   /**
   * Get agreement
   * @return agreement
  **/
  @ApiModelProperty(value = "")
  public Agreement getAgreement() {
    return agreement;
  }

  public void setAgreement(Agreement agreement) {
    this.agreement = agreement;
  }

  public AgreementDocs documentType(DocumentType documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  @ApiModelProperty(value = "")
  public DocumentType getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentType documentType) {
    this.documentType = documentType;
  }

  public AgreementDocs fileStore(String fileStore) {
    this.fileStore = fileStore;
    return this;
  }

   /**
   * File store reference key.
   * @return fileStore
  **/
  @ApiModelProperty(value = "File store reference key.")
  public String getFileStore() {
    return fileStore;
  }

  public void setFileStore(String fileStore) {
    this.fileStore = fileStore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementDocs agreementDocs = (AgreementDocs) o;
    return Objects.equals(this.id, agreementDocs.id) &&
        Objects.equals(this.tenantId, agreementDocs.tenantId) &&
        Objects.equals(this.agreement, agreementDocs.agreement) &&
        Objects.equals(this.documentType, agreementDocs.documentType) &&
        Objects.equals(this.fileStore, agreementDocs.fileStore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, agreement, documentType, fileStore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementDocs {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    agreement: ").append(toIndentedString(agreement)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    fileStore: ").append(toIndentedString(fileStore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

