/*
 * eGov LAMS (Leases And Agreements System) APIs
 * eGov LAMS manages the Lease data for immovable assets owned by a ULB. This module aim is to improve lease operations in ULB. This will gives a comprehensive details of agreements for immovable assets like Land, Shopping Complex, Market, Kalyanamandapam, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.egov.lams.common.web.contract;

import lombok.*;

import javax.validation.constraints.NotNull;

/**
 * Allottee is a citizen with whom the agreement is done
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Allottee {
  @NotNull
  private Long id = null;

  @NotNull
  private String name = null;

  private String address = null;

  private String mobileNumber = null;

  private String aadhaarNumber = null;

  private String pan = null;

  private String emailId = null;

}

