/*
 * eGov LAMS (Leases And Agreements System) APIs
 * eGov LAMS manages the Lease data for immovable assets owned by a ULB. This module aim is to improve lease operations in ULB. This will gives a comprehensive details of agreements for immovable assets like Land, Shopping Complex, Market, Kalyanamandapam, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.egov.lams.common.web.contract;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.validation.constraints.NotNull;
import java.util.Set;

/**
 * BoundaryType
 */
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
public class BoundaryType {
  @NotNull
  @JsonProperty("id")
  private String id;

  @JsonProperty("name")
  private String name;

  @JsonProperty("code")
  private String code;

  @JsonProperty("hierarchyType")
  private HierarchyType hierarchyType;

  @JsonProperty("parent")
  private BoundaryType parent;

  @JsonProperty("hierarchy")
  private Long hierarchy;

  @JsonProperty("localName")
  private String localName;

  @JsonProperty("parentName")
  private String parentName;

  @JsonProperty("childBoundaryTypes")
  private Set<BoundaryType> childBoundaryTypes;

  @JsonProperty("tenantId")
  private String tenantId;
}

