package org.egov.lams.common.web.contract;
/*
 
* eGov LAMS (Leases And Agreements System) APIs
 * eGov LAMS manages the Lease data for immovable assets owned by a ULB. This module aim is to improve lease operations in ULB. This will gives a comprehensive details of agreements for immovable assets like Land, Shopping Complex, Market, Kalyanamandapam, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A Object which holds the basic info about the revenue assessment for which the demand is generated like module name, consumercode, owner, etc.
 */
@ApiModel(description = "A Object which holds the basic info about the revenue assessment for which the demand is generated like module name, consumercode, owner, etc.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-01T12:22:22.713Z")
public class Demand {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("consumerCode")
  private String consumerCode = null;

  @SerializedName("consumerType")
  private String consumerType = null;

  @SerializedName("businessService")
  private String businessService = null;

  @SerializedName("owner")
  private User owner = null;

  @SerializedName("taxPeriodFrom")
  private Long taxPeriodFrom = null;

  @SerializedName("taxPeriodTo")
  private Long taxPeriodTo = null;

  @SerializedName("demandDetails")
  private List<DemandDetails> demandDetails = new ArrayList<DemandDetails>();

  @SerializedName("auditDetails")
  private AuditDetails auditDetails = null;

  @SerializedName("minimumAmountPayable")
  private Double minimumAmountPayable = null;

  public Demand id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * primary key of a demand.
   * @return id
  **/
  @ApiModelProperty(value = "primary key of a demand.")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

   /**
   * Unique Identifier of the tenant
   * @return tenantId
  **/
  @ApiModelProperty(required = true, value = "Unique Identifier of the tenant")
  public String getTenantId() {
    return tenantId;
  }

  public Demand consumerCode(String consumerCode) {
    this.consumerCode = consumerCode;
    return this;
  }

   /**
   * Unique identification of billing entity.
   * @return consumerCode
  **/
  @ApiModelProperty(required = true, value = "Unique identification of billing entity.")
  public String getConsumerCode() {
    return consumerCode;
  }

  public void setConsumerCode(String consumerCode) {
    this.consumerCode = consumerCode;
  }

  public Demand consumerType(String consumerType) {
    this.consumerType = consumerType;
    return this;
  }

   /**
   * Consumer type of billing entity.
   * @return consumerType
  **/
  @ApiModelProperty(value = "Consumer type of billing entity.")
  public String getConsumerType() {
    return consumerType;
  }

  public void setConsumerType(String consumerType) {
    this.consumerType = consumerType;
  }

  public Demand businessService(String businessService) {
    this.businessService = businessService;
    return this;
  }

   /**
   * Billing system e.g., Property Tax, Water Charges etc.
   * @return businessService
  **/
  @ApiModelProperty(required = true, value = "Billing system e.g., Property Tax, Water Charges etc.")
  public String getBusinessService() {
    return businessService;
  }

  public void setBusinessService(String businessService) {
    this.businessService = businessService;
  }

  public Demand owner(User owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @ApiModelProperty(value = "")
  public User getOwner() {
    return owner;
  }

  public void setOwner(User owner) {
    this.owner = owner;
  }

  public Demand taxPeriodFrom(Long taxPeriodFrom) {
    this.taxPeriodFrom = taxPeriodFrom;
    return this;
  }

   /**
   * start date from when the tax is applicable. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
   * @return taxPeriodFrom
  **/
  @ApiModelProperty(required = true, value = "start date from when the tax is applicable. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss")
  public Long getTaxPeriodFrom() {
    return taxPeriodFrom;
  }

  public void setTaxPeriodFrom(Long taxPeriodFrom) {
    this.taxPeriodFrom = taxPeriodFrom;
  }

  public Demand taxPeriodTo(Long taxPeriodTo) {
    this.taxPeriodTo = taxPeriodTo;
    return this;
  }

   /**
   * end date till when the tax is applicable. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
   * @return taxPeriodTo
  **/
  @ApiModelProperty(required = true, value = "end date till when the tax is applicable. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss")
  public Long getTaxPeriodTo() {
    return taxPeriodTo;
  }

  public void setTaxPeriodTo(Long taxPeriodTo) {
    this.taxPeriodTo = taxPeriodTo;
  }

  public Demand demandDetails(List<DemandDetails> demandDetails) {
    this.demandDetails = demandDetails;
    return this;
  }

  public Demand addDemandDetailsItem(DemandDetails demandDetailsItem) {
    this.demandDetails.add(demandDetailsItem);
    return this;
  }

   /**
   * Get demandDetails
   * @return demandDetails
  **/
  @ApiModelProperty(required = true, value = "")
  public List<DemandDetails> getDemandDetails() {
    return demandDetails;
  }

  public void setDemandDetails(List<DemandDetails> demandDetails) {
    this.demandDetails = demandDetails;
  }

  public Demand auditDetails(AuditDetails auditDetails) {
    this.auditDetails = auditDetails;
    return this;
  }

   /**
   * Get auditDetails
   * @return auditDetails
  **/
  @ApiModelProperty(value = "")
  public AuditDetails getAuditDetails() {
    return auditDetails;
  }

  public void setAuditDetails(AuditDetails auditDetails) {
    this.auditDetails = auditDetails;
  }

  public Demand minimumAmountPayable(Double minimumAmountPayable) {
    this.minimumAmountPayable = minimumAmountPayable;
    return this;
  }

   /**
   * Minimum bill amount to be paid.
   * @return minimumAmountPayable
  **/
  @ApiModelProperty(required = true, value = "Minimum bill amount to be paid.")
  public Double getMinimumAmountPayable() {
    return minimumAmountPayable;
  }

  public void setMinimumAmountPayable(Double minimumAmountPayable) {
    this.minimumAmountPayable = minimumAmountPayable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Demand demand = (Demand) o;
    return Objects.equals(this.id, demand.id) &&
        Objects.equals(this.tenantId, demand.tenantId) &&
        Objects.equals(this.consumerCode, demand.consumerCode) &&
        Objects.equals(this.consumerType, demand.consumerType) &&
        Objects.equals(this.businessService, demand.businessService) &&
        Objects.equals(this.owner, demand.owner) &&
        Objects.equals(this.taxPeriodFrom, demand.taxPeriodFrom) &&
        Objects.equals(this.taxPeriodTo, demand.taxPeriodTo) &&
        Objects.equals(this.demandDetails, demand.demandDetails) &&
        Objects.equals(this.auditDetails, demand.auditDetails) &&
        Objects.equals(this.minimumAmountPayable, demand.minimumAmountPayable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, consumerCode, consumerType, businessService, owner, taxPeriodFrom, taxPeriodTo, demandDetails, auditDetails, minimumAmountPayable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Demand {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    consumerCode: ").append(toIndentedString(consumerCode)).append("\n");
    sb.append("    consumerType: ").append(toIndentedString(consumerType)).append("\n");
    sb.append("    businessService: ").append(toIndentedString(businessService)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    taxPeriodFrom: ").append(toIndentedString(taxPeriodFrom)).append("\n");
    sb.append("    taxPeriodTo: ").append(toIndentedString(taxPeriodTo)).append("\n");
    sb.append("    demandDetails: ").append(toIndentedString(demandDetails)).append("\n");
    sb.append("    auditDetails: ").append(toIndentedString(auditDetails)).append("\n");
    sb.append("    minimumAmountPayable: ").append(toIndentedString(minimumAmountPayable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

