package org.egov.lams.common.web.contract;
/*

 * eGov LAMS (Leases And Agreements System) APIs
 * eGov LAMS manages the Lease data for immovable assets owned by a ULB. This module aim is to improve lease operations in ULB. This will gives a comprehensive details of agreements for immovable assets like Land, Shopping Complex, Market, Kalyanamandapam, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A object holds a demand and collection values for a tax head and period.
 */
@ApiModel(description = "A object holds a demand and collection values for a tax head and period.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-01T12:22:22.713Z")
public class DemandDetails {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("taxHead")
  private String taxHead = null;

  @SerializedName("taxAmount")
  private Double taxAmount = null;

  @SerializedName("collectionAmount")
  private Double collectionAmount = 0.0d;

  @SerializedName("auditDetails")
  private AuditDetails auditDetails = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  public DemandDetails id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * primary key of a DemandDetails.
   * @return id
  **/
  @ApiModelProperty(value = "primary key of a DemandDetails.")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DemandDetails taxHead(String taxHead) {
    this.taxHead = taxHead;
    return this;
  }

   /**
   * Tax Head code.
   * @return taxHead
  **/
  @ApiModelProperty(required = true, value = "Tax Head code.")
  public String getTaxHead() {
    return taxHead;
  }

  public void setTaxHead(String taxHead) {
    this.taxHead = taxHead;
  }

  public DemandDetails taxAmount(Double taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

   /**
   * demand amount.
   * @return taxAmount
  **/
  @ApiModelProperty(required = true, value = "demand amount.")
  public Double getTaxAmount() {
    return taxAmount;
  }

  public void setTaxAmount(Double taxAmount) {
    this.taxAmount = taxAmount;
  }

  public DemandDetails collectionAmount(Double collectionAmount) {
    this.collectionAmount = collectionAmount;
    return this;
  }

   /**
   * collection against taxAmount.
   * @return collectionAmount
  **/
  @ApiModelProperty(required = true, value = "collection against taxAmount.")
  public Double getCollectionAmount() {
    return collectionAmount;
  }

  public void setCollectionAmount(Double collectionAmount) {
    this.collectionAmount = collectionAmount;
  }

  public DemandDetails auditDetails(AuditDetails auditDetails) {
    this.auditDetails = auditDetails;
    return this;
  }

   /**
   * Get auditDetails
   * @return auditDetails
  **/
  @ApiModelProperty(value = "")
  public AuditDetails getAuditDetails() {
    return auditDetails;
  }

  public void setAuditDetails(AuditDetails auditDetails) {
    this.auditDetails = auditDetails;
  }

   /**
   * Unique Identifier of the tenant
   * @return tenantId
  **/
  @ApiModelProperty(required = true, value = "Unique Identifier of the tenant")
  public String getTenantId() {
    return tenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DemandDetails demandDetails = (DemandDetails) o;
    return Objects.equals(this.id, demandDetails.id) &&
        Objects.equals(this.taxHead, demandDetails.taxHead) &&
        Objects.equals(this.taxAmount, demandDetails.taxAmount) &&
        Objects.equals(this.collectionAmount, demandDetails.collectionAmount) &&
        Objects.equals(this.auditDetails, demandDetails.auditDetails) &&
        Objects.equals(this.tenantId, demandDetails.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, taxHead, taxAmount, collectionAmount, auditDetails, tenantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DemandDetails {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    taxHead: ").append(toIndentedString(taxHead)).append("\n");
    sb.append("    taxAmount: ").append(toIndentedString(taxAmount)).append("\n");
    sb.append("    collectionAmount: ").append(toIndentedString(collectionAmount)).append("\n");
    sb.append("    auditDetails: ").append(toIndentedString(auditDetails)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

