/*
 * eGov LAMS (Leases And Agreements System) APIs
 * eGov LAMS manages the Lease data for immovable assets owned by a ULB. This module aim is to improve lease operations in ULB. This will gives a comprehensive details of agreements for immovable assets like Land, Shopping Complex, Market, Kalyanamandapam, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.egov.lams.common.web.contract;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * This object holds list of documents attached during the transaciton for a
 * agreement Author : Ramki
 */

@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
public class Document {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("documentType")
  @NotNull
  private String documentType = null;

  @JsonProperty("fileStore")
  private String fileStore = null;

  @JsonProperty("auditDetails")
  private AuditDetails auditDetails = null;

}

