/*
 * eGov Land Management
 * APIs for Land management module. This modules handles Proposal for Land Acquisition (create,update,search of required land acquisition), land possession,transfer of land to manage the land acquisition within the ulb jurisdiction. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contacts@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.lams.common.web.contract;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.egov.common.contract.request.RequestInfo;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "Contract class to receive request. Array of Land Possession items are used in case of create, whereas single Land Possession item is used for update")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-26T05:34:54.775Z")
public class LandPossessionRequest {
  @SerializedName("requestInfo")
  private RequestInfo requestInfo = null;

  @SerializedName("landPossession")
  private List<LandPossession> landPossession = null;

  public LandPossessionRequest requestInfo(RequestInfo requestInfo) {
    this.requestInfo = requestInfo;
    return this;
  }

   /**
   * Get requestInfo
   * @return requestInfo
  **/
  @ApiModelProperty(value = "")
  public RequestInfo getRequestInfo() {
    return requestInfo;
  }

  public void setRequestInfo(RequestInfo requestInfo) {
    this.requestInfo = requestInfo;
  }

  public LandPossessionRequest landPossession(List<LandPossession> landPossession) {
    this.landPossession = landPossession;
    return this;
  }

  public LandPossessionRequest addLandPossessionItem(LandPossession landPossessionItem) {
    if (this.landPossession == null) {
      this.landPossession = new ArrayList<LandPossession>();
    }
    this.landPossession.add(landPossessionItem);
    return this;
  }

   /**
   * Used for search result and create only
   * @return landPossession
  **/
  @ApiModelProperty(value = "Used for search result and create only")
  public List<LandPossession> getLandPossession() {
    return landPossession;
  }

  public void setLandPossession(List<LandPossession> landPossession) {
    this.landPossession = landPossession;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandPossessionRequest landPossessionRequest = (LandPossessionRequest) o;
    return Objects.equals(this.requestInfo, landPossessionRequest.requestInfo) &&
        Objects.equals(this.landPossession, landPossessionRequest.landPossession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestInfo, landPossession);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandPossessionRequest {\n");
    
    sb.append("    requestInfo: ").append(toIndentedString(requestInfo)).append("\n");
    sb.append("    landPossession: ").append(toIndentedString(landPossession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

