/*
 * eGov Land Management
 * APIs for Land management module. This modules handles Proposal for Land Acquisition (create,update,search of required land acquisition), land possession,transfer of land to manage the land acquisition within the ulb jurisdiction. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contacts@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.egov.lams.common.web.contract;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import org.egov.common.contract.response.ResponseInfo;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

/**
 * Contract class to send response. Array of Land Possession detail items are used in case of search results or response for create, whereas single land possession detail item is used for update
 */
@ApiModel(description = "Contract class to send response. Array of Land Possession detail items are used in case of search results or response for create, whereas single land possession detail item is used for update")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-26T05:34:54.775Z")
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class LandPossessionResponse {
  @SerializedName("responseInfo")
  private ResponseInfo responseInfo = null;

  @SerializedName("landPossession")
  private List<LandPossession> landPossession = null;

  public LandPossessionResponse responseInfo(ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
    return this;
  }

   /**
   * Get responseInfo
   * @return responseInfo
  **/
  @ApiModelProperty(value = "")
  public ResponseInfo getResponseInfo() {
    return responseInfo;
  }

  public void setResponseInfo(ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
  }

  public LandPossessionResponse landPossession(List<LandPossession> landPossession) {
    this.landPossession = landPossession;
    return this;
  }

  public LandPossessionResponse addLandPossessionItem(LandPossession landPossessionItem) {
    if (this.landPossession == null) {
      this.landPossession = new ArrayList<LandPossession>();
    }
    this.landPossession.add(landPossessionItem);
    return this;
  }

   /**
   * Used for search result and create only
   * @return landPossession
  **/
  @ApiModelProperty(value = "Used for search result and create only")
  public List<LandPossession> getLandPossession() {
    return landPossession;
  }

  public void setLandPossession(List<LandPossession> landPossession) {
    this.landPossession = landPossession;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandPossessionResponse landPossessionResponse = (LandPossessionResponse) o;
    return Objects.equals(this.responseInfo, landPossessionResponse.responseInfo) &&
        Objects.equals(this.landPossession, landPossessionResponse.landPossession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseInfo, landPossession);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandPossessionResponse {\n");
    
    sb.append("    responseInfo: ").append(toIndentedString(responseInfo)).append("\n");
    sb.append("    landPossession: ").append(toIndentedString(landPossession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

