update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Stall Details","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Market' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Total Square Feet Area","type":"Number","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Built up area","type":"Number","isActive":true,"isMandatory":false,"columns":[]},{"name":"Amenities","type":"Table","isActive":false,"isMandatory":false,"columns":[{"name":"Type","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total count","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}]}' where name='Kalyana Mandapam' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Parking Space' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Slaughter House' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Usufruct' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Fish Tanks' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Parks' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Door No.","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Shopping Complex No.","type":"Text","isActive":true,"isMandatory":true,"columns":[]},{"name":"No. of Floors","type":"Number","isActive":true,"isMandatory":true,"columns":[]},{"name":"Total No. of Shops","type":"Number","isActive":true,"isMandatory":true,"columns":[]},{"name":"Floor Details","type":"Table","isActive":false,"isMandatory":false,"columns":[{"name":"Floor No.","type":"Text","isActive":true,"isMandatory":true,"columns":[]},{"name":"No. of Shops","type":"Text","isActive":true,"isMandatory":true,"columns":[]}]}]}' where name='Shopping Complex' and tenantid='default';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Community toilet complex Name","type":"Text","isActive":true,"isMandatory":true,"order":"1","columns":[]},{"name":"East","type":"Text","isActive":true,"isMandatory":false,"order":"2","columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"order":"4","columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"order":"5","columns":[]},{"name":"Total Square feet area","type":"Text","isActive":true,"isMandatory":false,"order":"6","columns":[]}]}' where name='Community Toilet Complex' and tenantid='default';


