update egasset_assetcategory set tenantid='default' where tenantid='ap.kurnool';

INSERT INTO egasset_assetcategory (id, name, code, assetcategorytype,customfields, tenantid, createdby, createddate, version) VALUES (nextval('seq_egasset_assetcategory'),'Drains and Culvets','017','IMMOVABLE','{"assetFieldsDefination":[{"name":"Classification of the drain","type":"Select","isActive":true,"isMandatory":true,"values":"Open drain, Underground drain","order":"1","columns":[]},{"name":"Type of drain","type":"Select","isActive":true,"isMandatory":false,"values":"Outfall,Primary,Secondary,Tertiary,Earthen","order":"2","columns":[]},{"name":"Classification of culvert","type":"Select","isActive":true,"isMandatory":false,"values":"Masonry,Pipe,Concrete,Donation,Concrete","order":"3","columns":[]},{"name":"Length","type":"Text","isActive":true,"isMandatory":true,"order":"4","columns":[]},{"name":"Breadth","type":"Text","isActive":true,"isMandatory":true,"order":"5","columns":[]},{"name":"Height","type":"Text","isActive":true,"isMandatory":true,"order":"6","columns":[]},{"name":"Land Area (acre/sqmtrs)","type":"Text","isActive":true,"isMandatory":true,"order":"7","columns":[]},{"name":"Land Survey Number","type":"Text","isActive":true,"isMandatory":true,"order":"8","columns":[]},{"name":"Condition of the asset","type":"Select","isActive":true,"isMandatory":true,"values":"Good,Dilapidated","order":"9","columns":[]},{"name":"Available Doc List","type":"Text","isActive":true,"isMandatory":false,"order":"10","columns":[]},{"name":"Description of the drain","type":"Text","isActive":true,"isMandatory":false,"order":"11","columns":[]}]}','default',1 ,current_date,1);

INSERT INTO egasset_assetcategory (id, name, code, assetcategorytype,customfields, tenantid, createdby, createddate, version) VALUES (nextval('seq_egasset_assetcategory'),'Street light','019','IMMOVABLE','{"assetFieldsDefination":[{"name":"Road Survey Number","type":"Text","isActive":true,"isMandatory":false,"order":"1","columns":[]},{"name":"Street lighting Category","type":"Select","isActive":true,"isMandatory":false,"values":"Street lights,High mast lights,Central lighting","order":"2","columns":[]},{"name":"Length of cables used","type":"Text","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"Pole Type","type":"Select","isActive":true,"isMandatory":false,"values":"Concrete,Iron,Others","order":"4","columns":[]},{"name":"Source of energy","type":"Select","isActive":true,"isMandatory":false,"values":"Solar,Electric Power","order":"5","columns":[]},{"name":"No of Lamp Posts","type":"Number","isActive":true,"isMandatory":false,"order":"6","columns":[]},{"name":"No. of bulbs in thepost","type":"Number","isActive":true,"isMandatory":false,"order":"7","columns":[]},{"name":"Street Lights Bulbs","type":"Select","isActive":true,"isMandatory":false,"values":"Mercury vapour,Sodium vapour,Metalloid,LED,Tubelights,CFL,Others","order":"8","columns":[]},{"name":"Cost of lamp posts and erection charges","type":"Text","isActive":true,"isMandatory":false,"order":"9","columns":[]},{"name":"Available Doc List","type":"Text","isActive":true,"isMandatory":false,"order":"10","columns":[]}]}','default',1 ,current_date,1);

INSERT INTO egasset_assetcategory (id, name, code, assetcategorytype,customfields, tenantid, createdby, createddate, version) VALUES (nextval('seq_egasset_assetcategory'),'Lakes and Ponds','020','IMMOVABLE','{"assetFieldsDefination":[{"name":"Usage","type":"Select","isActive":true,"isMandatory":false,"values":"Drinking,Aqua culture,Irrigation,\nOthers","order":"1","columns":[]},{"name":"Possession","type":"Select","isActive":true,"isMandatory":false,"values":"Owned,Leased","order":"2","columns":[]},{"name":"Land Survey Number","type":"Text","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"Area (acre/sqmtr)","type":"Text","isActive":true,"isMandatory":false,"order":"4","columns":[]},{"name":"Acquired from","type":"Text","isActive":true,"isMandatory":false,"order":"5","columns":[]},{"name":"Available Doc List","type":"Text","isActive":true,"isMandatory":false,"order":"6","columns":[]}]}','default',1 ,current_date,1);

INSERT INTO egasset_assetcategory (id, name, code, assetcategorytype,customfields, tenantid, createdby, createddate, version) VALUES (nextval('seq_egasset_assetcategory'),'Plant and Machinery','021','MOVABLE','{"assetFieldsDefination":[{"name":"Capacity","type":"Text","isActive":true,"isMandatory":true,"order":"1","columns":[]},{"name":"Condition of Machinery","type":"Select","isActive":true,"isMandatory":true,"values":"Operational,Non-Operational","order":"2","columns":[]},{"name":"Since when non-operational","type":"Text","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"Acquired from","type":"Text","isActive":true,"isMandatory":false,"order":"4","columns":[]},{"name":"Available Doc List","type":"Text","isActive":true,"isMandatory":true,"order":"5","columns":[]}]}', 'default',1 ,current_date,1);                                        

INSERT INTO egasset_assetcategory (id, name, code, assetcategorytype,customfields, tenantid, createdby, createddate, version) VALUES (nextval('seq_egasset_assetcategory'),'Vehicle','022','MOVABLE','{"assetFieldsDefination":[{"name":"Type of Vehicle","type":"Text","isActive":true,"isMandatory":false,"order":"1","columns":[]},{"name":"Year of Manufacture","type":"Text","isActive":true,"isMandatory":false,"order":"2","columns":[]},{"name":"Registration Details","type":"Text","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"Engine Number","type":"Text","isActive":true,"isMandatory":false,"order":"4","columns":[]},{"name":"Chassis Number","type":"Text","isActive":true,"isMandatory":false,"order":"5","columns":[]},{"name":"Acquired from","type":"Text","isActive":true,"isMandatory":false,"order":"6","columns":[]},{"name":"Acquisition Cost","type":"Text","isActive":true,"isMandatory":false,"order":"7","columns":[]},{"name":"Available Doc List","type":"Text","isActive":true,"isMandatory":false,"order":"8","columns":[]}]}','default',1 ,current_date,1);                                                                     

INSERT INTO egasset_assetcategory (id, name, code, assetcategorytype,customfields, tenantid, createdby, createddate, version) VALUES (nextval('seq_egasset_assetcategory'),'Community Toilet Complex','023','IMMOVABLE','{"assetFieldsDefination":[{"name":"Community toilet complex Name","type":"Text","isActive":true,"isMandatory":true,"order":"1","columns":[]},{"name":"East","type":"Text","isActive":true,"isMandatory":false,"order":"2","columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"order":"4","columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"order":"5","columns":[]},{"name":"Total Square feet area","type":"Text","isActive":true,"isMandatory":false,"order":"6","columns":[]}]}','default',1 ,current_date,1); 

INSERT INTO egasset_assetcategory (id, name, code, assetcategorytype,customfields, tenantid, createdby, createddate, version) VALUES (nextval('seq_egasset_assetcategory'),'Roads','024','IMMOVABLE','{"assetFieldsDefination":[{"name":"Road type","type":"Select","isActive":true,"isMandatory":true,"values":"Black top road , concrete road","order":"1","columns":[]},{"name":"Length(m)","type":"Number","isActive":true,"isMandatory":false,"order":"2","columns":[]},{"name":"Width(m)","type":"Number","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"Area(Sq.m)","type":"Number","isActive":true,"isMandatory":false,"order":"4","columns":[]}]}','default',1 ,current_date,1);
                                                                                                                                               

ALTER SEQUENCE seq_egasset_categorycode RESTART WITH 30;