update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Stall Details","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Market';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Total Square Feet Area","type":"Number","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Built up area","type":"Number","isActive":true,"isMandatory":false,"columns":[]},{"name":"Amenities","type":"Table","isActive":false,"isMandatory":false,"columns":[{"name":"Type","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total count","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}]}' where name='Kalyana Mandapam';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Parking Space';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Slaughter House';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Usufruct';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Fish Tanks';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"East","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Remarks","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Total Square feet area","type":"Number","isActive":true,"isMandatory":false,"columns":[]}]}' where name='Parks';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Door No.","type":"Text","isActive":true,"isMandatory":false,"columns":[]},{"name":"Shopping Complex No.","type":"Text","isActive":true,"isMandatory":true,"columns":[]},{"name":"No. of Floors","type":"Number","isActive":true,"isMandatory":true,"columns":[]},{"name":"Total No. of Shops","type":"Number","isActive":true,"isMandatory":true,"columns":[]},{"name":"Floor Details","type":"Table","isActive":false,"isMandatory":false,"columns":[{"name":"Floor No.","type":"Text","isActive":true,"isMandatory":true,"columns":[]},{"name":"No. of Shops","type":"Text","isActive":true,"isMandatory":true,"columns":[]}]}]}' where name='Shopping Complex';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Community toilet complex Name","type":"Text","isActive":true,"isMandatory":true,"order":"1","columns":[]},{"name":"East","type":"Text","isActive":true,"isMandatory":false,"order":"2","columns":[]},{"name":"South","type":"Text","isActive":true,"isMandatory":false,"order":"3","columns":[]},{"name":"West","type":"Text","isActive":true,"isMandatory":false,"order":"4","columns":[]},{"name":"North","type":"Text","isActive":true,"isMandatory":false,"order":"5","columns":[]},{"name":"Total Square feet area","type":"Text","isActive":true,"isMandatory":false,"order":"6","columns":[]}]}' where name='Community Toilet Complex';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Classification of the drain","type":"Select","isActive":true,"isMandatory":true,"values":"Open drain, Underground drain","order":"1","columns":[]},{"name":"Type of drain","type":"Select","isActive":true,"isMandatory":false,"values":"Outfall,Primary,Secondary,Tertiary,Earthen","order":"2","columns":[]},{"name":"Classification of culvert","type":"Select","isActive":true,"isMandatory":false,"values":"Masonry,Pipe,Concrete,Donation,Concrete","order":"3","columns":[]},{"name":"Length","type":"Text","isActive":true,"isMandatory":true,"order":"4","columns":[]},{"name":"Breadth","type":"Text","isActive":true,"isMandatory":true,"order":"5","columns":[]},{"name":"Height","type":"Text","isActive":true,"isMandatory":true,"order":"6","columns":[]},{"name":"Land Area (acre/sqmtrs)","type":"Text","isActive":true,"isMandatory":true,"order":"7","columns":[]},{"name":"Condition of the asset","type":"Select","isActive":true,"isMandatory":true,"values":"Good,Dilapidated","order":"9","columns":[]},{"name":"Available Doc List","type":"Text","isActive":true,"isMandatory":false,"order":"10","columns":[]},{"name":"Description of the drain","type":"Text","isActive":true,"isMandatory":false,"order":"11","columns":[]}]}' where name='Drains and Culvets';

update egasset_assetcategory set customfields='{"assetFieldsDefination":[{"name":"Usage","type":"Select","isActive":true,"isMandatory":false,"values":"Drinking,Aqua culture,Irrigation,\nOthers","order":"1","columns":[]},{"name":"Possession","type":"Select","isActive":true,"isMandatory":false,"values":"Owned,Leased","order":"2","columns":[]},{"name":"Area (acre/sqmtr)","type":"Text","isActive":true,"isMandatory":false,"order":"4","columns":[]},{"name":"Acquired from","type":"Text","isActive":true,"isMandatory":false,"order":"5","columns":[]},{"name":"Available Doc List","type":"Text","isActive":true,"isMandatory":false,"order":"6","columns":[]}]}' where name='Lakes and Ponds';

